project:
  type: book

book:
  title: "esl"
  author: "Norah Jones"
  date: "3/16/2026"
  chapters:
    - index.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt



