# Preface {.unnumbered}

*In God we trust, all others bring data.*

—William Edwards Deming (1900-1993)<sup>1</sup>

We have been gratified by the popularity of the first edition of *The Elements of Statistical Learning*. This, along with the fast pace of research in the statistical learning field, motivated us to update our book with a second edition.

We have added four new chapters and updated some of the existing chapters. Because many readers are familiar with the layout of the first edition, we have tried to change it as little as possible. Here is a summary of the main changes:

---

<sup>1</sup>On the Web, this quote has been widely attributed to both Deming and Robert W. Hayden; however Professor Hayden told us that he can claim no credit for this quote, and ironically we could find no “data” confirming that Deming actually said this.

| Chapter                                                       | What's new                                                                                                                                                                              |
|---------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| <b>1. Introduction</b>                                        |                                                                                                                                                                                         |
| <b>2. Overview of Supervised Learning</b>                     |                                                                                                                                                                                         |
| <b>3. Linear Methods for Regression</b>                       | LAR algorithm and generalizations of the lasso                                                                                                                                          |
| <b>4. Linear Methods for Classification</b>                   | Lasso path for logistic regression                                                                                                                                                      |
| <b>5. Basis Expansions and Regularization</b>                 | Additional illustrations of RKHS                                                                                                                                                        |
| <b>6. Kernel Smoothing Methods</b>                            |                                                                                                                                                                                         |
| <b>7. Model Assessment and Selection</b>                      | Strengths and pitfalls of cross-validation                                                                                                                                              |
| <b>8. Model Inference and Averaging</b>                       |                                                                                                                                                                                         |
| <b>9. Additive Models, Trees, and Related Methods</b>         |                                                                                                                                                                                         |
| <b>10. Boosting and Additive Trees</b>                        | New example from ecology; some material split off to Chapter 16.                                                                                                                        |
| <b>11. Neural Networks</b>                                    | Bayesian neural nets and the NIPS 2003 challenge                                                                                                                                        |
| <b>12. Support Vector Machines and Flexible Discriminants</b> | Path algorithm for SVM classifier                                                                                                                                                       |
| <b>13. Prototype Methods and Nearest-Neighbors</b>            |                                                                                                                                                                                         |
| <b>14. Unsupervised Learning</b>                              | Spectral clustering, kernel PCA, sparse PCA, non-negative matrix factorization archetypal analysis, nonlinear dimension reduction, Google page rank algorithm, a direct approach to ICA |
| <b>15. Random Forests</b>                                     | New                                                                                                                                                                                     |
| <b>16. Ensemble Learning</b>                                  | New                                                                                                                                                                                     |
| <b>17. Undirected Graphical Models</b>                        | New                                                                                                                                                                                     |
| <b>18. High-Dimensional Problems</b>                          | New                                                                                                                                                                                     |

Some further notes:

- Our first edition was unfriendly to colorblind readers; in particular, we tended to favor red/green contrasts which are particularly troublesome. We have changed the color palette in this edition to a large extent, replacing the above with an orange/blue contrast.
- We have changed the name of Chapter 6 from “Kernel Methods” to “Kernel Smoothing Methods”, to avoid confusion with the machine-learning kernel method that is discussed in the context of support vector machines (Chapter 12) and more generally in Chapters 5 and 14.
- In the first edition, the discussion of error-rate estimation in Chapter 7 was sloppy, as we did not clearly differentiate the notions of conditional error rates (conditional on the training set) and unconditional rates. We have fixed this in the new edition.

- Chapters 15 and 16 follow naturally from Chapter 10, and the chapters are probably best read in that order.
- In Chapter 17, we have not attempted a comprehensive treatment of graphical models, and discuss only undirected models and some new methods for their estimation. Due to a lack of space, we have specifically omitted coverage of directed graphical models.
- Chapter 18 explores the “ $p \gg N$ ” problem, which is learning in high-dimensional feature spaces. These problems arise in many areas, including genomic and proteomic studies, and document classification.

We thank the many readers who have found the (too numerous) errors in the first edition. We apologize for those and have done our best to avoid errors in this new edition. We thank Mark Segal, Bala Rajaratnam, and Larry Wasserman for comments on some of the new chapters, and many Stanford graduate and post-doctoral students who offered comments, in particular Mohammed AlQuraishi, John Boik, Holger Hoefling, Arian Maleki, Donal McMahon, Saharon Rosset, Babak Shababa, Daniela Witten, Ji Zhu and Hui Zou. We thank John Kimmel for his patience in guiding us through this new edition. RT dedicates this edition to the memory of Anna McPhee.

*Trevor Hastie  
Robert Tibshirani  
Jerome Friedman*  
Stanford, California  
August 2008