<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.35">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>4&nbsp; Linear Methods for Classification – esl</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../chapters/05-basis-expansions-and-regularization.html" rel="next">
<link href="../chapters/03-linear-methods-for-regression.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-46f66b053e56abd73bb6e954d61a315b.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-5ccb035bea26c1e21f80f44cf7c27909.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/04-linear-methods-for-classification.html"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Linear Methods for Classification</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">esl</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/01-introduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/02-overview-of-supervised-learning.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Overview of Supervised Learning</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/03-linear-methods-for-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Linear Methods for Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/04-linear-methods-for-classification.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Linear Methods for Classification</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/05-basis-expansions-and-regularization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Basis Expansions and Regularization</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/06-kernel-smoothing-methods.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Kernel Smoothing Methods</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/07-model-assessment-and-selection.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Model Assessment and Selection</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/08-model-inference-and-averaging.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Model Inference and Averaging</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/09-additive-models-trees-and-related-methods.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Additive Models, Trees, and Related Methods</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/10-boosting-and-additive-trees.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Boosting and Additive Trees</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/11-neural-networks.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Neural Networks</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/12-support-vector-machines-and-flexible-discriminants.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Support Vector Machines and Flexible Discriminants</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/13-prototype-methods-and-nearest-neighbors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Prototype Methods and Nearest-Neighbors</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/14-unsupervised-learning.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Unsupervised Learning</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/15-random-forests.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Random Forests</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/16-ensemble-learning.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Ensemble Learning</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/17-undirected-graphical-models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Undirected Graphical Models</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/18-high-dimensional-problems.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">High-Dimensional Problems: p ≫ N</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/19-references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">References</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/20-author-index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Author Index</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/21-index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Index</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"><span class="header-section-number">4.1</span> 4.1 Introduction</a></li>
  <li><a href="#linear-regression-of-an-indicator-matrix" id="toc-linear-regression-of-an-indicator-matrix" class="nav-link" data-scroll-target="#linear-regression-of-an-indicator-matrix"><span class="header-section-number">4.2</span> 4.2 Linear Regression of an Indicator Matrix</a></li>
  <li><a href="#linear-discriminant-analysis" id="toc-linear-discriminant-analysis" class="nav-link" data-scroll-target="#linear-discriminant-analysis"><span class="header-section-number">4.3</span> 4.3 Linear Discriminant Analysis</a>
  <ul class="collapse">
  <li><a href="#regularized-discriminant-analysis-on-the-vowel-data" id="toc-regularized-discriminant-analysis-on-the-vowel-data" class="nav-link" data-scroll-target="#regularized-discriminant-analysis-on-the-vowel-data"><span class="header-section-number">4.3.1</span> Regularized Discriminant Analysis on the Vowel Data</a></li>
  <li><a href="#regularized-discriminant-analysis" id="toc-regularized-discriminant-analysis" class="nav-link" data-scroll-target="#regularized-discriminant-analysis"><span class="header-section-number">4.3.2</span> 4.3.1 Regularized Discriminant Analysis</a></li>
  <li><a href="#computations-for-lda" id="toc-computations-for-lda" class="nav-link" data-scroll-target="#computations-for-lda"><span class="header-section-number">4.3.3</span> 4.3.2 Computations for LDA</a></li>
  <li><a href="#reduced-rank-linear-discriminant-analysis" id="toc-reduced-rank-linear-discriminant-analysis" class="nav-link" data-scroll-target="#reduced-rank-linear-discriminant-analysis"><span class="header-section-number">4.3.4</span> 4.3.3 Reduced-Rank Linear Discriminant Analysis</a></li>
  </ul></li>
  <li><a href="#logistic-regression" id="toc-logistic-regression" class="nav-link" data-scroll-target="#logistic-regression"><span class="header-section-number">4.4</span> 4.4 Logistic Regression</a>
  <ul class="collapse">
  <li><a href="#fitting-logistic-regression-models" id="toc-fitting-logistic-regression-models" class="nav-link" data-scroll-target="#fitting-logistic-regression-models"><span class="header-section-number">4.4.1</span> 4.4.1 Fitting Logistic Regression Models</a></li>
  <li><a href="#example-south-african-heart-disease" id="toc-example-south-african-heart-disease" class="nav-link" data-scroll-target="#example-south-african-heart-disease"><span class="header-section-number">4.4.2</span> 4.4.2 Example: South African Heart Disease</a></li>
  <li><a href="#quadratic-approximations-and-inference" id="toc-quadratic-approximations-and-inference" class="nav-link" data-scroll-target="#quadratic-approximations-and-inference"><span class="header-section-number">4.4.3</span> 4.4.3 Quadratic Approximations and Inference</a></li>
  <li><a href="#l1-regularized-logistic-regression" id="toc-l1-regularized-logistic-regression" class="nav-link" data-scroll-target="#l1-regularized-logistic-regression"><span class="header-section-number">4.4.4</span> 4.4.4 L<sub>1</sub> Regularized Logistic Regression</a></li>
  <li><a href="#logistic-regression-or-lda" id="toc-logistic-regression-or-lda" class="nav-link" data-scroll-target="#logistic-regression-or-lda"><span class="header-section-number">4.4.5</span> 4.4.5 Logistic Regression or LDA?</a></li>
  </ul></li>
  <li><a href="#separating-hyperplanes" id="toc-separating-hyperplanes" class="nav-link" data-scroll-target="#separating-hyperplanes"><span class="header-section-number">4.5</span> 4.5 Separating Hyperplanes</a>
  <ul class="collapse">
  <li><a href="#rosenblatts-perceptron-learning-algorithm" id="toc-rosenblatts-perceptron-learning-algorithm" class="nav-link" data-scroll-target="#rosenblatts-perceptron-learning-algorithm"><span class="header-section-number">4.5.1</span> 4.5.1 Rosenblatt’s Perceptron Learning Algorithm</a></li>
  <li><a href="#optimal-separating-hyperplanes" id="toc-optimal-separating-hyperplanes" class="nav-link" data-scroll-target="#optimal-separating-hyperplanes"><span class="header-section-number">4.5.2</span> 4.5.2 Optimal Separating Hyperplanes</a></li>
  </ul></li>
  <li><a href="#bibliographic-notes" id="toc-bibliographic-notes" class="nav-link" data-scroll-target="#bibliographic-notes"><span class="header-section-number">4.6</span> Bibliographic Notes</a></li>
  <li><a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises"><span class="header-section-number">4.7</span> Exercises</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Linear Methods for Classification</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="introduction" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="introduction"><span class="header-section-number">4.1</span> 4.1 Introduction</h2>
<p>In this chapter we revisit the classification problem and focus on linear methods for classification. Since our predictor G(x) takes values in a discrete set <span class="math inline">\(\mathcal{G}\)</span> , we can always divide the input space into a collection of regions labeled according to the classification. We saw in Chapter 2 that the boundaries of these regions can be rough or smooth, depending on the prediction function. For an important class of procedures, these decision boundaries are linear; this is what we will mean by linear methods for classification.</p>
<p>There are several different ways in which linear decision boundaries can be found. In Chapter 2 we fit linear regression models to the class indicator variables, and classify to the largest fit. Suppose there are K classes, for convenience labeled <span class="math inline">\(1, 2, \ldots, K\)</span> , and the fitted linear model for the kth indicator response variable is <span class="math inline">\(\hat{f}_k(x) = \hat{\beta}_{k0} + \hat{\beta}_k^T x\)</span> . The decision boundary between class k and <span class="math inline">\(\ell\)</span> is that set of points for which <span class="math inline">\(\hat{f}_k(x) = \hat{f}_\ell(x)\)</span> , that is, the set <span class="math inline">\(\{x: (\hat{\beta}_{k0} - \hat{\beta}_{\ell0}) + (\hat{\beta}_k - \hat{\beta}_{\ell})^T x = 0\}\)</span> , an affine set or hyperplane. Since the same is true for any pair of classes, the input space is divided into regions of constant classification, with piecewise hyperplanar decision boundaries. This regression approach is a member of a class of methods that model discriminant functions <span class="math inline">\(\delta_k(x)\)</span> for each class, and then classify x to the class with the largest value for its discriminant function. Methods</p>
<p><sup>&amp;</sup>lt;sup&gt;1Strictly speaking, a hyperplane passes through the origin, while an affine set need not. We sometimes ignore the distinction and refer in general to hyperplanes.</p>
<p>that model the posterior probabilities <span class="math inline">\(\Pr(G = k|X = x)\)</span> are also in this class. Clearly, if either the <span class="math inline">\(\delta_k(x)\)</span> or <span class="math inline">\(\Pr(G = k|X = x)\)</span> are linear in x, then the decision boundaries will be linear.</p>
<p>Actually, all we require is that some monotone transformation of <span class="math inline">\(\delta_k\)</span> or <span class="math inline">\(\Pr(G = k | X = x)\)</span> be linear for the decision boundaries to be linear. For example, if there are two classes, a popular model for the posterior probabilities is</p>
<p><span class="math display">\[\Pr(G = 1|X = x) = \frac{\exp(\beta_0 + \beta^T x)}{1 + \exp(\beta_0 + \beta^T x)},\]</span></p>
<p><span class="math display">\[\Pr(G = 2|X = x) = \frac{1}{1 + \exp(\beta_0 + \beta^T x)}.\]</span> (4.1)</p>
<p>Here the monotone transformation is the logit transformation: log[p/(1-p)], and in fact we see that</p>
<p><span class="math display">\[\log \frac{\Pr(G = 1|X = x)}{\Pr(G = 2|X = x)} = \beta_0 + \beta^T x.\]</span> (4.2)</p>
<p>The decision boundary is the set of points for which the log-odds are zero, and this is a hyperplane defined by <span class="math inline">\(\{x|\beta_0 + \beta^T x = 0\}\)</span> . We discuss two very popular but different methods that result in linear log-odds or logits: linear discriminant analysis and linear logistic regression. Although they differ in their derivation, the essential difference between them is in the way the linear function is fit to the training data.</p>
<p>A more direct approach is to explicitly model the boundaries between the classes as linear. For a two-class problem in a p-dimensional input space, this amounts to modeling the decision boundary as a hyperplane—in other words, a normal vector and a cut-point. We will look at two methods that explicitly look for “separating hyperplanes.” The first is the well-known perceptron model of Rosenblatt (1958), with an algorithm that finds a separating hyperplane in the training data, if one exists. The second method, due to Vapnik (1996), finds an optimally separating hyperplane if one exists, else finds a hyperplane that minimizes some measure of overlap in the training data. We treat the separable case here, and defer treatment of the nonseparable case to Chapter 12.</p>
<p>While this entire chapter is devoted to linear decision boundaries, there is considerable scope for generalization. For example, we can expand our variable set <span class="math inline">\(X_1, \ldots, X_p\)</span> by including their squares and cross-products <span class="math inline">\(X_1^2, X_2^2, \ldots, X_1 X_2, \ldots\)</span> , thereby adding p(p+1)/2 additional variables. Linear functions in the augmented space map down to quadratic functions in the original space—hence linear decision boundaries to quadratic decision boundaries. Figure 4.1 illustrates the idea. The data are the same: the left plot uses linear decision boundaries in the two-dimensional space shown, while the right plot uses linear decision boundaries in the augmented five-dimensional space described above. This approach can be used with any basis transfor-</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figures/_page_121_Figure_2.jpeg" class="img-fluid figure-img"></p>
<figcaption><strong>FIGURE 4.1.</strong> The left plot shows some data from three classes, with linear decision boundaries found by linear discriminant analysis. The right plot shows quadratic decision boundaries.</figcaption>
</figure>
</div>
<p><strong>FIGURE 4.1.</strong> The left plot shows some data from three classes, with linear decision boundaries found by linear discriminant analysis. The right plot shows quadratic decision boundaries. These were obtained by finding linear boundaries in the five-dimensional space <span class="math inline">\(X_1, X_2, X_1X_2, X_1^2, X_2^2\)</span> . Linear inequalities in this space are quadratic inequalities in the original space.</p>
<p>mation h(X) where <span class="math inline">\(h: \mathbb{R}^p \to \mathbb{R}^q\)</span> with q &gt; p, and will be explored in later chapters.</p>
</section>
<section id="linear-regression-of-an-indicator-matrix" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="linear-regression-of-an-indicator-matrix"><span class="header-section-number">4.2</span> 4.2 Linear Regression of an Indicator Matrix</h2>
<p>Here each of the response categories are coded via an indicator variable. Thus if <span class="math inline">\(\mathcal{G}\)</span> has K classes, there will be K such indicators <span class="math inline">\(Y_k\)</span> , <span class="math inline">\(k = 1, \ldots, K\)</span> , with <span class="math inline">\(Y_k = 1\)</span> if G = k else 0. These are collected together in a vector <span class="math inline">\(Y = (Y_1, \ldots, Y_K)\)</span> , and the N training instances of these form an <span class="math inline">\(N \times K\)</span> indicator response matrix <span class="math inline">\(\mathbf{Y}\)</span> . <span class="math inline">\(\mathbf{Y}\)</span> is a matrix of 0’s and 1’s, with each row having a single 1. We fit a linear regression model to each of the columns of <span class="math inline">\(\mathbf{Y}\)</span> simultaneously, and the fit is given by</p>
<p><span class="math display">\[\hat{\mathbf{Y}} = \mathbf{X}(\mathbf{X}^T \mathbf{X})^{-1} \mathbf{X}^T \mathbf{Y}. \tag{4.3}\]</span></p>
<p>Chapter 3 has more details on linear regression. Note that we have a coefficient vector for each response column <span class="math inline">\(\mathbf{y}_k\)</span> , and hence a <span class="math inline">\((p+1) \times K\)</span> coefficient matrix <span class="math inline">\(\hat{\mathbf{B}} = (\mathbf{X}^T \mathbf{X})^{-1} \mathbf{X}^T \mathbf{Y}\)</span> . Here <span class="math inline">\(\mathbf{X}\)</span> is the model matrix with p+1 columns corresponding to the p inputs, and a leading column of 1’s for the intercept.</p>
<p>A new observation with input x is classified as follows:</p>
<ul>
<li>compute the fitted output <span class="math inline">\(\hat{f}(x)^T = (1, x^T)\hat{\mathbf{B}}\)</span> , a K vector;</li>
<li>identify the largest component and classify accordingly:</li>
</ul>
<p><span class="math display">\[\hat{G}(x) = \operatorname{argmax}_{k \in G} \hat{f}_k(x). \tag{4.4}\]</span></p>
<p>What is the rationale for this approach? One rather formal justification is to view the regression as an estimate of conditional expectation. For the random variable <span class="math inline">\(Y_k\)</span> , <span class="math inline">\(E(Y_k|X=x) = \Pr(G=k|X=x)\)</span> , so conditional expectation of each of the <span class="math inline">\(Y_k\)</span> seems a sensible goal. The real issue is: how good an approximation to conditional expectation is the rather rigid linear regression model? Alternatively, are the <span class="math inline">\(\hat{f}_k(x)\)</span> reasonable estimates of the posterior probabilities <span class="math inline">\(\Pr(G=k|X=x)\)</span> , and more importantly, does this matter?</p>
<p>It is quite straightforward to verify that <span class="math inline">\(\sum_{k \in \mathcal{G}} \hat{f}_k(x) = 1\)</span> for any x, as long as there is an intercept in the model (column of 1’s in <span class="math inline">\(\mathbf{X}\)</span> ). However, the <span class="math inline">\(\hat{f}_k(x)\)</span> can be negative or greater than 1, and typically some are. This is a consequence of the rigid nature of linear regression, especially if we make predictions outside the hull of the training data. These violations in themselves do not guarantee that this approach will not work, and in fact on many problems it gives similar results to more standard linear methods for classification. If we allow linear regression onto basis expansions h(X) of the inputs, this approach can lead to consistent estimates of the probabilities. As the size of the training set N grows bigger, we adaptively include more basis elements so that linear regression onto these basis functions approaches conditional expectation. We discuss such approaches in Chapter 5.</p>
<p>A more simplistic viewpoint is to construct <span class="math inline">\(targets\ t_k\)</span> for each class, where <span class="math inline">\(t_k\)</span> is the kth column of the <span class="math inline">\(K\times K\)</span> identity matrix. Our prediction problem is to try and reproduce the appropriate target for an observation. With the same coding as before, the response vector <span class="math inline">\(y_i\)</span> (ith row of <span class="math inline">\(\mathbf{Y}\)</span> ) for observation i has the value <span class="math inline">\(y_i = t_k\)</span> if <span class="math inline">\(g_i = k\)</span> . We might then fit the linear model by least squares:</p>
<p><span class="math display">\[\min_{\mathbf{B}} \sum_{i=1}^{N} ||y_i - [(1, x_i^T)\mathbf{B}]^T||^2.\]</span> (4.5)</p>
<p>The criterion is a sum-of-squared Euclidean distances of the fitted vectors from their targets. A new observation is classified by computing its fitted vector <span class="math inline">\(\hat{f}(x)\)</span> and classifying to the closest target:</p>
<p><span class="math display">\[\hat{G}(x) = \underset{k}{\operatorname{argmin}} ||\hat{f}(x) - t_k||^2.\]</span> (4.6)</p>
<p>This is exactly the same as the previous approach:</p>
<p>• The sum-of-squared-norm criterion is exactly the criterion for multiple response linear regression, just viewed slightly differently. Since a squared norm is itself a sum of squares, the components decouple and can be rearranged as a separate linear model for each element. Note that this is only possible because there is nothing in the model that binds the different responses together.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figures/_page_123_Figure_2.jpeg" class="img-fluid figure-img"></p>
<figcaption><strong>FIGURE 4.2.</strong> The data come from three classes in <span class="math inline">\(\mathbb{R}^2\)</span> and are easily separated by linear decision boundaries. The right plot shows the boundaries found by linear discriminant analysis.</figcaption>
</figure>
</div>
<p><strong>FIGURE 4.2.</strong> The data come from three classes in <span class="math inline">\(\mathbb{R}^2\)</span> and are easily separated by linear decision boundaries. The right plot shows the boundaries found by linear discriminant analysis. The left plot shows the boundaries found by linear regression of the indicator response variables. The middle class is completely masked (never dominates).</p>
<p>• The closest target classification rule (4.6) is easily seen to be exactly the same as the maximum fitted component criterion (4.4).</p>
<p>There is a serious problem with the regression approach when the number of classes <span class="math inline">\(K \geq 3\)</span> , especially prevalent when K is large. Because of the rigid nature of the regression model, classes can be masked by others. Figure 4.2 illustrates an extreme situation when K=3. The three classes are perfectly separated by linear decision boundaries, yet linear regression misses the middle class completely.</p>
<p>In Figure 4.3 we have projected the data onto the line joining the three centroids (there is no information in the orthogonal direction in this case), and we have included and coded the three response variables <span class="math inline">\(Y_1\)</span> , <span class="math inline">\(Y_2\)</span> and <span class="math inline">\(Y_3\)</span> . The three regression lines (left panel) are included, and we see that the line corresponding to the middle class is horizontal and its fitted values are never dominant! Thus, observations from class 2 are classified either as class 1 or class 3. The right panel uses quadratic regression rather than linear regression. For this simple example a quadratic rather than linear fit (for the middle class at least) would solve the problem. However, it can be seen that if there were four rather than three classes lined up like this, a quadratic would not come down fast enough, and a cubic would be needed as well. A loose but general rule is that if <span class="math inline">\(K \geq 3\)</span> classes are lined up, polynomial terms up to degree K-1 might be needed to resolve them. Note also that these are polynomials along the derived direction passing through the centroids, which can have arbitrary orientation. So in</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figures/_page_124_Figure_2.jpeg" class="img-fluid figure-img"></p>
<figcaption><strong>FIGURE 4.3.</strong> The effects of masking on linear regression in <span class="math inline">\(\mathbb{R}\)</span> for a three-class problem. The rug plot indicates positions and class membership, and the curves are the fitted regressions.</figcaption>
</figure>
</div>
<p><strong>FIGURE 4.3.</strong> The effects of masking on linear regression in <span class="math inline">\(\mathbb{R}\)</span> for a three-class problem. The rug plot at the base indicates the positions and class membership of each observation. The three curves in each panel are the fitted regressions to the three-class indicator variables; for example, for the blue class, <span class="math inline">\(y_{blue}\)</span> is 1 for the blue observations, and 0 for the green and orange. The fits are linear and quadratic polynomials. Above each plot is the training error rate. The Bayes error rate is 0.025 for this problem, as is the LDA error rate.</p>
<p>p-dimensional input space, one would need general polynomial terms and cross-products of total degree K-1, <span class="math inline">\(O(p^{K-1})\)</span> terms in all, to resolve such worst-case scenarios.</p>
<p>The example is extreme, but for large K and small p such maskings naturally occur. As a more realistic illustration, Figure 4.4 is a projection of the training data for a vowel recognition problem onto an informative two-dimensional subspace. There are K=11 classes in p=10 dimensions. This is a difficult classification problem, and the best methods achieve around 40% errors on the test data. The main point here is summarized in Table 4.1; linear regression has an error rate of 67%, while a close relative, linear discriminant analysis, has an error rate of 56%. It seems that masking has hurt in this case. While all the other methods in this chapter are based on linear functions of x as well, they use them in such a way that avoids this masking problem.</p>
</section>
<section id="linear-discriminant-analysis" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="linear-discriminant-analysis"><span class="header-section-number">4.3</span> 4.3 Linear Discriminant Analysis</h2>
<p>Decision theory for classification (Section 2.4) tells us that we need to know the class posteriors <span class="math inline">\(\Pr(G|X)\)</span> for optimal classification. Suppose <span class="math inline">\(f_k(x)\)</span> is the class-conditional density of X in class G=k, and let <span class="math inline">\(\pi_k\)</span> be the prior probability of class k, with <span class="math inline">\(\sum_{k=1}^K \pi_k = 1\)</span> . A simple application of Bayes</p>
<p>Linear Discriminant Analysis</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figures/_page_125_Figure_3.jpeg" class="img-fluid figure-img"></p>
<figcaption><strong>FIGURE 4.4.</strong> A two-dimensional plot of the vowel training data. There are eleven classes with <span class="math inline">\(X \in \mathbb{R}^{10}\)</span> , and this is the best view in terms of a LDA model (Section 4.3.3). The heavy circles are the projected mean vectors for each class. The class overlap is considerable.</figcaption>
</figure>
</div>
<p><strong>FIGURE 4.4.</strong> A two-dimensional plot of the vowel training data. There are eleven classes with <span class="math inline">\(X \in \mathbb{R}^{10}\)</span> , and this is the best view in terms of a LDA model (Section 4.3.3). The heavy circles are the projected mean vectors for each class. The class overlap is considerable.</p>
<p><strong>TABLE 4.1.</strong> Training and test error rates using a variety of linear techniques on the vowel data. There are eleven classes in ten dimensions, of which three account for 90% of the variance (via a principal components analysis). We see that linear regression is hurt by masking, increasing the test and training error by over 10%.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Technique</th>
<th>Error Rates</th>
<th></th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td></td>
<td>Training</td>
<td>Test</td>
<td></td>
</tr>
<tr class="even">
<td>Linear regression</td>
<td>0.48</td>
<td>0.67</td>
<td></td>
</tr>
<tr class="odd">
<td>Linear discriminant analysis</td>
<td>0.32</td>
<td>0.56</td>
<td></td>
</tr>
<tr class="even">
<td>Quadratic discriminant analysis</td>
<td>0.01</td>
<td>0.53</td>
<td></td>
</tr>
<tr class="odd">
<td>Logistic regression</td>
<td>0.22</td>
<td>0.51</td>
<td></td>
</tr>
</tbody>
</table>
<p>theorem gives us</p>
<p><span class="math display">\[\Pr(G = k | X = x) = \frac{f_k(x)\pi_k}{\sum_{\ell=1}^K f_\ell(x)\pi_\ell}.\]</span> (4.7)</p>
<p>We see that in terms of ability to classify, having the <span class="math inline">\(f_k(x)\)</span> is almost equivalent to having the quantity Pr(G = k|X = x).</p>
<p>Many techniques are based on models for the class densities:</p>
<ul>
<li>linear and quadratic discriminant analysis use Gaussian densities;</li>
<li>more flexible mixtures of Gaussians allow for nonlinear decision boundaries (Section 6.8);</li>
<li>general nonparametric density estimates for each class density allow the most flexibility (Section 6.6.2);</li>
<li>Naive Bayes models are a variant of the previous case, and assume that each of the class densities are products of marginal densities; that is, they assume that the inputs are conditionally independent in each class (Section 6.6.3).</li>
</ul>
<p>Suppose that we model each class density as multivariate Gaussian</p>
<p><span class="math display">\[f_k(x) = \frac{1}{(2\pi)^{p/2} |\mathbf{\Sigma}_k|^{1/2}} e^{-\frac{1}{2}(x-\mu_k)^T \mathbf{\Sigma}_k^{-1}(x-\mu_k)}.\]</span> (4.8)</p>
<p>Linear discriminant analysis (LDA) arises in the special case when we assume that the classes have a common covariance matrix <span class="math inline">\(\Sigma_k = \Sigma \ \forall k\)</span> . In comparing two classes k and <span class="math inline">\(\ell\)</span> , it is sufficient to look at the log-ratio, and we see that</p>
<p><span class="math display">\[\log \frac{\Pr(G = k | X = x)}{\Pr(G = \ell | X = x)} = \log \frac{f_k(x)}{f_{\ell}(x)} + \log \frac{\pi_k}{\pi_{\ell}}\]</span></p>
<p><span class="math display">\[= \log \frac{\pi_k}{\pi_{\ell}} - \frac{1}{2} (\mu_k + \mu_{\ell})^T \mathbf{\Sigma}^{-1} (\mu_k - \mu_{\ell})\]</span></p>
<p><span class="math display">\[+ x^T \mathbf{\Sigma}^{-1} (\mu_k - \mu_{\ell}).\]</span> (4.9)</p>
<p>an equation linear in x. The equal covariance matrices cause the normalization factors to cancel, as well as the quadratic part in the exponents. This linear log-odds function implies that the decision boundary between classes k and <span class="math inline">\(\ell\)</span> —the set where <span class="math inline">\(\Pr(G = k|X = x) = \Pr(G = \ell|X = x)\)</span> —is linear in x; in p dimensions a hyperplane. This is of course true for any pair of classes, so all the decision boundaries are linear. If we divide <span class="math inline">\(\mathbb{R}^p\)</span> into regions that are classified as class 1, class 2, etc., these regions will be separated by hyperplanes. Figure 4.5 (left panel) shows an idealized example with three classes and p = 2. Here the data do arise from three Gaussian distributions with a common covariance matrix. We have included in</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figures/_page_127_Figure_2.jpeg" class="img-fluid figure-img"></p>
<figcaption><strong>FIGURE 4.5 (Left).</strong> Three Gaussian distributions, with the same covariance and different means. Included are the contours of constant density enclosing 95% of the probability in each case.</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figures/_page_127_Figure_3.jpeg" class="img-fluid figure-img"></p>
<figcaption><strong>FIGURE 4.5 (Right).</strong> A sample of 30 drawn from each Gaussian distribution, and the fitted LDA decision boundaries.</figcaption>
</figure>
</div>
<p><strong>FIGURE 4.5.</strong> The left panel shows three Gaussian distributions, with the same covariance and different means. Included are the contours of constant density enclosing 95% of the probability in each case. The Bayes decision boundaries between each pair of classes are shown (broken straight lines), and the Bayes decision boundaries separating all three classes are the thicker solid lines (a subset of the former). On the right we see a sample of 30 drawn from each Gaussian distribution, and the fitted LDA decision boundaries.</p>
<p>the figure the contours corresponding to 95% highest probability density, as well as the class centroids. Notice that the decision boundaries are not the perpendicular bisectors of the line segments joining the centroids. This would be the case if the covariance <span class="math inline">\(\Sigma\)</span> were spherical <span class="math inline">\(\sigma^2 \mathbf{I}\)</span> , and the class priors were equal. From (4.9) we see that the <em>linear discriminant functions</em></p>
<p><span class="math display">\[\delta_k(x) = x^T \mathbf{\Sigma}^{-1} \mu_k - \frac{1}{2} \mu_k^T \mathbf{\Sigma}^{-1} \mu_k + \log \pi_k\]</span> (4.10)</p>
<p>are an equivalent description of the decision rule, with <span class="math inline">\(G(x) = \operatorname{argmax}_k \delta_k(x)\)</span> . In practice we do not know the parameters of the Gaussian distributions, and will need to estimate them using our training data:</p>
<ul>
<li><span class="math inline">\(\hat{\pi}_k = N_k/N\)</span> , where <span class="math inline">\(N_k\)</span> is the number of class-k observations;</li>
<li><span class="math inline">\(\hat{\mu}_k = \sum_{g_i=k} x_i/N_k;\)</span></li>
<li><span class="math inline">\(\hat{\Sigma} = \sum_{k=1}^{K} \sum_{g_i=k} (x_i \hat{\mu}_k) (x_i \hat{\mu}_k)^T / (N K).\)</span></li>
</ul>
<p>Figure 4.5 (right panel) shows the estimated decision boundaries based on a sample of size 30 each from three Gaussian distributions. Figure 4.1 on page 103 is another example, but here the classes are not Gaussian.</p>
<p>With two classes there is a simple correspondence between linear discriminant analysis and classification by linear regression, as in (4.5). The LDA rule classifies to class 2 if</p>
<p><span class="math display">\[x^{T} \hat{\boldsymbol{\Sigma}}^{-1} (\hat{\mu}_{2} - \hat{\mu}_{1}) &gt; \frac{1}{2} (\hat{\mu}_{2} + \hat{\mu}_{1})^{T} \hat{\boldsymbol{\Sigma}}^{-1} (\hat{\mu}_{2} - \hat{\mu}_{1}) - \log(N_{2}/N_{1}), \quad (4.11)\]</span></p>
<p>and class 1 otherwise. Suppose we code the targets in the two classes as +1 and −1, respectively. It is easy to show that the coefficient vector from least squares is proportional to the LDA direction given in (4.11) (Exercise 4.2). [In fact, this correspondence occurs for any (distinct) coding of the targets; see Exercise 4.2]. However unless N<sup>1</sup> = N<sup>2</sup> the intercepts are different and hence the resulting decision rules are different.</p>
<p>Since this derivation of the LDA direction via least squares does not use a Gaussian assumption for the features, its applicability extends beyond the realm of Gaussian data. However the derivation of the particular intercept or cut-point given in (4.11) does require Gaussian data. Thus it makes sense to instead choose the cut-point that empirically minimizes training error for a given dataset. This is something we have found to work well in practice, but have not seen it mentioned in the literature.</p>
<p>With more than two classes, LDA is not the same as linear regression of the class indicator matrix, and it avoids the masking problems associated with that approach (Hastie et al., 1994). A correspondence between regression and LDA can be established through the notion of optimal scoring, discussed in Section 12.5.</p>
<p>Getting back to the general discriminant problem (4.8), if the Σ<sup>k</sup> are not assumed to be equal, then the convenient cancellations in (4.9) do not occur; in particular the pieces quadratic in x remain. We then get quadratic discriminant functions (QDA),</p>
<p><span class="math display">\[\delta_k(x) = -\frac{1}{2}\log|\mathbf{\Sigma}_k| - \frac{1}{2}(x - \mu_k)^T \mathbf{\Sigma}_k^{-1}(x - \mu_k) + \log \pi_k.\]</span> (4.12)</p>
<p>The decision boundary between each pair of classes k and ℓ is described by a quadratic equation {x : δk(x) = δℓ(x)}.</p>
<p>Figure 4.6 shows an example (from Figure 4.1 on page 103) where the three classes are Gaussian mixtures (Section 6.8) and the decision boundaries are approximated by quadratic equations in x. Here we illustrate two popular ways of fitting these quadratic boundaries. The right plot uses QDA as described here, while the left plot uses LDA in the enlarged five-dimensional quadratic polynomial space. The differences are generally small; QDA is the preferred approach, with the LDA method a convenient substitute <sup>2</sup> .</p>
<p>The estimates for QDA are similar to those for LDA, except that separate covariance matrices must be estimated for each class. When p is large this can mean a dramatic increase in parameters. Since the decision boundaries are functions of the parameters of the densities, counting the number of parameters must be done with care. For LDA, it seems there are (K − 1) × (p + 1) parameters, since we only need the differences δk(x) − δK(x)</p>
<p><sup>2</sup>For this figure and many similar figures in the book we compute the decision boundaries by an exhaustive contouring method. We compute the decision rule on a fine lattice of points, and then use contouring algorithms to compute the boundaries.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figures/_page_129_Figure_2.jpeg" class="img-fluid figure-img"></p>
<figcaption><strong>FIGURE 4.6.</strong> Two methods for fitting quadratic boundaries. The left plot shows the quadratic decision boundaries for the data in Figure 4.1 (obtained using LDA in the five-dimensional space). The right plot shows the quadratic decision boundaries found by QDA.</figcaption>
</figure>
</div>
<p><strong>FIGURE 4.6.</strong> Two methods for fitting quadratic boundaries. The left plot shows the quadratic decision boundaries for the data in Figure 4.1 (obtained using LDA in the five-dimensional space <span class="math inline">\(X_1, X_2, X_1X_2, X_1^2, X_2^2\)</span> ). The right plot shows the quadratic decision boundaries found by QDA. The differences are small, as is usually the case.</p>
<p>between the discriminant functions where K is some pre-chosen class (here we have chosen the last), and each difference requires p+1 parameters<sup>3</sup>. Likewise for QDA there will be <span class="math inline">\((K-1) \times \{p(p+3)/2+1\}\)</span> parameters. Both LDA and QDA perform well on an amazingly large and diverse set of classification tasks. For example, in the STATLOG project (Michie et al., 1994) LDA was among the top three classifiers for 7 of the 22 datasets, QDA among the top three for four datasets, and one of the pair were in the top three for 10 datasets. Both techniques are widely used, and entire books are devoted to LDA. It seems that whatever exotic tools are the rage of the day, we should always have available these two simple tools. The question arises why LDA and QDA have such a good track record. The reason is not likely to be that the data are approximately Gaussian, and in addition for LDA that the covariances are approximately equal. More likely a reason is that the data can only support simple decision boundaries such as linear or quadratic, and the estimates provided via the Gaussian models are stable. This is a bias variance tradeoff—we can put up with the bias of a linear decision boundary because it can be estimated with much lower variance than more exotic alternatives. This argument is less believable for QDA, since it can have many parameters itself, although perhaps fewer than the non-parametric alternatives.</p>
<p><sup>&amp;</sup>lt;sup&gt;3 Although we fit the covariance matrix <span class="math inline">\(\hat{\Sigma}\)</span> to compute the LDA discriminant functions, a much reduced function of it is all that is required to estimate the O(p) parameters needed to compute the decision boundaries.</p>
<section id="regularized-discriminant-analysis-on-the-vowel-data" class="level3" data-number="4.3.1">
<h3 data-number="4.3.1" class="anchored" data-anchor-id="regularized-discriminant-analysis-on-the-vowel-data"><span class="header-section-number">4.3.1</span> Regularized Discriminant Analysis on the Vowel Data</h3>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figures/_page_130_Figure_3.jpeg" class="img-fluid figure-img"></p>
<figcaption><strong>FIGURE 4.7.</strong> Test and training errors for the vowel data, using regularized discriminant analysis with a series of values of α ∈ [0, 1]. The optimum for the test data occurs around α = 0.9, close to quadratic discriminant analysis.</figcaption>
</figure>
</div>
<p><strong>FIGURE 4.7.</strong> Test and training errors for the vowel data, using regularized discriminant analysis with a series of values of α ∈ [0, 1]. The optimum for the test data occurs around α = 0.9, close to quadratic discriminant analysis.</p>
</section>
<section id="regularized-discriminant-analysis" class="level3" data-number="4.3.2">
<h3 data-number="4.3.2" class="anchored" data-anchor-id="regularized-discriminant-analysis"><span class="header-section-number">4.3.2</span> 4.3.1 Regularized Discriminant Analysis</h3>
<p>Friedman (1989) proposed a compromise between LDA and QDA, which allows one to shrink the separate covariances of QDA toward a common covariance as in LDA. These methods are very similar in flavor to ridge regression. The regularized covariance matrices have the form</p>
<p><span class="math display">\[\hat{\Sigma}_k(\alpha) = \alpha \hat{\Sigma}_k + (1 - \alpha)\hat{\Sigma}, \tag{4.13}\]</span></p>
<p>where <sup>Σ</sup><sup>ˆ</sup> is the pooled covariance matrix as used in LDA. Here <sup>α</sup> <sup>∈</sup> [0, 1] allows a continuum of models between LDA and QDA, and needs to be specified. In practice α can be chosen based on the performance of the model on validation data, or by cross-validation.</p>
<p>Figure 4.7 shows the results of RDA applied to the vowel data. Both the training and test error improve with increasing α, although the test error increases sharply after α = 0.9. The large discrepancy between the training and test error is partly due to the fact that there are many repeat measurements on a small number of individuals, different in the training and test set.</p>
<p>Similar modifications allow Σˆ itself to be shrunk toward the scalar covariance,</p>
<p><span class="math display">\[\hat{\mathbf{\Sigma}}(\gamma) = \gamma \hat{\mathbf{\Sigma}} + (1 - \gamma)\hat{\sigma}^2 \mathbf{I}\]</span> (4.14)</p>
<p>for <sup>γ</sup> <sup>∈</sup> [0, 1]. Replacing <sup>Σ</sup><sup>ˆ</sup> in (4.13) by <sup>Σ</sup><sup>ˆ</sup> (γ) leads to a more general family of covariances Σˆ (α, γ) indexed by a pair of parameters.</p>
<p>In Chapter 12, we discuss other regularized versions of LDA, which are more suitable when the data arise from digitized analog signals and images. In these situations the features are high-dimensional and correlated, and the LDA coefficients can be regularized to be smooth or sparse in the original domain of the signal. This leads to better generalization and allows for easier interpretation of the coefficients. In Chapter 18 we also deal with very high-dimensional problems, where for example the features are gene-expression measurements in microarray studies. There the methods focus on the case <span class="math inline">\(\gamma=0\)</span> in (4.14), and other severely regularized versions of LDA.</p>
</section>
<section id="computations-for-lda" class="level3" data-number="4.3.3">
<h3 data-number="4.3.3" class="anchored" data-anchor-id="computations-for-lda"><span class="header-section-number">4.3.3</span> 4.3.2 Computations for LDA</h3>
<p>As a lead-in to the next topic, we briefly digress on the computations required for LDA and especially QDA. Their computations are simplified by diagonalizing <span class="math inline">\(\hat{\Sigma}\)</span> or <span class="math inline">\(\hat{\Sigma}_k\)</span> . For the latter, suppose we compute the eigendecomposition for each <span class="math inline">\(\hat{\Sigma}_k = \mathbf{U}_k \mathbf{D}_k \mathbf{U}_k^T\)</span> , where <span class="math inline">\(\mathbf{U}_k\)</span> is <span class="math inline">\(p \times p\)</span> orthonormal, and <span class="math inline">\(\mathbf{D}_k\)</span> a diagonal matrix of positive eigenvalues <span class="math inline">\(d_{k\ell}\)</span> . Then the ingredients for <span class="math inline">\(\delta_k(x)\)</span> (4.12) are</p>
<ul>
<li><span class="math inline">\((x \hat{\mu}_k)^T \hat{\Sigma}_k^{-1} (x \hat{\mu}_k) = [\mathbf{U}_k^T (x \hat{\mu}_k)]^T \mathbf{D}_k^{-1} [\mathbf{U}_k^T (x \hat{\mu}_k)];\)</span></li>
<li><span class="math inline">\(\log |\hat{\Sigma}_k| = \sum_{\ell} \log d_{k\ell}\)</span> .</li>
</ul>
<p>In light of the computational steps outlined above, the LDA classifier can be implemented by the following pair of steps:</p>
<ul>
<li>Sphere the data with respect to the common covariance estimate <span class="math inline">\(\hat{\Sigma}\)</span> : <span class="math inline">\(X^* \leftarrow \mathbf{D}^{-\frac{1}{2}}\mathbf{U}^T X\)</span> , where <span class="math inline">\(\hat{\Sigma} = \mathbf{U}\mathbf{D}\mathbf{U}^T\)</span> . The common covariance estimate of <span class="math inline">\(X^*\)</span> will now be the identity.</li>
<li>Classify to the closest class centroid in the transformed space, modulo the effect of the class prior probabilities <span class="math inline">\(\pi_k\)</span> .</li>
</ul>
</section>
<section id="reduced-rank-linear-discriminant-analysis" class="level3" data-number="4.3.4">
<h3 data-number="4.3.4" class="anchored" data-anchor-id="reduced-rank-linear-discriminant-analysis"><span class="header-section-number">4.3.4</span> 4.3.3 Reduced-Rank Linear Discriminant Analysis</h3>
<p>So far we have discussed LDA as a restricted Gaussian classifier. Part of its popularity is due to an additional restriction that allows us to view informative low-dimensional projections of the data.</p>
<p>The K centroids in p-dimensional input space lie in an affine subspace of dimension <span class="math inline">\(\leq K-1\)</span> , and if p is much larger than K, this will be a considerable drop in dimension. Moreover, in locating the closest centroid, we can ignore distances orthogonal to this subspace, since they will contribute equally to each class. Thus we might just as well project the <span class="math inline">\(X^*\)</span> onto this centroid-spanning subspace <span class="math inline">\(H_{K-1}\)</span> , and make distance comparisons there. Thus there is a fundamental dimension reduction in LDA, namely, that we need only consider the data in a subspace of dimension at most K-1.</p>
<p>If K=3, for instance, this could allow us to view the data in a two-dimensional plot, color-coding the classes. In doing so we would not have relinquished any of the information needed for LDA classification.</p>
<p>What if K&gt;3? We might then ask for a L&lt; K-1 dimensional subspace <span class="math inline">\(H_L\subseteq H_{K-1}\)</span> optimal for LDA in some sense. Fisher defined optimal to mean that the projected centroids were spread out as much as possible in terms of variance. This amounts to finding principal component subspaces of the centroids themselves (principal components are described briefly in Section 3.5.1, and in more detail in Section 14.5.1). Figure 4.4 shows such an optimal two-dimensional subspace for the vowel data. Here there are eleven classes, each a different vowel sound, in a ten-dimensional input space. The centroids require the full space in this case, since K-1=p, but we have shown an optimal two-dimensional subspace. The dimensions are ordered, so we can compute additional dimensions in sequence. Figure 4.8 shows four additional pairs of coordinates, also known as canonical or discriminant variables. In summary then, finding the sequences of optimal subspaces for LDA involves the following steps:</p>
<ul>
<li>compute the <span class="math inline">\(K \times p\)</span> matrix of class centroids <strong>M</strong> and the common covariance matrix <strong>W</strong> (for <em>within-class</em> covariance);</li>
<li>compute <span class="math inline">\(\mathbf{M}^* = \mathbf{M}\mathbf{W}^{-\frac{1}{2}}\)</span> using the eigen-decomposition of <span class="math inline">\(\mathbf{W}\)</span> ;</li>
<li>compute <span class="math inline">\(\mathbf{B}^*\)</span> , the covariance matrix of <span class="math inline">\(\mathbf{M}^*\)</span> ( <span class="math inline">\(\mathbf{B}\)</span> for between-class covariance), and its eigen-decomposition <span class="math inline">\(\mathbf{B}^* = \mathbf{V}^* \mathbf{D}_B \mathbf{V}^{*T}\)</span> . The columns <span class="math inline">\(v_\ell^*\)</span> of <span class="math inline">\(\mathbf{V}^*\)</span> in sequence from first to last define the coordinates of the optimal subspaces.</li>
</ul>
<p>Combining all these operations the <span class="math inline">\(\ell\)</span> th discriminant variable is given by <span class="math inline">\(Z_{\ell} = v_{\ell}^T X\)</span> with <span class="math inline">\(v_{\ell} = \mathbf{W}^{-\frac{1}{2}} v_{\ell}^*\)</span> .</p>
<p>Fisher arrived at this decomposition via a different route, without referring to Gaussian distributions at all. He posed the problem:</p>
<p>Find the linear combination <span class="math inline">\(Z = a^T X\)</span> such that the betweenclass variance is maximized relative to the within-class variance.</p>
<p>Again, the between class variance is the variance of the class means of Z, and the within class variance is the pooled variance about the means. Figure 4.9 shows why this criterion makes sense. Although the direction joining the centroids separates the means as much as possible (i.e., maximizes the between-class variance), there is considerable overlap between the projected classes due to the nature of the covariances. By taking the covariance into account as well, a direction with minimum overlap can be found.</p>
<p>The between-class variance of Z is <span class="math inline">\(a^T \mathbf{B} a\)</span> and the within-class variance <span class="math inline">\(a^T \mathbf{W} a\)</span> , where <span class="math inline">\(\mathbf{W}\)</span> is defined earlier, and <span class="math inline">\(\mathbf{B}\)</span> is the covariance matrix of the class centroid matrix <span class="math inline">\(\mathbf{M}\)</span> . Note that <span class="math inline">\(\mathbf{B} + \mathbf{W} = \mathbf{T}\)</span> , where <span class="math inline">\(\mathbf{T}\)</span> is the <em>total</em> covariance matrix of X, ignoring class information.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figures/_page_133_Figure_2.jpeg" class="img-fluid figure-img"></p>
<figcaption><strong>FIGURE 4.8.</strong> Four projections onto pairs of canonical variates. Notice that as the rank of the canonical variates increases, the centroids become less spread out.</figcaption>
</figure>
</div>
<p><strong>FIGURE 4.8.</strong> Four projections onto pairs of canonical variates. Notice that as the rank of the canonical variates increases, the centroids become less spread out. In the lower right panel they appear to be superimposed, and the classes most confused.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figures/_page_134_Picture_2.jpeg" class="img-fluid figure-img"></p>
<figcaption><strong>FIGURE 4.9 (Left).</strong> Although the line joining the centroids defines the direction of greatest centroid spread, the projected data overlap because of the covariance.</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figures/_page_134_Picture_3.jpeg" class="img-fluid figure-img"></p>
<figcaption><strong>FIGURE 4.9 (Right).</strong> The discriminant direction minimizes this overlap for Gaussian data.</figcaption>
</figure>
</div>
<p><strong>FIGURE 4.9.</strong> Although the line joining the centroids defines the direction of greatest centroid spread, the projected data overlap because of the covariance (left panel). The discriminant direction minimizes this overlap for Gaussian data (right panel).</p>
<p>Fisher’s problem therefore amounts to maximizing the Rayleigh quotient,</p>
<p><span class="math display">\[\max_{a} \frac{a^T \mathbf{B} a}{a^T \mathbf{W} a},\tag{4.15}\]</span></p>
<p>or equivalently</p>
<p><span class="math display">\[\max_{a} a^{T} \mathbf{B} a \text{ subject to } a^{T} \mathbf{W} a = 1. \tag{4.16}\]</span></p>
<p>This is a generalized eigenvalue problem, with a given by the largest eigenvalue of <span class="math inline">\(\mathbf{W}^{-1}\mathbf{B}\)</span> . It is not hard to show (Exercise 4.1) that the optimal <span class="math inline">\(a_1\)</span> is identical to <span class="math inline">\(v_1\)</span> defined above. Similarly one can find the next direction <span class="math inline">\(a_2\)</span> , orthogonal in <span class="math inline">\(\mathbf{W}\)</span> to <span class="math inline">\(a_1\)</span> , such that <span class="math inline">\(a_2^T\mathbf{B}a_2/a_2^T\mathbf{W}a_2\)</span> is maximized; the solution is <span class="math inline">\(a_2 = v_2\)</span> , and so on. The <span class="math inline">\(a_\ell\)</span> are referred to as discriminant coordinates, not to be confused with discriminant functions. They are also referred to as canonical variates, since an alternative derivation of these results is through a canonical correlation analysis of the indicator response matrix <span class="math inline">\(\mathbf{Y}\)</span> on the predictor matrix <span class="math inline">\(\mathbf{X}\)</span> . This line is pursued in Section 12.5.</p>
<p>To summarize the developments so far:</p>
<ul>
<li>Gaussian classification with common covariances leads to linear decision boundaries. Classification can be achieved by sphering the data with respect to <span class="math inline">\(\mathbf{W}\)</span> , and classifying to the closest centroid (modulo <span class="math inline">\(\log \pi_k\)</span> ) in the sphered space.</li>
<li>Since only the relative distances to the centroids count, one can confine the data to the subspace spanned by the centroids in the sphered space.</li>
<li>This subspace can be further decomposed into successively optimal subspaces in term of centroid separation. This decomposition is identical to the decomposition due to Fisher.</li>
</ul>
<section id="lda-and-dimension-reduction-on-the-vowel-data" class="level4" data-number="4.3.4.1">
<h4 data-number="4.3.4.1" class="anchored" data-anchor-id="lda-and-dimension-reduction-on-the-vowel-data"><span class="header-section-number">4.3.4.1</span> LDA and Dimension Reduction on the Vowel Data</h4>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figures/_page_135_Figure_3.jpeg" class="img-fluid figure-img"></p>
<figcaption><strong>FIGURE 4.10.</strong> Training and test error rates for the vowel data, as a function of the dimension of the discriminant subspace. In this case the best error rate is for dimension 2.</figcaption>
</figure>
</div>
<p><strong>FIGURE 4.10.</strong> Training and test error rates for the vowel data, as a function of the dimension of the discriminant subspace. In this case the best error rate is for dimension 2. Figure 4.11 shows the decision boundaries in this space.</p>
<p>The reduced subspaces have been motivated as a data reduction (for viewing) tool. Can they also be used for classification, and what is the rationale? Clearly they can, as in our original derivation; we simply limit the distance-to-centroid calculations to the chosen subspace. One can show that this is a Gaussian classification rule with the additional restriction that the centroids of the Gaussians lie in a L-dimensional subspace of IR<sup>p</sup> . Fitting such a model by maximum likelihood, and then constructing the posterior probabilities using Bayes’ theorem amounts to the classification rule described above (Exercise 4.8).</p>
<p>Gaussian classification dictates the log π<sup>k</sup> correction factor in the distance calculation. The reason for this correction can be seen in Figure 4.9. The misclassification rate is based on the area of overlap between the two densities. If the π<sup>k</sup> are equal (implicit in that figure), then the optimal cut-point is midway between the projected means. If the π<sup>k</sup> are not equal, moving the cut-point toward the smaller class will improve the error rate. As mentioned earlier for two classes, one can derive the linear rule using LDA (or any other method), and then choose the cut-point to minimize misclassification error over the training data.</p>
<p>As an example of the benefit of the reduced-rank restriction, we return to the vowel data. There are 11 classes and 10 variables, and hence 10 possible dimensions for the classifier. We can compute the training and test error in each of these hierarchical subspaces; Figure 4.10 shows the results. Figure 4.11 shows the decision boundaries for the classifier based on the two-dimensional LDA solution.</p>
<p>There is a close connection between Fisher’s reduced rank discriminant analysis and regression of an indicator response matrix. It turns out that</p>
<p>Canonical Coordinate 2</p>
<p>Classification in Reduced Subspace</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figures/_page_136_Figure_4.jpeg" class="img-fluid figure-img"></p>
<figcaption><strong>FIGURE 4.11.</strong> Decision boundaries for the vowel training data, in the two-dimensional subspace spanned by the first two canonical variates.</figcaption>
</figure>
</div>
<p>Canonical Coordinate 1</p>
<p><strong>FIGURE 4.11.</strong> Decision boundaries for the vowel training data, in the two-dimensional subspace spanned by the first two canonical variates. Note that in any higher-dimensional subspace, the decision boundaries are higher-dimensional affine planes, and could not be represented as lines.</p>
<p>LDA amounts to the regression followed by an eigen-decomposition of <span class="math inline">\(\hat{\mathbf{Y}}^T\mathbf{Y}\)</span> . In the case of two classes, there is a single discriminant variable that is identical up to a scalar multiplication to either of the columns of <span class="math inline">\(\hat{\mathbf{Y}}\)</span> . These connections are developed in Chapter 12. A related fact is that if one transforms the original predictors <span class="math inline">\(\mathbf{X}\)</span> to <span class="math inline">\(\hat{\mathbf{Y}}\)</span> , then LDA using <span class="math inline">\(\hat{\mathbf{Y}}\)</span> is identical to LDA in the original space (Exercise 4.3).</p>
</section>
</section>
</section>
<section id="logistic-regression" class="level2" data-number="4.4">
<h2 data-number="4.4" class="anchored" data-anchor-id="logistic-regression"><span class="header-section-number">4.4</span> 4.4 Logistic Regression</h2>
<p>The logistic regression model arises from the desire to model the posterior probabilities of the K classes via linear functions in x, while at the same time ensuring that they sum to one and remain in [0,1]. The model has the form</p>
<p><span class="math display">\[\log \frac{\Pr(G = 1|X = x)}{\Pr(G = K|X = x)} = \beta_{10} + \beta_1^T x\]</span></p>
<p><span class="math display">\[\log \frac{\Pr(G = 2|X = x)}{\Pr(G = K|X = x)} = \beta_{20} + \beta_2^T x\]</span></p>
<p><span class="math display">\[\vdots\]</span></p>
<p><span class="math display">\[\log \frac{\Pr(G = K - 1|X = x)}{\Pr(G = K|X = x)} = \beta_{(K-1)0} + \beta_{K-1}^T x.\]</span> (4.17)</p>
<p>The model is specified in terms of K-1 log-odds or logit transformations (reflecting the constraint that the probabilities sum to one). Although the model uses the last class as the denominator in the odds-ratios, the choice of denominator is arbitrary in that the estimates are equivariant under this choice. A simple calculation shows that</p>
<p><span class="math display">\[\Pr(G = k | X = x) = \frac{\exp(\beta_{k0} + \beta_k^T x)}{1 + \sum_{\ell=1}^{K-1} \exp(\beta_{\ell0} + \beta_\ell^T x)}, \ k = 1, \dots, K - 1,\]</span></p>
<p><span class="math display">\[\Pr(G = K | X = x) = \frac{1}{1 + \sum_{\ell=1}^{K-1} \exp(\beta_{\ell0} + \beta_\ell^T x)},\]</span> (4.18)</p>
<p>and they clearly sum to one. To emphasize the dependence on the entire parameter set <span class="math inline">\(\theta = \{\beta_{10}, \beta_1^T, \dots, \beta_{(K-1)0}, \beta_{K-1}^T\}\)</span> , we denote the probabilities <span class="math inline">\(\Pr(G = k | X = x) = p_k(x; \theta)\)</span> .</p>
<p>When K=2, this model is especially simple, since there is only a single linear function. It is widely used in biostatistical applications where binary responses (two classes) occur quite frequently. For example, patients survive or die, have heart disease or not, or a condition is present or absent.</p>
<section id="fitting-logistic-regression-models" class="level3" data-number="4.4.1">
<h3 data-number="4.4.1" class="anchored" data-anchor-id="fitting-logistic-regression-models"><span class="header-section-number">4.4.1</span> 4.4.1 Fitting Logistic Regression Models</h3>
<p>Logistic regression models are usually fit by maximum likelihood, using the conditional likelihood of G given X. Since <span class="math inline">\(\Pr(G|X)\)</span> completely specifies the conditional distribution, the <em>multinomial</em> distribution is appropriate. The log-likelihood for N observations is</p>
<p><span class="math display">\[\ell(\theta) = \sum_{i=1}^{N} \log p_{g_i}(x_i; \theta), \tag{4.19}\]</span></p>
<p>where <span class="math inline">\(p_k(x_i; \theta) = \Pr(G = k | X = x_i; \theta)\)</span> .</p>
<p>We discuss in detail the two-class case, since the algorithms simplify considerably. It is convenient to code the two-class <span class="math inline">\(g_i\)</span> via a 0/1 response <span class="math inline">\(y_i\)</span> , where <span class="math inline">\(y_i = 1\)</span> when <span class="math inline">\(g_i = 1\)</span> , and <span class="math inline">\(y_i = 0\)</span> when <span class="math inline">\(g_i = 2\)</span> . Let <span class="math inline">\(p_1(x; \theta) = p(x; \theta)\)</span> , and <span class="math inline">\(p_2(x; \theta) = 1 - p(x; \theta)\)</span> . The log-likelihood can be written</p>
<p><span class="math display">\[\ell(\beta) = \sum_{i=1}^{N} \left\{ y_i \log p(x_i; \beta) + (1 - y_i) \log(1 - p(x_i; \beta)) \right\}\]</span> <span class="math display">\[= \sum_{i=1}^{N} \left\{ y_i \beta^T x_i - \log(1 + e^{\beta^T x_i}) \right\}. \tag{4.20}\]</span></p>
<p>Here <span class="math inline">\(\beta = \{\beta_{10}, \beta_1\}\)</span> , and we assume that the vector of inputs <span class="math inline">\(x_i\)</span> includes the constant term 1 to accommodate the intercept.</p>
<p>To maximize the log-likelihood, we set its derivatives to zero. These <span class="math inline">\(\mathit{score}\)</span> equations are</p>
<p><span class="math display">\[\frac{\partial \ell(\beta)}{\partial \beta} = \sum_{i=1}^{N} x_i (y_i - p(x_i; \beta)) = 0, \tag{4.21}\]</span></p>
<p>which are p+1 equations nonlinear in <span class="math inline">\(\beta\)</span> . Notice that since the first component of <span class="math inline">\(x_i\)</span> is 1, the first score equation specifies that <span class="math inline">\(\sum_{i=1}^{N} y_i = \sum_{i=1}^{N} p(x_i; \beta)\)</span> ; the expected number of class ones matches the observed number (and hence also class twos.)</p>
<p>To solve the score equations (4.21), we use the Newton-Raphson algorithm, which requires the second-derivative or Hessian matrix</p>
<p><span class="math display">\[\frac{\partial^2 \ell(\beta)}{\partial \beta \partial \beta^T} = -\sum_{i=1}^N x_i x_i^T p(x_i; \beta) (1 - p(x_i; \beta)). \tag{4.22}\]</span></p>
<p>Starting with <span class="math inline">\(\beta^{\text{old}}\)</span> , a single Newton update is</p>
<p><span class="math display">\[\beta^{\text{new}} = \beta^{\text{old}} - \left(\frac{\partial^2 \ell(\beta)}{\partial \beta \partial \beta^T}\right)^{-1} \frac{\partial \ell(\beta)}{\partial \beta},\]</span> (4.23)</p>
<p>where the derivatives are evaluated at <span class="math inline">\(\beta^{\text{old}}\)</span> .</p>
<p>It is convenient to write the score and Hessian in matrix notation. Let <span class="math inline">\(\mathbf{y}\)</span> denote the vector of <span class="math inline">\(y_i\)</span> values, <span class="math inline">\(\mathbf{X}\)</span> the <span class="math inline">\(N \times (p+1)\)</span> matrix of <span class="math inline">\(x_i\)</span> values, <span class="math inline">\(\mathbf{p}\)</span> the vector of fitted probabilities with ith element <span class="math inline">\(p(x_i; \beta^{\text{old}})\)</span> and <span class="math inline">\(\mathbf{W}\)</span> a <span class="math inline">\(N \times N\)</span> diagonal matrix of weights with ith diagonal element <span class="math inline">\(p(x_i; \beta^{\text{old}})(1 - p(x_i; \beta^{\text{old}}))\)</span> . Then we have</p>
<p><span class="math display">\[\frac{\partial \ell(\beta)}{\partial \beta} = \mathbf{X}^T (\mathbf{y} - \mathbf{p}) \tag{4.24}\]</span></p>
<p><span class="math display">\[\frac{\partial^2 \ell(\beta)}{\partial \beta \partial \beta^T} = -\mathbf{X}^T \mathbf{W} \mathbf{X}\]</span> (4.25)</p>
<p>The Newton step is thus</p>
<p><span class="math display">\[\beta^{\text{new}} = \beta^{\text{old}} + (\mathbf{X}^T \mathbf{W} \mathbf{X})^{-1} \mathbf{X}^T (\mathbf{y} - \mathbf{p})\]</span></p>
<p><span class="math display">\[= (\mathbf{X}^T \mathbf{W} \mathbf{X})^{-1} \mathbf{X}^T \mathbf{W} (\mathbf{X} \beta^{\text{old}} + \mathbf{W}^{-1} (\mathbf{y} - \mathbf{p}))\]</span></p>
<p><span class="math display">\[= (\mathbf{X}^T \mathbf{W} \mathbf{X})^{-1} \mathbf{X}^T \mathbf{W} \mathbf{z}. \tag{4.26}\]</span></p>
<p>In the second and third line we have re-expressed the Newton step as a weighted least squares step, with the response</p>
<p><span class="math display">\[\mathbf{z} = \mathbf{X}\beta^{\text{old}} + \mathbf{W}^{-1}(\mathbf{y} - \mathbf{p}), \tag{4.27}\]</span></p>
<p>sometimes known as the <em>adjusted response</em>. These equations get solved repeatedly, since at each iteration <span class="math inline">\(\mathbf{p}\)</span> changes, and hence so does <span class="math inline">\(\mathbf{W}\)</span> and <span class="math inline">\(\mathbf{z}\)</span> . This algorithm is referred to as <em>iteratively reweighted least squares</em> or IRLS, since each iteration solves the weighted least squares problem:</p>
<p><span class="math display">\[\beta^{\text{new}} \leftarrow \arg\min_{\beta} (\mathbf{z} - \mathbf{X}\beta)^T \mathbf{W} (\mathbf{z} - \mathbf{X}\beta).\]</span> (4.28)</p>
<p>It seems that <span class="math inline">\(\beta=0\)</span> is a good starting value for the iterative procedure, although convergence is never guaranteed. Typically the algorithm does converge, since the log-likelihood is concave, but overshooting can occur. In the rare cases that the log-likelihood decreases, step size halving will guarantee convergence.</p>
<p>For the multiclass case <span class="math inline">\((K \geq 3)\)</span> the Newton algorithm can also be expressed as an iteratively reweighted least squares algorithm, but with a vector of K-1 responses and a nondiagonal weight matrix per observation. The latter precludes any simplified algorithms, and in this case it is numerically more convenient to work with the expanded vector <span class="math inline">\(\theta\)</span> directly (Exercise 4.4). Alternatively coordinate-descent methods (Section 3.8.6) can be used to maximize the log-likelihood efficiently. The R package glmnet (Friedman et al., 2010) can fit very large logistic regression problems efficiently, both in N and p.&nbsp;Although designed to fit regularized models, options allow for unregularized fits.</p>
<p>Logistic regression models are used mostly as a data analysis and inference tool, where the goal is to understand the role of the input variables</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th>Coefficient</th>
<th>Std. Error</th>
<th>Z<br>Score</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>(Intercept)</td>
<td>−4.130</td>
<td>0.964</td>
<td>−4.285</td>
</tr>
<tr class="even">
<td>sbp</td>
<td>0.006</td>
<td>0.006</td>
<td>1.023</td>
</tr>
<tr class="odd">
<td>tobacco</td>
<td>0.080</td>
<td>0.026</td>
<td>3.034</td>
</tr>
<tr class="even">
<td>ldl</td>
<td>0.185</td>
<td>0.057</td>
<td>3.219</td>
</tr>
<tr class="odd">
<td>famhist</td>
<td>0.939</td>
<td>0.225</td>
<td>4.178</td>
</tr>
<tr class="even">
<td>obesity</td>
<td>-0.035</td>
<td>0.029</td>
<td>−1.187</td>
</tr>
<tr class="odd">
<td>alcohol</td>
<td>0.001</td>
<td>0.004</td>
<td>0.136</td>
</tr>
<tr class="even">
<td>age</td>
<td>0.043</td>
<td>0.010</td>
<td>4.184</td>
</tr>
</tbody>
</table>
<p>TABLE 4.2. Results from a logistic regression fit to the South African heart disease data.</p>
<p>in explaining the outcome. Typically many models are fit in a search for a parsimonious model involving a subset of the variables, possibly with some interactions terms. The following example illustrates some of the issues involved.</p>
</section>
<section id="example-south-african-heart-disease" class="level3" data-number="4.4.2">
<h3 data-number="4.4.2" class="anchored" data-anchor-id="example-south-african-heart-disease"><span class="header-section-number">4.4.2</span> 4.4.2 Example: South African Heart Disease</h3>
<p>Here we present an analysis of binary data to illustrate the traditional statistical use of the logistic regression model. The data in Figure 4.12 are a subset of the Coronary Risk-Factor Study (CORIS) baseline survey, carried out in three rural areas of the Western Cape, South Africa (Rousseauw et al., 1983). The aim of the study was to establish the intensity of ischemic heart disease risk factors in that high-incidence region. The data represent white males between 15 and 64, and the response variable is the presence or absence of myocardial infarction (MI) at the time of the survey (the overall prevalence of MI was 5.1% in this region). There are 160 cases in our data set, and a sample of 302 controls. These data are described in more detail in Hastie and Tibshirani (1987).</p>
<p>We fit a logistic-regression model by maximum likelihood, giving the results shown in Table 4.2. This summary includes Z scores for each of the coefficients in the model (coefficients divided by their standard errors); a nonsignificant Z score suggests a coefficient can be dropped from the model. Each of these correspond formally to a test of the null hypothesis that the coefficient in question is zero, while all the others are not (also known as the Wald test). A Z score greater than approximately 2 in absolute value is significant at the 5% level.</p>
<p>There are some surprises in this table of coefficients, which must be interpreted with caution. Systolic blood pressure (sbp) is not significant! Nor is obesity, and its sign is negative. This confusion is a result of the correlation between the set of predictors. On their own, both sbp and obesity are significant, and with positive sign. However, in the presence of many</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figures/_page_141_Figure_2.jpeg" class="img-fluid figure-img"></p>
<figcaption><strong>FIGURE 4.12.</strong> A scatterplot matrix of the South African heart disease data. Each plot shows a pair of risk factors, and the cases and controls are color coded (red is a case).</figcaption>
</figure>
</div>
<p><strong>FIGURE 4.12.</strong> A scatterplot matrix of the South African heart disease data. Each plot shows a pair of risk factors, and the cases and controls are color coded (red is a case). The variable family history of heart disease (famhist) is binary (yes or no).</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th>Coefficient</th>
<th>Std. Error</th>
<th>Z<br>score</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>(Intercept)</td>
<td>−4.204</td>
<td>0.498</td>
<td>−8.45</td>
</tr>
<tr class="even">
<td>tobacco</td>
<td>0.081</td>
<td>0.026</td>
<td>3.16</td>
</tr>
<tr class="odd">
<td>ldl</td>
<td>0.168</td>
<td>0.054</td>
<td>3.09</td>
</tr>
<tr class="even">
<td>famhist</td>
<td>0.924</td>
<td>0.223</td>
<td>4.14</td>
</tr>
<tr class="odd">
<td>age</td>
<td>0.044</td>
<td>0.010</td>
<td>4.52</td>
</tr>
</tbody>
</table>
<p>TABLE 4.3. Results from stepwise logistic regression fit to South African heart disease data.</p>
<p>other correlated variables, they are no longer needed (and can even get a negative sign).</p>
<p>At this stage the analyst might do some model selection; find a subset of the variables that are sufficient for explaining their joint effect on the prevalence of chd. One way to proceed by is to drop the least significant coefficient, and refit the model. This is done repeatedly until no further terms can be dropped from the model. This gave the model shown in Table 4.3.</p>
<p>A better but more time-consuming strategy is to refit each of the models with one variable removed, and then perform an analysis of deviance to decide which variable to exclude. The residual deviance of a fitted model is minus twice its log-likelihood, and the deviance between two models is the difference of their individual residual deviances (in analogy to sums-ofsquares). This strategy gave the same final model as above.</p>
<p>How does one interpret a coefficient of 0.081 (Std. Error = 0.026) for tobacco, for example? Tobacco is measured in total lifetime usage in kilograms, with a median of 1.0kg for the controls and 4.1kg for the cases. Thus an increase of 1kg in lifetime tobacco usage accounts for an increase in the odds of coronary heart disease of exp(0.081) = 1.084 or 8.4%. Incorporating the standard error we get an approximate 95% confidence interval of exp(0.081 ± 2 × 0.026) = (1.03, 1.14).</p>
<p>We return to these data in Chapter 5, where we see that some of the variables have nonlinear effects, and when modeled appropriately, are not excluded from the model.</p>
</section>
<section id="quadratic-approximations-and-inference" class="level3" data-number="4.4.3">
<h3 data-number="4.4.3" class="anchored" data-anchor-id="quadratic-approximations-and-inference"><span class="header-section-number">4.4.3</span> 4.4.3 Quadratic Approximations and Inference</h3>
<p>The maximum-likelihood parameter estimates βˆ satisfy a self-consistency relationship: they are the coefficients of a weighted least squares fit, where the responses are</p>
<p><span class="math display">\[z_i = x_i^T \hat{\beta} + \frac{(y_i - \hat{p}_i)}{\hat{p}_i (1 - \hat{p}_i)}, \tag{4.29}\]</span></p>
<p>and the weights are <span class="math inline">\(w_i = \hat{p}_i(1-\hat{p}_i)\)</span> , both depending on <span class="math inline">\(\hat{\beta}\)</span> itself. Apart from providing a convenient algorithm, this connection with least squares has more to offer:</p>
<p>• The weighted residual sum-of-squares is the familiar Pearson chisquare statistic</p>
<p><span class="math display">\[\sum_{i=1}^{N} \frac{(y_i - \hat{p}_i)^2}{\hat{p}_i(1 - \hat{p}_i)},\tag{4.30}\]</span></p>
<p>a quadratic approximation to the deviance.</p>
<ul>
<li>Asymptotic likelihood theory says that if the model is correct, then <span class="math inline">\(\hat{\beta}\)</span> is consistent (i.e., converges to the <em>true</em> <span class="math inline">\(\beta\)</span> ).</li>
<li>A central limit theorem then shows that the distribution of <span class="math inline">\(\hat{\beta}\)</span> converges to <span class="math inline">\(N(\beta, (\mathbf{X}^T \mathbf{W} \mathbf{X})^{-1})\)</span> . This and other asymptotics can be derived directly from the weighted least squares fit by mimicking normal theory inference.</li>
<li>Model building can be costly for logistic regression models, because each model fitted requires iteration. Popular shortcuts are the Rao score test which tests for inclusion of a term, and the Wald test which can be used to test for exclusion of a term. Neither of these require iterative fitting, and are based on the maximum-likelihood fit of the current model. It turns out that both of these amount to adding or dropping a term from the weighted least squares fit, using the same weights. Such computations can be done efficiently, without recomputing the entire weighted least squares fit.</li>
</ul>
<p>Software implementations can take advantage of these connections. For example, the generalized linear modeling software in R (which includes logistic regression as part of the binomial family of models) exploits them fully. GLM (generalized linear model) objects can be treated as linear model objects, and all the tools available for linear models can be applied automatically.</p>
</section>
<section id="l1-regularized-logistic-regression" class="level3" data-number="4.4.4">
<h3 data-number="4.4.4" class="anchored" data-anchor-id="l1-regularized-logistic-regression"><span class="header-section-number">4.4.4</span> 4.4.4 L<sub>1</sub> Regularized Logistic Regression</h3>
<p>The <span class="math inline">\(L_1\)</span> penalty used in the lasso (Section 3.4.2) can be used for variable selection and shrinkage with any linear regression model. For logistic regression, we would maximize a penalized version of (4.20):</p>
<p><span class="math display">\[\max_{\beta_0,\beta} \left\{ \sum_{i=1}^{N} \left[ y_i (\beta_0 + \beta^T x_i) - \log(1 + e^{\beta_0 + \beta^T x_i}) \right] - \lambda \sum_{j=1}^{p} |\beta_j| \right\}.\]</span> (4.31)</p>
<p>As with the lasso, we typically do not penalize the intercept term, and standardize the predictors for the penalty to be meaningful. Criterion (4.31) is</p>
<p>concave, and a solution can be found using nonlinear programming methods (Koh et al., 2007, for example). Alternatively, using the same quadratic approximations that were used in the Newton algorithm in Section 4.4.1, we can solve (4.31) by repeated application of a weighted lasso algorithm. Interestingly, the score equations [see (4.24)] for the variables with non-zero coefficients have the form</p>
<p><span class="math display">\[\mathbf{x}_{i}^{T}(\mathbf{y} - \mathbf{p}) = \lambda \cdot \operatorname{sign}(\beta_{j}), \tag{4.32}\]</span></p>
<p>which generalizes (3.58) in Section 3.4.4; the active variables are tied in their <em>generalized</em> correlation with the residuals.</p>
<p>Path algorithms such as LAR for lasso are more difficult, because the coefficient profiles are piecewise smooth rather than linear. Nevertheless, progress can be made using quadratic approximations.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figures/_page_144_Figure_6.jpeg" class="img-fluid figure-img"></p>
<figcaption><strong>FIGURE 4.13.</strong> <span class="math inline">\(L_1\)</span> regularized logistic regression coefficients for the South African heart disease data, plotted as a function of the <span class="math inline">\(L_1\)</span> norm.</figcaption>
</figure>
</div>
<p><strong>FIGURE 4.13.</strong> <span class="math inline">\(L_1\)</span> regularized logistic regression coefficients for the South African heart disease data, plotted as a function of the <span class="math inline">\(L_1\)</span> norm. The variables were all standardized to have unit variance. The profiles are computed exactly at each of the plotted points.</p>
<p>Figure 4.13 shows the <span class="math inline">\(L_1\)</span> regularization path for the South African heart disease data of Section 4.4.2. This was produced using the R package glmpath (Park and Hastie, 2007), which uses predictor-corrector methods of convex optimization to identify the exact values of <span class="math inline">\(\lambda\)</span> at which the active set of non-zero coefficients changes (vertical lines in the figure). Here the profiles look almost linear; in other examples the curvature will be more visible.</p>
<p>Coordinate descent methods (Section 3.8.6) are very efficient for computing the coefficient profiles on a grid of values for <span class="math inline">\(\lambda\)</span> . The R package glmnet</p>
<p>(Friedman et al., 2010) can fit coefficient paths for very large logistic regression problems efficiently (large in N or p). Their algorithms can exploit sparsity in the predictor matrix <span class="math inline">\(\mathbf{X}\)</span> , which allows for even larger problems. See Section 18.4 for more details, and a discussion of <span class="math inline">\(L_1\)</span> -regularized multinomial models.</p>
</section>
<section id="logistic-regression-or-lda" class="level3" data-number="4.4.5">
<h3 data-number="4.4.5" class="anchored" data-anchor-id="logistic-regression-or-lda"><span class="header-section-number">4.4.5</span> 4.4.5 Logistic Regression or LDA?</h3>
<p>In Section 4.3 we find that the log-posterior odds between class k and K are linear functions of x (4.9):</p>
<p><span class="math display">\[\log \frac{\Pr(G = k | X = x)}{\Pr(G = K | X = x)} = \log \frac{\pi_k}{\pi_K} - \frac{1}{2} (\mu_k + \mu_K)^T \mathbf{\Sigma}^{-1} (\mu_k - \mu_K) + x^T \mathbf{\Sigma}^{-1} (\mu_k - \mu_K)\]</span></p>
<p><span class="math display">\[= \alpha_{k0} + \alpha_k^T x. \tag{4.33}\]</span></p>
<p>This linearity is a consequence of the Gaussian assumption for the class densities, as well as the assumption of a common covariance matrix. The linear logistic model (4.17) by construction has linear logists:</p>
<p><span class="math display">\[\log \frac{\Pr(G = k | X = x)}{\Pr(G = K | X = x)} = \beta_{k0} + \beta_k^T x.\]</span> (4.34)</p>
<p>It seems that the models are the same. Although they have exactly the same form, the difference lies in the way the linear coefficients are estimated. The logistic regression model is more general, in that it makes less assumptions. We can write the <em>joint density</em> of X and G as</p>
<p><span class="math display">\[Pr(X, G = k) = Pr(X)Pr(G = k|X), \tag{4.35}\]</span></p>
<p>where Pr(X) denotes the marginal density of the inputs X. For both LDA and logistic regression, the second term on the right has the logit-linear form</p>
<p><span class="math display">\[\Pr(G = k | X = x) = \frac{e^{\beta_{k0} + \beta_k^T x}}{1 + \sum_{\ell=1}^{K-1} e^{\beta_{\ell0} + \beta_\ell^T x}},\]</span> (4.36)</p>
<p>where we have again arbitrarily chosen the last class as the reference.</p>
<p>The logistic regression model leaves the marginal density of X as an arbitrary density function <span class="math inline">\(\Pr(X)\)</span> , and fits the parameters of <span class="math inline">\(\Pr(G|X)\)</span> by maximizing the conditional likelihood—the multinomial likelihood with probabilities the <span class="math inline">\(\Pr(G=k|X)\)</span> . Although <span class="math inline">\(\Pr(X)\)</span> is totally ignored, we can think of this marginal density as being estimated in a fully nonparametric and unrestricted fashion, using the empirical distribution function which places mass 1/N at each observation.</p>
<p>With LDA we fit the parameters by maximizing the full log-likelihood, based on the joint density</p>
<p><span class="math display">\[Pr(X, G = k) = \phi(X; \mu_k, \Sigma)\pi_k, \tag{4.37}\]</span></p>
<p>where φ is the Gaussian density function. Standard normal theory leads easily to the estimates ˆµk,Σˆ , and ˆπ<sup>k</sup> given in Section 4.3. Since the linear parameters of the logistic form (4.33) are functions of the Gaussian parameters, we get their maximum-likelihood estimates by plugging in the corresponding estimates. However, unlike in the conditional case, the marginal density Pr(X) does play a role here. It is a mixture density</p>
<p><span class="math display">\[\Pr(X) = \sum_{k=1}^{K} \pi_k \phi(X; \mu_k, \Sigma), \tag{4.38}\]</span></p>
<p>which also involves the parameters.</p>
<p>What role can this additional component/restriction play? By relying on the additional model assumptions, we have more information about the parameters, and hence can estimate them more efficiently (lower variance). If in fact the true fk(x) are Gaussian, then in the worst case ignoring this marginal part of the likelihood constitutes a loss of efficiency of about 30% asymptotically in the error rate (Efron, 1975). Paraphrasing: with 30% more data, the conditional likelihood will do as well.</p>
<p>For example, observations far from the decision boundary (which are down-weighted by logistic regression) play a role in estimating the common covariance matrix. This is not all good news, because it also means that LDA is not robust to gross outliers.</p>
<p>From the mixture formulation, it is clear that even observations without class labels have information about the parameters. Often it is expensive to generate class labels, but unclassified observations come cheaply. By relying on strong model assumptions, such as here, we can use both types of information.</p>
<p>The marginal likelihood can be thought of as a regularizer, requiring in some sense that class densities be visible from this marginal view. For example, if the data in a two-class logistic regression model can be perfectly separated by a hyperplane, the maximum likelihood estimates of the parameters are undefined (i.e., infinite; see Exercise 4.5). The LDA coefficients for the same data will be well defined, since the marginal likelihood will not permit these degeneracies.</p>
<p>In practice these assumptions are never correct, and often some of the components of X are qualitative variables. It is generally felt that logistic regression is a safer, more robust bet than the LDA model, relying on fewer assumptions. It is our experience that the models give very similar results, even when LDA is used inappropriately, such as with qualitative predictors.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figures/_page_147_Figure_2.jpeg" class="img-fluid figure-img"></p>
<figcaption><strong>FIGURE 4.14.</strong> A toy example with two classes separable by a hyperplane. The orange line is the least squares solution, which misclassifies one of the training points.</figcaption>
</figure>
</div>
<p><strong>FIGURE 4.14.</strong> A toy example with two classes separable by a hyperplane. The orange line is the least squares solution, which misclassifies one of the training points. Also shown are two blue separating hyperplanes found by the perceptron learning algorithm with different random starts.</p>
</section>
</section>
<section id="separating-hyperplanes" class="level2" data-number="4.5">
<h2 data-number="4.5" class="anchored" data-anchor-id="separating-hyperplanes"><span class="header-section-number">4.5</span> 4.5 Separating Hyperplanes</h2>
<p>We have seen that linear discriminant analysis and logistic regression both estimate linear decision boundaries in similar but slightly different ways. For the rest of this chapter we describe separating hyperplane classifiers. These procedures construct linear decision boundaries that explicitly try to separate the data into different classes as well as possible. They provide the basis for support vector classifiers, discussed in Chapter 12. The mathematical level of this section is somewhat higher than that of the previous sections.</p>
<p>Figure 4.14 shows 20 data points in two classes in <span class="math inline">\(\mathbb{R}^2\)</span> . These data can be separated by a linear boundary. Included in the figure (blue lines) are two of the infinitely many possible <em>separating hyperplanes</em>. The orange line is the least squares solution to the problem, obtained by regressing the -1/1 response Y on X (with intercept); the line is given by</p>
<p><span class="math display">\[\{x: \hat{\beta}_0 + \hat{\beta}_1 x_1 + \hat{\beta}_2 x_2 = 0\}. \tag{4.39}\]</span></p>
<p>This least squares solution does not do a perfect job in separating the points, and makes one error. This is the same boundary found by LDA, in light of its equivalence with linear regression in the two-class case (Section 4.3 and Exercise 4.2).</p>
<p>Classifiers such as (4.39), that compute a linear combination of the input features and return the sign, were called <em>perceptrons</em> in the engineering liter-</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figures/_page_148_Figure_2.jpeg" class="img-fluid figure-img"></p>
<figcaption><strong>FIGURE 4.15.</strong> The linear algebra of a hyperplane (affine set).</figcaption>
</figure>
</div>
<p><strong>FIGURE 4.15.</strong> The linear algebra of a hyperplane (affine set).</p>
<p>ature in the late 1950s (Rosenblatt, 1958). Perceptrons set the foundations for the neural network models of the 1980s and 1990s.</p>
<p>Before we continue, let us digress slightly and review some vector algebra. Figure 4.15 depicts a hyperplane or <em>affine set L</em> defined by the equation <span class="math inline">\(f(x) = \beta_0 + \beta^T x = 0\)</span> ; since we are in <span class="math inline">\(\mathbb{R}^2\)</span> this is a line.</p>
<p>Here we list some properties:</p>
<ol type="1">
<li>For any two points <span class="math inline">\(x_1\)</span> and <span class="math inline">\(x_2\)</span> lying in L, <span class="math inline">\(\beta^T(x_1 x_2) = 0\)</span> , and hence <span class="math inline">\(\beta^* = \beta/||\beta||\)</span> is the vector normal to the surface of L.</li>
<li>For any point <span class="math inline">\(x_0\)</span> in L, <span class="math inline">\(\beta^T x_0 = -\beta_0\)</span> .</li>
<li>The signed distance of any point x to L is given by</li>
</ol>
<p><span class="math display">\[\beta^{*T}(x - x_0) = \frac{1}{\|\beta\|} (\beta^T x + \beta_0)\]</span></p>
<p><span class="math display">\[= \frac{1}{\|f'(x)\|} f(x). \tag{4.40}\]</span></p>
<p>Hence f(x) is proportional to the signed distance from x to the hyperplane defined by f(x) = 0.</p>
<section id="rosenblatts-perceptron-learning-algorithm" class="level3" data-number="4.5.1">
<h3 data-number="4.5.1" class="anchored" data-anchor-id="rosenblatts-perceptron-learning-algorithm"><span class="header-section-number">4.5.1</span> 4.5.1 Rosenblatt’s Perceptron Learning Algorithm</h3>
<p>The perceptron learning algorithm tries to find a separating hyperplane by minimizing the distance of misclassified points to the decision boundary. If</p>
<p>a response y<sup>i</sup> = 1 is misclassified, then x T <sup>i</sup> β + β<sup>0</sup> &lt; 0, and the opposite for a misclassified response with y<sup>i</sup> = −1. The goal is to minimize</p>
<p><span class="math display">\[D(\beta, \beta_0) = -\sum_{i \in \mathcal{M}} y_i(x_i^T \beta + \beta_0), \tag{4.41}\]</span></p>
<p>where M indexes the set of misclassified points. The quantity is nonnegative and proportional to the distance of the misclassified points to the decision boundary defined by β <sup>T</sup> x + β<sup>0</sup> = 0. The gradient (assuming M is fixed) is given by</p>
<p><span class="math display">\[\partial \frac{D(\beta, \beta_0)}{\partial \beta} = -\sum_{i \in \mathcal{M}} y_i x_i, \tag{4.42}\]</span></p>
<p><span class="math display">\[\partial \frac{D(\beta, \beta_0)}{\partial \beta_0} = -\sum_{i \in \mathcal{M}} y_i. \tag{4.43}\]</span></p>
<p>The algorithm in fact uses stochastic gradient descent to minimize this piecewise linear criterion. This means that rather than computing the sum of the gradient contributions of each observation followed by a step in the negative gradient direction, a step is taken after each observation is visited. Hence the misclassified observations are visited in some sequence, and the parameters β are updated via</p>
<p><span class="math display">\[\begin{pmatrix} \beta \\ \beta_0 \end{pmatrix} \leftarrow \begin{pmatrix} \beta \\ \beta_0 \end{pmatrix} + \rho \begin{pmatrix} y_i x_i \\ y_i \end{pmatrix}. \tag{4.44}\]</span></p>
<p>Here ρ is the learning rate, which in this case can be taken to be 1 without loss in generality. If the classes are linearly separable, it can be shown that the algorithm converges to a separating hyperplane in a finite number of steps (Exercise 4.6). Figure 4.14 shows two solutions to a toy problem, each started at a different random guess.</p>
<p>There are a number of problems with this algorithm, summarized in Ripley (1996):</p>
<ul>
<li>When the data are separable, there are many solutions, and which one is found depends on the starting values.</li>
<li>The “finite” number of steps can be very large. The smaller the gap, the longer the time to find it.</li>
<li>When the data are not separable, the algorithm will not converge, and cycles develop. The cycles can be long and therefore hard to detect.</li>
</ul>
<p>The second problem can often be eliminated by seeking a hyperplane not in the original space, but in a much enlarged space obtained by creating many basis-function transformations of the original variables. This is analogous to driving the residuals in a polynomial regression problem down to zero by making the degree sufficiently large. Perfect separation cannot always be achieved: for example, if observations from two different classes share the same input. It may not be desirable either, since the resulting model is likely to be overfit and will not generalize well. We return to this point at the end of the next section.</p>
<p>A rather elegant solution to the first problem is to add additional constraints to the separating hyperplane.</p>
</section>
<section id="optimal-separating-hyperplanes" class="level3" data-number="4.5.2">
<h3 data-number="4.5.2" class="anchored" data-anchor-id="optimal-separating-hyperplanes"><span class="header-section-number">4.5.2</span> 4.5.2 Optimal Separating Hyperplanes</h3>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figures/_page_150_Picture_5.jpeg" class="img-fluid figure-img"></p>
<figcaption><strong>Margin illustration.</strong> The optimal separating hyperplane separates the two classes and maximizes the distance to the closest point from either class.</figcaption>
</figure>
</div>
<p>The optimal separating hyperplane separates the two classes and maximizes the distance to the closest point from either class (Vapnik, 1996). Not only does this provide a unique solution to the separating hyperplane problem, but by maximizing the margin between the two classes on the training data, this leads to better classification performance on test data.</p>
<p>We need to generalize criterion (4.41). Consider the optimization problem</p>
<p><span class="math display">\[\max_{\beta,\beta_0,||\beta||=1} M\]</span> subject to <span class="math inline">\(y_i(x_i^T \beta + \beta_0) \ge M, \ i = 1, \dots, N.\)</span></p>
<p><span class="math display">\[(4.45)\]</span></p>
<p>The set of conditions ensure that all the points are at least a signed distance M from the decision boundary defined by β and β0, and we seek the largest such M and associated parameters. We can get rid of the ||β|| = 1 constraint by replacing the conditions with</p>
<p><span class="math display">\[\frac{1}{||\beta||} y_i(x_i^T \beta + \beta_0) \ge M, \tag{4.46}\]</span></p>
<p>(which redefines β0) or equivalently</p>
<p><span class="math display">\[y_i(x_i^T \beta + \beta_0) \ge M||\beta||. \tag{4.47}\]</span></p>
<p>Since for any β and β<sup>0</sup> satisfying these inequalities, any positively scaled multiple satisfies them too, we can arbitrarily set ||β|| = 1/M. Thus (4.45) is equivalent to</p>
<p><span class="math display">\[\min_{\beta,\beta_0} \frac{1}{2} ||\beta||^2\]</span> subject to <span class="math inline">\(y_i(x_i^T \beta + \beta_0) \ge 1, \ i = 1, \dots, N.\)</span></p>
<p>In light of (4.40), the constraints define an empty slab or margin around the linear decision boundary of thickness 1/||β||. Hence we choose β and β<sup>0</sup> to maximize its thickness. This is a convex optimization problem (quadratic criterion with linear inequality constraints). The Lagrange (primal) function, to be minimized w.r.t. β and β0, is</p>
<p><span class="math display">\[L_P = \frac{1}{2}||\beta||^2 - \sum_{i=1}^N \alpha_i [y_i(x_i^T \beta + \beta_0) - 1]. \tag{4.49}\]</span></p>
<p>Setting the derivatives to zero, we obtain:</p>
<p><span class="math display">\[\beta = \sum_{i=1}^{N} \alpha_i y_i x_i, \tag{4.50}\]</span></p>
<p><span class="math display">\[0 = \sum_{i=1}^{N} \alpha_i y_i, \tag{4.51}\]</span></p>
<p>and substituting these in (4.49) we obtain the so-called Wolfe dual</p>
<p><span class="math display">\[L_D = \sum_{i=1}^{N} \alpha_i - \frac{1}{2} \sum_{i=1}^{N} \sum_{k=1}^{N} \alpha_i \alpha_k y_i y_k x_i^T x_k\]</span> subject to <span class="math inline">\(\alpha_i \ge 0\)</span> and <span class="math inline">\(\sum_{i=1}^{N} \alpha_i y_i = 0\)</span> . (4.52)</p>
<p>The solution is obtained by maximizing L<sup>D</sup> in the positive orthant, a simpler convex optimization problem, for which standard software can be used. In addition the solution must satisfy the Karush–Kuhn–Tucker conditions, which include (4.50), (4.51), (4.52) and</p>
<p><span class="math display">\[\alpha_i[y_i(x_i^T\beta + \beta_0) - 1] = 0 \,\forall i. \tag{4.53}\]</span></p>
<p>From these we can see that</p>
<ul>
<li>if α<sup>i</sup> &gt; 0, then yi(x T <sup>i</sup> β + β0) = 1, or in other words, x<sup>i</sup> is on the boundary of the slab;</li>
<li>if yi(x T <sup>i</sup> β+β0) &gt; 1, x<sup>i</sup> is not on the boundary of the slab, and α<sup>i</sup> = 0.</li>
</ul>
<p>From (4.50) we see that the solution vector β is defined in terms of a linear combination of the support points xi—those points defined to be on the boundary of the slab via α<sup>i</sup> &gt; 0. Figure 4.16 shows the optimal separating hyperplane for our toy example; there are three support points. Likewise, β<sup>0</sup> is obtained by solving (4.53) for any of the support points.</p>
<p>The optimal separating hyperplane produces a function ˆf(x) = x <sup>T</sup> βˆ+βˆ 0 for classifying new observations:</p>
<p><span class="math display">\[\hat{G}(x) = \operatorname{sign}\hat{f}(x). \tag{4.54}\]</span></p>
<p>Although none of the training observations fall in the margin (by construction), this will not necessarily be the case for test observations. The</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figures/_page_152_Figure_2.jpeg" class="img-fluid figure-img"></p>
<figcaption><strong>FIGURE 4.16.</strong> The same data as in Figure 4.14. The shaded region delineates the maximum margin separating the two classes. There are three support points indicated.</figcaption>
</figure>
</div>
<p><strong>FIGURE 4.16.</strong> The same data as in Figure 4.14. The shaded region delineates the maximum margin separating the two classes. There are three support points indicated, which lie on the boundary of the margin, and the optimal separating hyperplane (blue line) bisects the slab. Included in the figure is the boundary found using logistic regression (red line), which is very close to the optimal separating hyperplane (see Section 12.3.3).</p>
<p>intuition is that a large margin on the training data will lead to good separation on the test data.</p>
<p>The description of the solution in terms of support points seems to suggest that the optimal hyperplane focuses more on the points that count, and is more robust to model misspecification. The LDA solution, on the other hand, depends on all of the data, even points far away from the decision boundary. Note, however, that the identification of these support points required the use of all the data. Of course, if the classes are really Gaussian, then LDA is optimal, and separating hyperplanes will pay a price for focusing on the (noisier) data at the boundaries of the classes.</p>
<p>Included in Figure 4.16 is the logistic regression solution to this problem, fit by maximum likelihood. Both solutions are similar in this case. When a separating hyperplane exists, logistic regression will always find it, since the log-likelihood can be driven to 0 in this case (Exercise 4.5). The logistic regression solution shares some other qualitative features with the separating hyperplane solution. The coefficient vector is defined by a weighted least squares fit of a zero-mean linearized response on the input features, and the weights are larger for points near the decision boundary than for those further away.</p>
<p>When the data are not separable, there will be no feasible solution to this problem, and an alternative formulation is needed. Again one can enlarge the space using basis transformations, but this can lead to artificial separation through over-fitting. In Chapter 12 we discuss a more attractive alternative known as the support vector machine, which allows for overlap, but minimizes a measure of the extent of this overlap.</p>
</section>
</section>
<section id="bibliographic-notes" class="level2" data-number="4.6">
<h2 data-number="4.6" class="anchored" data-anchor-id="bibliographic-notes"><span class="header-section-number">4.6</span> Bibliographic Notes</h2>
<p>Good general texts on classification include Duda et al.&nbsp;(2000), Hand (1981), McLachlan (1992) and Ripley (1996). Mardia et al.&nbsp;(1979) have a concise discussion of linear discriminant analysis. Michie et al.&nbsp;(1994) compare a large number of popular classifiers on benchmark datasets. Linear separating hyperplanes are discussed in Vapnik (1996). Our account of the perceptron learning algorithm follows Ripley (1996).</p>
</section>
<section id="exercises" class="level2" data-number="4.7">
<h2 data-number="4.7" class="anchored" data-anchor-id="exercises"><span class="header-section-number">4.7</span> Exercises</h2>
<p>Ex. 4.1 Show how to solve the generalized eigenvalue problem max a <sup>T</sup> Ba subject to a <sup>T</sup>Wa = 1 by transforming to a standard eigenvalue problem.</p>
<p>Ex. 4.2 Suppose we have features <sup>x</sup> <sup>∈</sup> IR<sup>p</sup> , a two-class response, with class sizes N1, N2, and the target coded as −N/N1, N/N2.</p>
<ol type="a">
<li>Show that the LDA rule classifies to class 2 if</li>
</ol>
<p><span class="math display">\[x^T \hat{\boldsymbol{\Sigma}}^{-1}(\hat{\mu}_2 - \hat{\mu}_1) &gt; \frac{1}{2}(\hat{\mu}_2 + \hat{\mu}_1)^T \hat{\boldsymbol{\Sigma}}^{-1}(\hat{\mu}_2 - \hat{\mu}_1) - \log(N_2/N_1),\]</span></p>
<p>and class 1 otherwise.</p>
<ol start="2" type="a">
<li>Consider minimization of the least squares criterion</li>
</ol>
<p><span class="math display">\[\sum_{i=1}^{N} (y_i - \beta_0 - x_i^T \beta)^2. \tag{4.55}\]</span></p>
<p>Show that the solution βˆ satisfies</p>
<p><span class="math display">\[\left[ (N-2)\hat{\Sigma} + N\hat{\Sigma}_B \right] \beta = N(\hat{\mu}_2 - \hat{\mu}_1)\]</span> (4.56)</p>
<p>(after simplification), where Σˆ <sup>B</sup> = N1N<sup>2</sup> <sup>N</sup><sup>2</sup> (ˆµ<sup>2</sup> − µˆ1)(ˆµ<sup>2</sup> − µˆ1) T .</p>
<ol start="3" type="a">
<li>Hence show that <sup>Σ</sup><sup>ˆ</sup> <sup>B</sup><sup>β</sup> is in the direction (ˆµ<sup>2</sup> <sup>−</sup> <sup>µ</sup>ˆ1) and thus</li>
</ol>
<p><span class="math display">\[\hat{\beta} \propto \hat{\Sigma}^{-1} (\hat{\mu}_2 - \hat{\mu}_1). \tag{4.57}\]</span></p>
<p>Therefore the least-squares regression coefficient is identical to the LDA coefficient, up to a scalar multiple.</p>
<ul>
<li><ol start="4" type="a">
<li>Show that this result holds for any (distinct) coding of the two classes.</li>
</ol></li>
<li><ol start="5" type="a">
<li>Find the solution <span class="math inline">\(\hat{\beta}_0\)</span> (up to the same scalar multiple as in (c), and hence the predicted value <span class="math inline">\(\hat{f}(x) = \hat{\beta}_0 + x^T \hat{\beta}\)</span> . Consider the following rule: classify to class 2 if <span class="math inline">\(\hat{f}(x) &gt; 0\)</span> and class 1 otherwise. Show this is not the same as the LDA rule unless the classes have equal numbers of observations.</li>
</ol></li>
</ul>
<p>(Fisher, 1936; Ripley, 1996)</p>
<p>Ex. 4.3 Suppose we transform the original predictors <span class="math inline">\(\mathbf{X}\)</span> to <span class="math inline">\(\hat{\mathbf{Y}}\)</span> via linear regression. In detail, let <span class="math inline">\(\hat{\mathbf{Y}} = \mathbf{X}(\mathbf{X}^T\mathbf{X})^{-1}\mathbf{X}^T\mathbf{Y} = \mathbf{X}\hat{\mathbf{B}}\)</span> , where <span class="math inline">\(\mathbf{Y}\)</span> is the indicator response matrix. Similarly for any input <span class="math inline">\(x \in \mathbb{R}^p\)</span> , we get a transformed vector <span class="math inline">\(\hat{y} = \hat{\mathbf{B}}^T x \in \mathbb{R}^K\)</span> . Show that LDA using <span class="math inline">\(\hat{\mathbf{Y}}\)</span> is identical to LDA in the original space.</p>
<p>Ex. 4.4 Consider the multilogit model with K classes (4.17). Let <span class="math inline">\(\beta\)</span> be the (p+1)(K-1)-vector consisting of all the coefficients. Define a suitably enlarged version of the input vector x to accommodate this vectorized coefficient matrix. Derive the Newton-Raphson algorithm for maximizing the multinomial log-likelihood, and describe how you would implement this algorithm.</p>
<p>Ex. 4.5 Consider a two-class logistic regression problem with <span class="math inline">\(x \in \mathbb{R}\)</span> . Characterize the maximum-likelihood estimates of the slope and intercept parameter if the sample <span class="math inline">\(x_i\)</span> for the two classes are separated by a point <span class="math inline">\(x_0 \in \mathbb{R}\)</span> . Generalize this result to (a) <span class="math inline">\(x \in \mathbb{R}^p\)</span> (see Figure 4.16), and (b) more than two classes.</p>
<p>Ex. 4.6 Suppose we have N points <span class="math inline">\(x_i\)</span> in <span class="math inline">\(\mathbb{R}^p\)</span> in general position, with class labels <span class="math inline">\(y_i \in \{-1, 1\}\)</span> . Prove that the perceptron learning algorithm converges to a separating hyperplane in a finite number of steps:</p>
<ul>
<li><ol type="a">
<li>Denote a hyperplane by <span class="math inline">\(f(x) = \beta_1^T x + \beta_0 = 0\)</span> , or in more compact notation <span class="math inline">\(\beta^T x^* = 0\)</span> , where <span class="math inline">\(x^* = (x, 1)\)</span> and <span class="math inline">\(\beta = (\beta_1, \beta_0)\)</span> . Let <span class="math inline">\(z_i = x_i^*/||x_i^*||\)</span> . Show that separability implies the existence of a <span class="math inline">\(\beta_{\text{sep}}\)</span> such that <span class="math inline">\(y_i \beta_{\text{sep}}^T z_i \geq 1 \ \forall i\)</span></li>
</ol></li>
<li><ol start="2" type="a">
<li>Given a current <span class="math inline">\(\beta_{\text{old}}\)</span> , the perceptron algorithm identifies a point <span class="math inline">\(z_i\)</span> that is misclassified, and produces the update <span class="math inline">\(\beta_{\text{new}} \leftarrow \beta_{\text{old}} + y_i z_i\)</span> . Show that <span class="math inline">\(||\beta_{\text{new}} \beta_{\text{sep}}||^2 \le ||\beta_{\text{old}} \beta_{\text{sep}}||^2 1\)</span> , and hence that the algorithm converges to a separating hyperplane in no more than <span class="math inline">\(||\beta_{\text{start}} \beta_{\text{sep}}||^2\)</span> steps (Ripley, 1996).</li>
</ol></li>
</ul>
<p>Ex. 4.7 Consider the criterion</p>
<p><span class="math display">\[D^*(\beta, \beta_0) = -\sum_{i=1}^{N} y_i (x_i^T \beta + \beta_0), \tag{4.58}\]</span></p>
<p>a generalization of (4.41) where we sum over all the observations. Consider minimizing <span class="math inline">\(D^*\)</span> subject to <span class="math inline">\(||\beta|| = 1\)</span> . Describe this criterion in words. Does it solve the optimal separating hyperplane problem?</p>
<p>Ex. 4.8 Consider the multivariate Gaussian model <span class="math inline">\(X|G = k \sim N(\mu_k, \Sigma)\)</span> , with the additional restriction that <span class="math inline">\(\operatorname{rank}\{\mu_k\}_1^K = L &lt; \max(K-1, p)\)</span> . Derive the constrained MLEs for the <span class="math inline">\(\mu_k\)</span> and <span class="math inline">\(\Sigma\)</span> . Show that the Bayes classification rule is equivalent to classifying in the reduced subspace computed by LDA (Hastie and Tibshirani, 1996b).</p>
<p>Ex. 4.9 Write a computer program to perform a quadratic discriminant analysis by fitting a separate Gaussian model per class. Try it out on the vowel data, and compute the misclassification error for the test data. The data can be found in the book website www-stat.stanford.edu/ElemStatLearn.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../chapters/03-linear-methods-for-regression.html" class="pagination-link" aria-label="Linear Methods for Regression">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Linear Methods for Regression</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../chapters/05-basis-expansions-and-regularization.html" class="pagination-link" aria-label="Basis Expansions and Regularization">
        <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Basis Expansions and Regularization</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>