<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.35">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>9&nbsp; Additive Models, Trees, and Related Methods – esl</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../chapters/10-boosting-and-additive-trees.html" rel="next">
<link href="../chapters/08-model-inference-and-averaging.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-46f66b053e56abd73bb6e954d61a315b.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-5ccb035bea26c1e21f80f44cf7c27909.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/09-additive-models-trees-and-related-methods.html"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Additive Models, Trees, and Related Methods</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">esl</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/01-introduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/02-overview-of-supervised-learning.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Overview of Supervised Learning</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/03-linear-methods-for-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Linear Methods for Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/04-linear-methods-for-classification.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Linear Methods for Classification</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/05-basis-expansions-and-regularization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Basis Expansions and Regularization</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/06-kernel-smoothing-methods.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Kernel Smoothing Methods</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/07-model-assessment-and-selection.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Model Assessment and Selection</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/08-model-inference-and-averaging.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Model Inference and Averaging</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/09-additive-models-trees-and-related-methods.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Additive Models, Trees, and Related Methods</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/10-boosting-and-additive-trees.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Boosting and Additive Trees</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/11-neural-networks.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Neural Networks</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/12-support-vector-machines-and-flexible-discriminants.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Support Vector Machines and Flexible Discriminants</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/13-prototype-methods-and-nearest-neighbors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Prototype Methods and Nearest-Neighbors</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/14-unsupervised-learning.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Unsupervised Learning</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/15-random-forests.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Random Forests</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/16-ensemble-learning.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Ensemble Learning</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/17-undirected-graphical-models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Undirected Graphical Models</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/18-high-dimensional-problems.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">High-Dimensional Problems: p ≫ N</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/19-references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">References</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/20-author-index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Author Index</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/21-index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Index</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#generalized-additive-models" id="toc-generalized-additive-models" class="nav-link active" data-scroll-target="#generalized-additive-models"><span class="header-section-number">10</span> 9.1 Generalized Additive Models</a></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary"><span class="header-section-number">11</span> 9.1.3 Summary</a></li>
  <li><a href="#tree-based-methods" id="toc-tree-based-methods" class="nav-link" data-scroll-target="#tree-based-methods"><span class="header-section-number">12</span> 9.2 Tree-Based Methods</a></li>
  <li><a href="#spam-example-continued" id="toc-spam-example-continued" class="nav-link" data-scroll-target="#spam-example-continued"><span class="header-section-number">13</span> 9.2.5 Spam Example (Continued)</a></li>
  <li><a href="#prim-bump-hunting" id="toc-prim-bump-hunting" class="nav-link" data-scroll-target="#prim-bump-hunting"><span class="header-section-number">14</span> 9.3 PRIM: Bump Hunting</a></li>
  <li><a href="#spam-example-continued-1" id="toc-spam-example-continued-1" class="nav-link" data-scroll-target="#spam-example-continued-1"><span class="header-section-number">15</span> 9.3.1 Spam Example (Continued)</a></li>
  <li><a href="#mars-multivariate-adaptive-regression-splines" id="toc-mars-multivariate-adaptive-regression-splines" class="nav-link" data-scroll-target="#mars-multivariate-adaptive-regression-splines"><span class="header-section-number">16</span> 9.4 MARS: Multivariate Adaptive Regression Splines</a>
  <ul class="collapse">
  <li><a href="#spam-example-continued-2" id="toc-spam-example-continued-2" class="nav-link" data-scroll-target="#spam-example-continued-2"><span class="header-section-number">16.1</span> 9.4.1 Spam Example (Continued)</a></li>
  <li><a href="#other-issues-1" id="toc-other-issues-1" class="nav-link" data-scroll-target="#other-issues-1"><span class="header-section-number">16.2</span> 9.4.3 Other Issues</a></li>
  </ul></li>
  <li><a href="#hierarchical-mixtures-of-experts" id="toc-hierarchical-mixtures-of-experts" class="nav-link" data-scroll-target="#hierarchical-mixtures-of-experts"><span class="header-section-number">17</span> 9.5 Hierarchical Mixtures of Experts</a></li>
  <li><a href="#missing-data" id="toc-missing-data" class="nav-link" data-scroll-target="#missing-data"><span class="header-section-number">18</span> 9.6 Missing Data</a></li>
  <li><a href="#computational-considerations" id="toc-computational-considerations" class="nav-link" data-scroll-target="#computational-considerations"><span class="header-section-number">19</span> 9.7 Computational Considerations</a></li>
  <li><a href="#bibliographic-notes" id="toc-bibliographic-notes" class="nav-link" data-scroll-target="#bibliographic-notes"><span class="header-section-number">20</span> Bibliographic Notes</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Additive Models, Trees, and Related Methods</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>In this chapter we begin our discussion of some specific methods for supervised learning. These techniques each assume a (different) structured form for the unknown regression function, and by doing so they finesse the curse of dimensionality. Of course, they pay the possible price of misspecifying the model, and so in each case there is a tradeoff that has to be made. They take off where Chapters 3–6 left off. We describe five related techniques: generalized additive models, trees, multivariate adaptive regression splines, the patient rule induction method, and hierarchical mixtures of experts.</p>
<section id="generalized-additive-models" class="level1" data-number="10">
<h1 data-number="10"><span class="header-section-number">10</span> 9.1 Generalized Additive Models</h1>
<p>Regression models play an important role in many data analyses, providing prediction and classification rules, and data analytic tools for understanding the importance of different inputs.</p>
<p>Although attractively simple, the traditional linear model often fails in these situations: in real life, effects are often not linear. In earlier chapters we described techniques that used predefined basis functions to achieve nonlinearities. This section describes more automatic flexible statistical methods that may be used to identify and characterize nonlinear regression effects. These methods are called “generalized additive models.”</p>
<p>In the regression setting, a generalized additive model has the form</p>
<p><span class="math display">\[E(Y|X_1, X_2, \dots, X_p) = \alpha + f_1(X_1) + f_2(X_2) + \dots + f_p(X_p).\]</span> (9.1)</p>
<p>As usual X1, X2, . . . , X<sup>p</sup> represent predictors and Y is the outcome; the f<sup>j</sup> ’s are unspecified smooth (“nonparametric”) functions. If we were to model each function using an expansion of basis functions (as in Chapter 5), the resulting model could then be fit by simple least squares. Our approach here is different: we fit each function using a scatterplot smoother (e.g., a cubic smoothing spline or kernel smoother), and provide an algorithm for simultaneously estimating all p functions (Section 9.1.1).</p>
<p>For two-class classification, recall the logistic regression model for binary data discussed in Section 4.4. We relate the mean of the binary response µ(X) = Pr(Y = 1|X) to the predictors via a linear regression model and the logit link function:</p>
<p><span class="math display">\[\log\left(\frac{\mu(X)}{1-\mu(X)}\right) = \alpha + \beta_1 X_1 + \dots + \beta_p X_p. \tag{9.2}\]</span></p>
<p>The additive logistic regression model replaces each linear term by a more general functional form</p>
<p><span class="math display">\[\log\left(\frac{\mu(X)}{1-\mu(X)}\right) = \alpha + f_1(X_1) + \dots + f_p(X_p), \tag{9.3}\]</span></p>
<p>where again each f<sup>j</sup> is an unspecified smooth function. While the nonparametric form for the functions f<sup>j</sup> makes the model more flexible, the additivity is retained and allows us to interpret the model in much the same way as before. The additive logistic regression model is an example of a generalized additive model. In general, the conditional mean µ(X) of a response Y is related to an additive function of the predictors via a link function g:</p>
<p><span class="math display">\[g[\mu(X)] = \alpha + f_1(X_1) + \dots + f_p(X_p).\]</span> (9.4)</p>
<p>Examples of classical link functions are the following:</p>
<ul>
<li>g(µ) = µ is the identity link, used for linear and additive models for Gaussian response data.</li>
<li>g(µ) = logit(µ) as above, or g(µ) = probit(µ), the probit link function, for modeling binomial probabilities. The probit function is the inverse Gaussian cumulative distribution function: probit(µ) = Φ<sup>−</sup><sup>1</sup> (µ).</li>
<li>g(µ) = log(µ) for log-linear or log-additive models for Poisson count data.</li>
</ul>
<p>All three of these arise from exponential family sampling models, which in addition include the gamma and negative-binomial distributions. These families generate the well-known class of generalized linear models, which are all extended in the same way to generalized additive models.</p>
<p>The functions f<sup>j</sup> are estimated in a flexible manner, using an algorithm whose basic building block is a scatterplot smoother. The estimated function ˆf<sup>j</sup> can then reveal possible nonlinearities in the effect of X<sup>j</sup> . Not all of the functions <span class="math inline">\(f_j\)</span> need to be nonlinear. We can easily mix in linear and other parametric forms with the nonlinear terms, a necessity when some of the inputs are qualitative variables (factors). The nonlinear terms are not restricted to main effects either; we can have nonlinear components in two or more variables, or separate curves in <span class="math inline">\(X_j\)</span> for each level of the factor <span class="math inline">\(X_k\)</span> . Thus each of the following would qualify:</p>
<ul>
<li><span class="math inline">\(g(\mu) = X^T \beta + \alpha_k + f(Z)\)</span> —a semiparametric model, where X is a vector of predictors to be modeled linearly, <span class="math inline">\(\alpha_k\)</span> the effect for the kth level of a qualitative input V, and the effect of predictor Z is modeled nonparametrically.</li>
<li><span class="math inline">\(g(\mu) = f(X) + g_k(Z)\)</span> —again k indexes the levels of a qualitative input V, and thus creates an interaction term <span class="math inline">\(g(V,Z) = g_k(Z)\)</span> for the effect of V and Z.</li>
<li><span class="math inline">\(g(\mu) = f(X) + g(Z, W)\)</span> where g is a nonparametric function in two features.</li>
</ul>
<p>Additive models can replace linear models in a wide variety of settings, for example an additive decomposition of time series,</p>
<p><span class="math display">\[Y_t = S_t + T_t + \varepsilon_t, \tag{9.5}\]</span></p>
<p>where <span class="math inline">\(S_t\)</span> is a seasonal component, <span class="math inline">\(T_t\)</span> is a trend and <span class="math inline">\(\varepsilon\)</span> is an error term.</p>
<section id="fitting-additive-models" class="level4" data-number="10.0.0.1">
<h4 data-number="10.0.0.1" class="anchored" data-anchor-id="fitting-additive-models"><span class="header-section-number">10.0.0.1</span> 9.1.1 Fitting Additive Models</h4>
<p>In this section we describe a modular algorithm for fitting additive models and their generalizations. The building block is the scatterplot smoother for fitting nonlinear effects in a flexible way. For concreteness we use as our scatterplot smoother the cubic smoothing spline described in Chapter 5.</p>
<p>The additive model has the form</p>
<p><span class="math display">\[Y = \alpha + \sum_{j=1}^{p} f_j(X_j) + \varepsilon, \tag{9.6}\]</span></p>
<p>where the error term <span class="math inline">\(\varepsilon\)</span> has mean zero. Given observations <span class="math inline">\(x_i, y_i\)</span> , a criterion like the penalized sum of squares (5.9) of Section 5.4 can be specified for this problem,</p>
<p><span class="math display">\[PRSS(\alpha, f_1, f_2, \dots, f_p) = \sum_{i=1}^{N} \left( y_i - \alpha - \sum_{j=1}^{p} f_j(x_{ij}) \right)^2 + \sum_{j=1}^{p} \lambda_j \int f_j''(t_j)^2 dt_j,\]</span> (9.7)</p>
<p>where the <span class="math inline">\(\lambda_j \geq 0\)</span> are tuning parameters. It can be shown that the minimizer of (9.7) is an additive cubic spline model; each of the functions <span class="math inline">\(f_j\)</span> is a</p>
</section>
<section id="algorithm-9.1-the-backfitting-algorithm-for-additive-models." class="level4" data-number="10.0.0.2">
<h4 data-number="10.0.0.2" class="anchored" data-anchor-id="algorithm-9.1-the-backfitting-algorithm-for-additive-models."><span class="header-section-number">10.0.0.2</span> <strong>Algorithm 9.1</strong> The Backfitting Algorithm for Additive Models.</h4>
<ul>
<li><ol type="1">
<li>Initialize: <span class="math inline">\(\hat{\alpha} = \frac{1}{N} \sum_{1}^{N} y_i\)</span> , <span class="math inline">\(\hat{f}_j \equiv 0, \forall i, j\)</span> .</li>
</ol></li>
<li><ol start="2" type="1">
<li>Cycle: <span class="math inline">\(j = 1, 2, \dots, p, \dots, 1, 2, \dots, p, \dots\)</span></li>
</ol></li>
</ul>
<p><span class="math display">\[\hat{f}_j \leftarrow \mathcal{S}_j \left[ \{ y_i - \hat{\alpha} - \sum_{k \neq j} \hat{f}_k(x_{ik}) \}_1^N \right],\]</span></p>
<p><span class="math display">\[\hat{f}_j \leftarrow \hat{f}_j - \frac{1}{N} \sum_{i=1}^N \hat{f}_j(x_{ij}).\]</span></p>
<p>until the functions <span class="math inline">\(\hat{f}_i\)</span> change less than a prespecified threshold.</p>
<p>cubic spline in the component <span class="math inline">\(X_j\)</span> , with knots at each of the unique values of <span class="math inline">\(x_{ij}\)</span> , <span class="math inline">\(i=1,\ldots,N\)</span> . However, without further restrictions on the model, the solution is not unique. The constant <span class="math inline">\(\alpha\)</span> is not identifiable, since we can add or subtract any constants to each of the functions <span class="math inline">\(f_j\)</span> , and adjust <span class="math inline">\(\alpha\)</span> accordingly. The standard convention is to assume that <span class="math inline">\(\sum_{1}^{N} f_j(x_{ij}) = 0 \ \forall j\)</span> —the functions average zero over the data. It is easily seen that <span class="math inline">\(\hat{\alpha} = \text{ave}(y_i)\)</span> in this case. If in addition to this restriction, the matrix of input values (having ijth entry <span class="math inline">\(x_{ij}\)</span> ) has full column rank, then (9.7) is a strictly convex criterion and the minimizer is unique. If the matrix is singular, then the linear part of the components <span class="math inline">\(f_j\)</span> cannot be uniquely determined (while the nonlinear parts can!)(Buja et al., 1989).</p>
<p>Furthermore, a simple iterative procedure exists for finding the solution. We set <span class="math inline">\(\hat{\alpha} = \operatorname{ave}(y_i)\)</span> , and it never changes. We apply a cubic smoothing spline <span class="math inline">\(S_j\)</span> to the targets <span class="math inline">\(\{y_i - \hat{\alpha} - \sum_{k \neq j} \hat{f}_k(x_{ik})\}_1^N\)</span> , as a function of <span class="math inline">\(x_{ij}\)</span> , to obtain a new estimate <span class="math inline">\(\hat{f}_j\)</span> . This is done for each predictor in turn, using the current estimates of the other functions <span class="math inline">\(\hat{f}_k\)</span> when computing <span class="math inline">\(y_i - \hat{\alpha} - \sum_{k \neq j} \hat{f}_k(x_{ik})\)</span> . The process is continued until the estimates <span class="math inline">\(\hat{f}_j\)</span> stabilize. This procedure, given in detail in Algorithm 9.1, is known as “backfitting” and the resulting fit is analogous to a multiple regression for linear models.</p>
<p>In principle, the second step in (2) of Algorithm 9.1 is not needed, since the smoothing spline fit to a mean-zero response has mean zero (Exercise 9.1). In practice, machine rounding can cause slippage, and the adjustment is advised.</p>
<p>This same algorithm can accommodate other fitting methods in exactly the same way, by specifying appropriate smoothing operators <span class="math inline">\(S_i\)</span> :</p>
<p>other univariate regression smoothers such as local polynomial regression and kernel methods;</p>
<ul>
<li>linear regression operators yielding polynomial fits, piecewise constant fits, parametric spline fits, series and Fourier fits;</li>
<li>more complicated operators such as surface smoothers for second or higher-order interactions or periodic smoothers for seasonal effects.</li>
</ul>
<p>If we consider the operation of smoother <span class="math inline">\(S_j\)</span> only at the training points, it can be represented by an <span class="math inline">\(N \times N\)</span> operator matrix <span class="math inline">\(\mathbf{S}_j\)</span> (see Section 5.4.1). Then the degrees of freedom for the jth term are (approximately) computed as <span class="math inline">\(\mathrm{df}_j = \mathrm{trace}[\mathbf{S}_j] - 1\)</span> , by analogy with degrees of freedom for smoothers discussed in Chapters 5 and 6.</p>
<p>For a large class of linear smoothers <span class="math inline">\(S_j\)</span> , backfitting is equivalent to a Gauss–Seidel algorithm for solving a certain linear system of equations. Details are given in Exercise 9.2.</p>
<p>For the logistic regression model and other generalized additive models, the appropriate criterion is a penalized log-likelihood. To maximize it, the backfitting procedure is used in conjunction with a likelihood maximizer. The usual Newton–Raphson routine for maximizing log-likelihoods in generalized linear models can be recast as an IRLS (iteratively reweighted least squares) algorithm. This involves repeatedly fitting a weighted linear regression of a working response variable on the covariates; each regression yields a new value of the parameter estimates, which in turn give new working responses and weights, and the process is iterated (see Section 4.4.1). In the generalized additive model, the weighted linear regression is simply replaced by a weighted backfitting algorithm. We describe the algorithm in more detail for logistic regression below, and more generally in Chapter 6 of Hastie and Tibshirani (1990).</p>
</section>
<section id="example-additive-logistic-regression" class="level4" data-number="10.0.0.3">
<h4 data-number="10.0.0.3" class="anchored" data-anchor-id="example-additive-logistic-regression"><span class="header-section-number">10.0.0.3</span> 9.1.2 Example: Additive Logistic Regression</h4>
<p>Probably the most widely used model in medical research is the logistic model for binary data. In this model the outcome Y can be coded as 0 or 1, with 1 indicating an event (like death or relapse of a disease) and 0 indicating no event. We wish to model <span class="math inline">\(\Pr(Y=1|X)\)</span> , the probability of an event given values of the prognostic factors <span class="math inline">\(X^T=(X_1,\ldots,X_p)\)</span> . The goal is usually to understand the roles of the prognostic factors, rather than to classify new individuals. Logistic models are also used in applications where one is interested in estimating the class probabilities, for use in risk screening. Apart from medical applications, credit risk screening is a popular application.</p>
<p>The generalized additive logistic model has the form</p>
<p><span class="math display">\[\log \frac{\Pr(Y=1|X)}{\Pr(Y=0|X)} = \alpha + f_1(X_1) + \dots + f_p(X_p).\]</span> (9.8)</p>
<p>The functions <span class="math inline">\(f_1, f_2, \ldots, f_p\)</span> are estimated by a backfitting algorithm within a Newton-Raphson procedure, shown in Algorithm 9.2.</p>
<p>Algorithm 9.2 Local Scoring Algorithm for the Additive Logistic Regression Model.</p>
<ul>
<li><ol type="1">
<li>Compute starting values: ˆα = log[¯y/(1 − y¯)], where ¯y = ave(yi), the sample proportion of ones, and set <sup>ˆ</sup>f<sup>j</sup> <sup>≡</sup> <sup>0</sup> <sup>∀</sup>j.</li>
</ol></li>
<li><ol start="2" type="1">
<li>Define ˆη<sup>i</sup> = ˆα + P j <sup>ˆ</sup>f<sup>j</sup> (xij ) and ˆp<sup>i</sup> = 1/[1 + exp(−ηˆi)]. Iterate:</li>
</ol>
<ul>
<li><ol type="a">
<li>Construct the working target variable</li>
</ol></li>
</ul></li>
</ul>
<p><span class="math display">\[z_i = \hat{\eta}_i + \frac{(y_i - \hat{p}_i)}{\hat{p}_i(1 - \hat{p}_i)}.\]</span></p>
<ul>
<li><ol start="2" type="a">
<li>Construct weights w<sup>i</sup> = ˆpi(1 − pˆi)</li>
</ol></li>
<li><ol start="3" type="a">
<li>Fit an additive model to the targets z<sup>i</sup> with weights w<sup>i</sup> , using a weighted backfitting algorithm. This gives new estimates α, ˆ <sup>ˆ</sup>f<sup>j</sup> , <sup>∀</sup><sup>j</sup></li>
</ol></li>
<li><ol start="3" type="1">
<li>Continue step 2. until the change in the functions falls below a prespecified threshold.</li>
</ol></li>
</ul>
<p>The additive model fitting in step (2) of Algorithm 9.2 requires a weighted scatterplot smoother. Most smoothing procedures can accept observation weights (Exercise 5.12); see Chapter 3 of Hastie and Tibshirani (1990) for further details.</p>
<p>The additive logistic regression model can be generalized further to handle more than two classes, using the multilogit formulation as outlined in Section 4.4. While the formulation is a straightforward extension of (9.8), the algorithms for fitting such models are more complex. See Yee and Wild (1996) for details, and the VGAM software currently available from:</p>
<p>http://www.stat.auckland.ac.nz/∼yee.</p>
</section>
<section id="example-predicting-email-spam" class="level4" data-number="10.0.0.4">
<h4 data-number="10.0.0.4" class="anchored" data-anchor-id="example-predicting-email-spam"><span class="header-section-number">10.0.0.4</span> Example: Predicting Email Spam</h4>
<p>We apply a generalized additive model to the spam data introduced in Chapter 1. The data consists of information from 4601 email messages, in a study to screen email for “spam” (i.e., junk email). The data is publicly available at ftp.ics.uci.edu, and was donated by George Forman from Hewlett-Packard laboratories, Palo Alto, California.</p>
<p>The response variable is binary, with values email or spam, and there are 57 predictors as described below:</p>
<p>• 48 quantitative predictors—the percentage of words in the email that match a given word. Examples include business, address, internet,</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th>Predicted Class</th>
<th></th>
<th></th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>True Class</td>
<td>email<br>(0)</td>
<td>spam<br>(1)</td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>email<br>(0)</td>
<td>58.3%</td>
<td>2.5%</td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>spam<br>(1)</td>
<td>3.0%</td>
<td>36.3%</td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<p>TABLE 9.1. Test data confusion matrix for the additive logistic regression model fit to the spam training data. The overall test error rate is 5.5%.</p>
<p>free, and george. The idea was that these could be customized for individual users.</p>
<ul>
<li>6 quantitative predictors—the percentage of characters in the email that match a given character. The characters are ch;, ch(, ch[, ch!, ch$, and ch#.</li>
<li>The average length of uninterrupted sequences of capital letters: CAPAVE.</li>
<li>The length of the longest uninterrupted sequence of capital letters: CAPMAX.</li>
<li>The sum of the length of uninterrupted sequences of capital letters: CAPTOT.</li>
</ul>
<p>We coded spam as 1 and email as zero. A test set of size 1536 was randomly chosen, leaving 3065 observations in the training set. A generalized additive model was fit, using a cubic smoothing spline with a nominal four degrees of freedom for each predictor. What this means is that for each predictor X<sup>j</sup> , the smoothing-spline parameter λ<sup>j</sup> was chosen so that trace[S<sup>j</sup> (λ<sup>j</sup> )]−1 = 4, where S<sup>j</sup> (λ) is the smoothing spline operator matrix constructed using the observed values xij , i = 1, . . . , N. This is a convenient way of specifying the amount of smoothing in such a complex model.</p>
<p>Most of the spam predictors have a very long-tailed distribution. Before fitting the GAM model, we log-transformed each variable (actually log(x+ 0.1)), but the plots in Figure 9.1 are shown as a function of the original variables.</p>
<p>The test error rates are shown in Table 9.1; the overall error rate is 5.3%. By comparison, a linear logistic regression has a test error rate of 7.6%. Table 9.2 shows the predictors that are highly significant in the additive model.</p>
<p>For ease of interpretation, in Table 9.2 the contribution for each variable is decomposed into a linear component and the remaining nonlinear component. The top block of predictors are positively correlated with spam, while the bottom block is negatively correlated. The linear component is a weighted least squares linear fit of the fitted curve on the predictor, while the nonlinear part is the residual. The linear component of an estimated</p>
<table class="caption-top table">
<colgroup>
<col style="width: 100%">
</colgroup>
<thead>
<tr class="header">
<th><b>TABLE 9.2.</b> Significant predictors from the additive model fit to the spam train-</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>ing data. The coefficients represent the linear part of <span class="math inline">\(\hat{f}_j\)</span> , along with their standard</td>
</tr>
<tr class="even">
<td>errors and Z-score. The nonlinear P-value is for a test of nonlinearity of <span class="math inline">\(\hat{f}_j\)</span> .</td>
</tr>
</tbody>
</table>
<table class="caption-top table">
<colgroup>
<col style="width: 13%">
<col style="width: 8%">
<col style="width: 6%">
<col style="width: 17%">
<col style="width: 16%">
<col style="width: 12%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Name</th>
<th>Num.</th>
<th>df</th>
<th>Coefficient</th>
<th>Std. Error</th>
<th>Z Score</th>
<th>Nonlinear P-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td></td>
<td></td>
<td></td>
<td>Positive e</td>
<td>effects</td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>our</td>
<td>5</td>
<td>3.9</td>
<td>0.566</td>
<td>0.114</td>
<td>4.970</td>
<td>0.052</td>
</tr>
<tr class="odd">
<td>over</td>
<td>6</td>
<td>3.9</td>
<td>0.244</td>
<td>0.195</td>
<td>1.249</td>
<td>0.004</td>
</tr>
<tr class="even">
<td>remove</td>
<td>7</td>
<td>4.0</td>
<td>0.949</td>
<td>0.183</td>
<td>5.201</td>
<td>0.093</td>
</tr>
<tr class="odd">
<td>internet</td>
<td>8</td>
<td>4.0</td>
<td>0.524</td>
<td>0.176</td>
<td>2.974</td>
<td>0.028</td>
</tr>
<tr class="even">
<td>free</td>
<td>16</td>
<td>3.9</td>
<td>0.507</td>
<td>0.127</td>
<td>4.010</td>
<td>0.065</td>
</tr>
<tr class="odd">
<td>business</td>
<td>17</td>
<td>3.8</td>
<td>0.779</td>
<td>0.186</td>
<td>4.179</td>
<td>0.194</td>
</tr>
<tr class="even">
<td>hpl</td>
<td>26</td>
<td>3.8</td>
<td>0.045</td>
<td>0.250</td>
<td>0.181</td>
<td>0.002</td>
</tr>
<tr class="odd">
<td>ch!</td>
<td>52</td>
<td>4.0</td>
<td>0.674</td>
<td>0.128</td>
<td>5.283</td>
<td>0.164</td>
</tr>
<tr class="even">
<td>ch$</td>
<td>53</td>
<td>3.9</td>
<td>1.419</td>
<td>0.280</td>
<td>5.062</td>
<td>0.354</td>
</tr>
<tr class="odd">
<td>CAPMAX</td>
<td>56</td>
<td>3.8</td>
<td>0.247</td>
<td>0.228</td>
<td>1.080</td>
<td>0.000</td>
</tr>
<tr class="even">
<td>CAPTOT</td>
<td>57</td>
<td>4.0</td>
<td>0.755</td>
<td>0.165</td>
<td>4.566</td>
<td>0.063</td>
</tr>
<tr class="odd">
<td></td>
<td>•</td>
<td>•</td>
<td>Negative of</td>
<td>effects</td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>hp</td>
<td>25</td>
<td>3.9</td>
<td>-1.404</td>
<td>0.224</td>
<td>-6.262</td>
<td>0.140</td>
</tr>
<tr class="odd">
<td>george</td>
<td>27</td>
<td>3.7</td>
<td>-5.003</td>
<td>0.744</td>
<td>-6.722</td>
<td>0.045</td>
</tr>
<tr class="even">
<td>1999</td>
<td>37</td>
<td>3.8</td>
<td>-0.672</td>
<td>0.191</td>
<td>-3.512</td>
<td>0.011</td>
</tr>
<tr class="odd">
<td>re</td>
<td>45</td>
<td>3.9</td>
<td>-0.620</td>
<td>0.133</td>
<td>-4.649</td>
<td>0.597</td>
</tr>
<tr class="even">
<td>edu</td>
<td>46</td>
<td>4.0</td>
<td>-1.183</td>
<td>0.209</td>
<td>-5.647</td>
<td>0.000</td>
</tr>
</tbody>
</table>
<p>function is summarized by the coefficient, standard error and Z-score; the latter is the coefficient divided by its standard error, and is considered significant if it exceeds the appropriate quantile of a standard normal distribution. The column labeled <span class="math inline">\(nonlinear\ P\)</span> -value is a test of nonlinearity of the estimated function. Note, however, that the effect of each predictor is fully adjusted for the entire effects of the other predictors, not just for their linear parts. The predictors shown in the table were judged significant by at least one of the tests (linear or nonlinear) at the p=0.01 level (two-sided).</p>
<p>Figure 9.1 shows the estimated functions for the significant predictors appearing in Table 9.2. Many of the nonlinear effects appear to account for a strong discontinuity at zero. For example, the probability of spam drops significantly as the frequency of george increases from zero, but then does not change much after that. This suggests that one might replace each of the frequency predictors by an indicator variable for a zero count, and resort to a linear logistic model. This gave a test error rate of 7.4%; including the linear effects of the frequencies as well dropped the test error to 6.6%. It appears that the nonlinearities in the additive model have an additional predictive power.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figures/_page_321_Figure_2.jpeg" class="img-fluid figure-img"></p>
<figcaption>Figure 9.1</figcaption>
</figure>
</div>
<p>FIGURE 9.1. Spam analysis: estimated functions for significant predictors. The rug plot along the bottom of each frame indicates the observed values of the corresponding predictor. For many of the predictors the nonlinearity picks up the discontinuity at zero.</p>
<p>It is more serious to classify a genuine email message as spam, since then a good email would be filtered out and would not reach the user. We can alter the balance between the class error rates by changing the losses (see Section 2.4). If we assign a loss L<sup>01</sup> for predicting a true class 0 as class 1, and L<sup>10</sup> for predicting a true class 1 as class 0, then the estimated Bayes rule predicts class 1 if its probability is greater than L01/(L<sup>01</sup> + L10). For example, if we take L<sup>01</sup> = 10, L<sup>10</sup> = 1 then the (true) class 0 and class 1 error rates change to 0.8% and 8.7%.</p>
<p>More ambitiously, we can encourage the model to fit better data in the class 0 by using weights L<sup>01</sup> for the class 0 observations and L<sup>10</sup> for the class 1 observations. As above, we then use the estimated Bayes rule to predict. This gave error rates of 1.2% and 8.0% in (true) class 0 and class 1, respectively. We discuss below the issue of unequal losses further, in the context of tree-based models.</p>
<p>After fitting an additive model, one should check whether the inclusion of some interactions can significantly improve the fit. This can be done “manually,” by inserting products of some or all of the significant inputs, or automatically via the MARS procedure (Section 9.4).</p>
<p>This example uses the additive model in an automatic fashion. As a data analysis tool, additive models are often used in a more interactive fashion, adding and dropping terms to determine their effect. By calibrating the amount of smoothing in terms of df<sup>j</sup> , one can move seamlessly between linear models (df<sup>j</sup> = 1) and partially linear models, where some terms are modeled more flexibly. See Hastie and Tibshirani (1990) for more details.</p>
</section>
</section>
<section id="summary" class="level1" data-number="11">
<h1 data-number="11"><span class="header-section-number">11</span> 9.1.3 Summary</h1>
<p>Additive models provide a useful extension of linear models, making them more flexible while still retaining much of their interpretability. The familiar tools for modeling and inference in linear models are also available for additive models, seen for example in Table 9.2. The backfitting procedure for fitting these models is simple and modular, allowing one to choose a fitting method appropriate for each input variable. As a result they have become widely used in the statistical community.</p>
<p>However additive models can have limitations for large data-mining applications. The backfitting algorithm fits all predictors, which is not feasible or desirable when a large number are available. The BRUTO procedure (Hastie and Tibshirani, 1990, Chapter 9) combines backfitting with selection of inputs, but is not designed for large data-mining problems. There has also been recent work using lasso-type penalties to estimate sparse additive models, for example the COSSO procedure of Lin and Zhang (2006) and the SpAM proposal of Ravikumar et al.&nbsp;(2008). For large problems a forward stagewise approach such as boosting (Chapter 10) is more effective, and also allows for interactions to be included in the model.</p>
</section>
<section id="tree-based-methods" class="level1" data-number="12">
<h1 data-number="12"><span class="header-section-number">12</span> 9.2 Tree-Based Methods</h1>
<section id="background" class="level4" data-number="12.0.0.1">
<h4 data-number="12.0.0.1" class="anchored" data-anchor-id="background"><span class="header-section-number">12.0.0.1</span> 9.2.1 Background</h4>
<p>Tree-based methods partition the feature space into a set of rectangles, and then fit a simple model (like a constant) in each one. They are conceptually simple yet powerful. We first describe a popular method for tree-based regression and classification called CART, and later contrast it with C4.5, a major competitor.</p>
<p>Let’s consider a regression problem with continuous response Y and inputs X<sup>1</sup> and X2, each taking values in the unit interval. The top left panel of Figure 9.2 shows a partition of the feature space by lines that are parallel to the coordinate axes. In each partition element we can model Y with a different constant. However, there is a problem: although each partitioning line has a simple description like X<sup>1</sup> = c, some of the resulting regions are complicated to describe.</p>
<p>To simplify matters, we restrict attention to recursive binary partitions like that in the top right panel of Figure 9.2. We first split the space into two regions, and model the response by the mean of Y in each region. We choose the variable and split-point to achieve the best fit. Then one or both of these regions are split into two more regions, and this process is continued, until some stopping rule is applied. For example, in the top right panel of Figure 9.2, we first split at X<sup>1</sup> = t1. Then the region X<sup>1</sup> ≤ t<sup>1</sup> is split at X<sup>2</sup> = t<sup>2</sup> and the region X<sup>1</sup> &gt; t<sup>1</sup> is split at X<sup>1</sup> = t3. Finally, the region X<sup>1</sup> &gt; t<sup>3</sup> is split at X<sup>2</sup> = t4. The result of this process is a partition into the five regions R1, R2, . . . , R<sup>5</sup> shown in the figure. The corresponding regression model predicts Y with a constant c<sup>m</sup> in region Rm, that is,</p>
<p><span class="math display">\[\hat{f}(X) = \sum_{m=1}^{5} c_m I\{(X_1, X_2) \in R_m\}.\]</span> (9.9)</p>
<p>This same model can be represented by the binary tree in the bottom left panel of Figure 9.2. The full dataset sits at the top of the tree. Observations satisfying the condition at each junction are assigned to the left branch, and the others to the right branch. The terminal nodes or leaves of the tree correspond to the regions R1, R2, . . . , R5. The bottom right panel of Figure 9.2 is a perspective plot of the regression surface from this model. For illustration, we chose the node means c<sup>1</sup> = −5, c<sup>2</sup> = −7, c<sup>3</sup> = 0, c<sup>4</sup> = 2, c<sup>5</sup> = 4 to make this plot.</p>
<p>A key advantage of the recursive binary tree is its interpretability. The feature space partition is fully described by a single tree. With more than two inputs, partitions like that in the top right panel of Figure 9.2 are difficult to draw, but the binary tree representation works in the same way. This representation is also popular among medical scientists, perhaps because it mimics the way that a doctor thinks. The tree stratifies the</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figures/_page_324_Figure_2.jpeg" class="img-fluid figure-img"></p>
<figcaption>Figure 9.2</figcaption>
</figure>
</div>
<p>FIGURE 9.2. Partitions and CART. Top right panel shows a partition of a two-dimensional feature space by recursive binary splitting, as used in CART, applied to some fake data. Top left panel shows a general partition that cannot be obtained from recursive binary splitting. Bottom left panel shows the tree corresponding to the partition in the top right panel, and a perspective plot of the prediction surface appears in the bottom right panel.</p>
<p>population into strata of high and low outcome, on the basis of patient characteristics.</p>
</section>
<section id="regression-trees" class="level4" data-number="12.0.0.2">
<h4 data-number="12.0.0.2" class="anchored" data-anchor-id="regression-trees"><span class="header-section-number">12.0.0.2</span> 9.2.2 Regression Trees</h4>
<p>We now turn to the question of how to grow a regression tree. Our data consists of p inputs and a response, for each of N observations: that is, (x<sup>i</sup> , yi) for i = 1, 2, . . . , N, with x<sup>i</sup> = (xi1, xi2, . . . , xip). The algorithm needs to automatically decide on the splitting variables and split points, and also what topology (shape) the tree should have. Suppose first that we have a partition into M regions R1, R2, . . . , RM, and we model the response as a constant c<sup>m</sup> in each region:</p>
<p><span class="math display">\[f(x) = \sum_{m=1}^{M} c_m I(x \in R_m).\]</span> (9.10)</p>
<p>If we adopt as our criterion minimization of the sum of squares <sup>P</sup>(y<sup>i</sup> <sup>−</sup> f(xi))<sup>2</sup> , it is easy to see that the best ˆc<sup>m</sup> is just the average of y<sup>i</sup> in region Rm:</p>
<p><span class="math display">\[\hat{c}_m = \text{ave}(y_i | x_i \in R_m). \tag{9.11}\]</span></p>
<p>Now finding the best binary partition in terms of minimum sum of squares is generally computationally infeasible. Hence we proceed with a greedy algorithm. Starting with all of the data, consider a splitting variable j and split point s, and define the pair of half-planes</p>
<p><span class="math display">\[R_1(j,s) = \{X | X_j \le s\} \text{ and } R_2(j,s) = \{X | X_j &gt; s\}.\]</span> (9.12)</p>
<p>Then we seek the splitting variable j and split point s that solve</p>
<p><span class="math display">\[\min_{j, s} \left[ \min_{c_1} \sum_{x_i \in R_1(j, s)} (y_i - c_1)^2 + \min_{c_2} \sum_{x_i \in R_2(j, s)} (y_i - c_2)^2 \right].\]</span> (9.13)</p>
<p>For any choice j and s, the inner minimization is solved by</p>
<p><span class="math display">\[\hat{c}_1 = \text{ave}(y_i | x_i \in R_1(j, s)) \text{ and } \hat{c}_2 = \text{ave}(y_i | x_i \in R_2(j, s)).\]</span> (9.14)</p>
<p>For each splitting variable, the determination of the split point s can be done very quickly and hence by scanning through all of the inputs, determination of the best pair (j, s) is feasible.</p>
<p>Having found the best split, we partition the data into the two resulting regions and repeat the splitting process on each of the two regions. Then this process is repeated on all of the resulting regions.</p>
<p>How large should we grow the tree? Clearly a very large tree might overfit the data, while a small tree might not capture the important structure. Tree size is a tuning parameter governing the model’s complexity, and the optimal tree size should be adaptively chosen from the data. One approach would be to split tree nodes only if the decrease in sum-of-squares due to the split exceeds some threshold. This strategy is too short-sighted, however, since a seemingly worthless split might lead to a very good split below it.</p>
<p>The preferred strategy is to grow a large tree <span class="math inline">\(T_0\)</span> , stopping the splitting process only when some minimum node size (say 5) is reached. Then this large tree is pruned using <em>cost-complexity pruning</em>, which we now describe.</p>
<p>We define a subtree <span class="math inline">\(T \subset T_0\)</span> to be any tree that can be obtained by pruning <span class="math inline">\(T_0\)</span> , that is, collapsing any number of its internal (non-terminal) nodes. We index terminal nodes by m, with node m representing region <span class="math inline">\(R_m\)</span> . Let |T| denote the number of terminal nodes in T. Letting</p>
<p><span class="math display">\[N_{m} = \#\{x_{i} \in R_{m}\},\]</span></p>
<p><span class="math display">\[\hat{c}_{m} = \frac{1}{N_{m}} \sum_{x_{i} \in R_{m}} y_{i},\]</span></p>
<p><span class="math display">\[Q_{m}(T) = \frac{1}{N_{m}} \sum_{x_{i} \in R_{m}} (y_{i} - \hat{c}_{m})^{2},\]</span> (9.15)</p>
<p>we define the cost complexity criterion</p>
<p><span class="math display">\[C_{\alpha}(T) = \sum_{m=1}^{|T|} N_m Q_m(T) + \alpha |T|. \tag{9.16}\]</span></p>
<p>The idea is to find, for each <span class="math inline">\(\alpha\)</span> , the subtree <span class="math inline">\(T_{\alpha} \subseteq T_0\)</span> to minimize <span class="math inline">\(C_{\alpha}(T)\)</span> . The tuning parameter <span class="math inline">\(\alpha \geq 0\)</span> governs the tradeoff between tree size and its goodness of fit to the data. Large values of <span class="math inline">\(\alpha\)</span> result in smaller trees <span class="math inline">\(T_{\alpha}\)</span> , and conversely for smaller values of <span class="math inline">\(\alpha\)</span> . As the notation suggests, with <span class="math inline">\(\alpha = 0\)</span> the solution is the full tree <span class="math inline">\(T_0\)</span> . We discuss how to adaptively choose <span class="math inline">\(\alpha\)</span> below.</p>
<p>For each <span class="math inline">\(\alpha\)</span> one can show that there is a unique smallest subtree <span class="math inline">\(T_{\alpha}\)</span> that minimizes <span class="math inline">\(C_{\alpha}(T)\)</span> . To find <span class="math inline">\(T_{\alpha}\)</span> we use weakest link pruning: we successively collapse the internal node that produces the smallest per-node increase in <span class="math inline">\(\sum_{m} N_{m}Q_{m}(T)\)</span> , and continue until we produce the single-node (root) tree. This gives a (finite) sequence of subtrees, and one can show this sequence must contain <span class="math inline">\(T_{\alpha}\)</span> . See Breiman et al.&nbsp;(1984) or Ripley (1996) for details. Estimation of <span class="math inline">\(\alpha\)</span> is achieved by five- or tenfold cross-validation: we choose the value <span class="math inline">\(\hat{\alpha}\)</span> to minimize the cross-validated sum of squares. Our final tree is <span class="math inline">\(T_{\hat{\alpha}}\)</span> .</p>
</section>
<section id="classification-trees" class="level4" data-number="12.0.0.3">
<h4 data-number="12.0.0.3" class="anchored" data-anchor-id="classification-trees"><span class="header-section-number">12.0.0.3</span> 9.2.3 Classification Trees</h4>
<p>If the target is a classification outcome taking values 1, 2, …, K, the only changes needed in the tree algorithm pertain to the criteria for splitting nodes and pruning the tree. For regression we used the squared-error node</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figures/_page_327_Figure_2.jpeg" class="img-fluid figure-img"></p>
<figcaption>Figure 9.3</figcaption>
</figure>
</div>
<p>FIGURE 9.3. Node impurity measures for two-class classification, as a function of the proportion p in class 2. Cross-entropy has been scaled to pass through (0.5, 0.5).</p>
<p>impurity measure Qm(T) defined in (9.15), but this is not suitable for classification. In a node m, representing a region R<sup>m</sup> with N<sup>m</sup> observations, let</p>
<p><span class="math display">\[\hat{p}_{mk} = \frac{1}{N_m} \sum_{x_i \in R_m} I(y_i = k),\]</span></p>
<p>the proportion of class k observations in node m. We classify the observations in node m to class k(m) = arg max<sup>k</sup> pˆmk, the majority class in node m. Different measures Qm(T) of node impurity include the following:</p>
<p>Misclassification error: <sup>1</sup> N<sup>m</sup> P i∈R<sup>m</sup> I(y<sup>i</sup> 6= k(m)) = 1 − pˆmk(m) . Gini index: P <sup>k</sup>6=k′ pˆmkpˆmk′ = P<sup>K</sup> <sup>k</sup>=1 pˆmk(1 − pˆmk). Cross-entropy or deviance: − P<sup>K</sup> <sup>k</sup>=1 pˆmk log ˆpmk. (9.17)</p>
<p>For two classes, if p is the proportion in the second class, these three measures are 1 − max(p, 1 − p), 2p(1 − p) and −p log p − (1 − p) log (1 − p), respectively. They are shown in Figure 9.3. All three are similar, but crossentropy and the Gini index are differentiable, and hence more amenable to numerical optimization. Comparing (9.13) and (9.15), we see that we need to weight the node impurity measures by the number Nm<sup>L</sup> and Nm<sup>R</sup> of observations in the two child nodes created by splitting node m.</p>
<p>In addition, cross-entropy and the Gini index are more sensitive to changes in the node probabilities than the misclassification rate. For example, in a two-class problem with 400 observations in each class (denote this by (400, 400)), suppose one split created nodes (300, 100) and (100, 300), while</p>
<p>the other created nodes (200, 400) and (200, 0). Both splits produce a misclassification rate of 0.25, but the second split produces a pure node and is probably preferable. Both the Gini index and cross-entropy are lower for the second split. For this reason, either the Gini index or cross-entropy should be used when growing the tree. To guide cost-complexity pruning, any of the three measures can be used, but typically it is the misclassification rate.</p>
<p>The Gini index can be interpreted in two interesting ways. Rather than classify observations to the majority class in the node, we could classify them to class k with probability <span class="math inline">\(\hat{p}_{mk}\)</span> . Then the expected training error rate of this rule in the node is <span class="math inline">\(\sum_{k \neq k'} \hat{p}_{mk} \hat{p}_{mk'}\)</span> —the Gini index. Similarly, if we code each observation as 1 for class k and zero otherwise, the variance over the node of this 0-1 response is <span class="math inline">\(\hat{p}_{mk}(1-\hat{p}_{mk})\)</span> . Summing over classes k again gives the Gini index.</p>
</section>
<section id="other-issues" class="level4" data-number="12.0.0.4">
<h4 data-number="12.0.0.4" class="anchored" data-anchor-id="other-issues"><span class="header-section-number">12.0.0.4</span> 9.2.4 Other Issues</h4>
</section>
<section id="categorical-predictors" class="level4" data-number="12.0.0.5">
<h4 data-number="12.0.0.5" class="anchored" data-anchor-id="categorical-predictors"><span class="header-section-number">12.0.0.5</span> Categorical Predictors</h4>
<p>When splitting a predictor having q possible unordered values, there are <span class="math inline">\(2^{q-1}-1\)</span> possible partitions of the q values into two groups, and the computations become prohibitive for large q. However, with a 0-1 outcome, this computation simplifies. We order the predictor classes according to the proportion falling in outcome class 1. Then we split this predictor as if it were an ordered predictor. One can show this gives the optimal split, in terms of cross-entropy or Gini index, among all possible <span class="math inline">\(2^{q-1}-1\)</span> splits. This result also holds for a quantitative outcome and square error loss—the categories are ordered by increasing mean of the outcome. Although intuitive, the proofs of these assertions are not trivial. The proof for binary outcomes is given in Breiman et al.&nbsp;(1984) and Ripley (1996); the proof for quantitative outcomes can be found in Fisher (1958). For multicategory outcomes, no such simplifications are possible, although various approximations have been proposed (Loh and Vanichsetakul, 1988).</p>
<p>The partitioning algorithm tends to favor categorical predictors with many levels q; the number of partitions grows exponentially in q, and the more choices we have, the more likely we can find a good one for the data at hand. This can lead to severe overfitting if q is large, and such variables should be avoided.</p>
</section>
<section id="the-loss-matrix" class="level4" data-number="12.0.0.6">
<h4 data-number="12.0.0.6" class="anchored" data-anchor-id="the-loss-matrix"><span class="header-section-number">12.0.0.6</span> The Loss Matrix</h4>
<p>In classification problems, the consequences of misclassifying observations are more serious in some classes than others. For example, it is probably worse to predict that a person will not have a heart attack when he/she actually will, than vice versa. To account for this, we define a <span class="math inline">\(K \times K\)</span> loss matrix <span class="math inline">\(\mathbf{L}\)</span> , with <span class="math inline">\(L_{kk'}\)</span> being the loss incurred for classifying a class k observation as class k’. Typically no loss is incurred for correct classifications,</p>
<p>that is, <span class="math inline">\(L_{kk} = 0 \ \forall k\)</span> . To incorporate the losses into the modeling process, we could modify the Gini index to <span class="math inline">\(\sum_{k \neq k'} L_{kk'} \hat{p}_{mk} \hat{p}_{mk'}\)</span> ; this would be the expected loss incurred by the randomized rule. This works for the multiclass case, but in the two-class case has no effect, since the coefficient of <span class="math inline">\(\hat{p}_{mk}\hat{p}_{mk'}\)</span> is <span class="math inline">\(L_{kk'} + L_{k'k}\)</span> . For two classes a better approach is to weight the observations in class k by <span class="math inline">\(L_{kk'}\)</span> . This can be used in the multiclass case only if, as a function of k, <span class="math inline">\(L_{kk'}\)</span> doesn’t depend on k’. Observation weighting can be used with the deviance as well. The effect of observation weighting is to alter the prior probability on the classes. In a terminal node, the empirical Bayes rule implies that we classify to class <span class="math inline">\(k(m) = \arg\min_k \sum_{\ell} L_{\ell k} \hat{p}_{m\ell}\)</span> .</p>
</section>
<section id="missing-predictor-values" class="level4" data-number="12.0.0.7">
<h4 data-number="12.0.0.7" class="anchored" data-anchor-id="missing-predictor-values"><span class="header-section-number">12.0.0.7</span> Missing Predictor Values</h4>
<p>Suppose our data has some missing predictor values in some or all of the variables. We might discard any observation with some missing values, but this could lead to serious depletion of the training set. Alternatively we might try to fill in (impute) the missing values, with say the mean of that predictor over the nonmissing observations. For tree-based models, there are two better approaches. The first is applicable to categorical predictors: we simply make a new category for “missing.” From this we might discover that observations with missing values for some measurement behave differently than those with nonmissing values. The second more general approach is the construction of surrogate variables. When considering a predictor for a split, we use only the observations for which that predictor is not missing. Having chosen the best (primary) predictor and split point, we form a list of surrogate predictors and split points. The first surrogate is the predictor and corresponding split point that best mimics the split of the training data achieved by the primary split. The second surrogate is the predictor and corresponding split point that does second best, and so on. When sending observations down the tree either in the training phase or during prediction, we use the surrogate splits in order, if the primary splitting predictor is missing. Surrogate splits exploit correlations between predictors to try and alleviate the effect of missing data. The higher the correlation between the missing predictor and the other predictors, the smaller the loss of information due to the missing value. The general problem of missing data is discussed in Section 9.6.</p>
</section>
<section id="why-binary-splits" class="level4" data-number="12.0.0.8">
<h4 data-number="12.0.0.8" class="anchored" data-anchor-id="why-binary-splits"><span class="header-section-number">12.0.0.8</span> Why Binary Splits?</h4>
<p>Rather than splitting each node into just two groups at each stage (as above), we might consider multiway splits into more than two groups. While this can sometimes be useful, it is not a good general strategy. The problem is that multiway splits fragment the data too quickly, leaving insufficient data at the next level down. Hence we would want to use such splits only when needed. Since multiway splits can be achieved by a series of binary splits, the latter are preferred.</p>
</section>
<section id="other-tree-building-procedures" class="level4" data-number="12.0.0.9">
<h4 data-number="12.0.0.9" class="anchored" data-anchor-id="other-tree-building-procedures"><span class="header-section-number">12.0.0.9</span> Other Tree-Building Procedures</h4>
<p>The discussion above focuses on the CART (classification and regression tree) implementation of trees. The other popular methodology is ID3 and its later versions, C4.5 and C5.0 (Quinlan, 1993). Early versions of the program were limited to categorical predictors, and used a top-down rule with no pruning. With more recent developments, C5.0 has become quite similar to CART. The most significant feature unique to C5.0 is a scheme for deriving rule sets. After a tree is grown, the splitting rules that define the terminal nodes can sometimes be simplified: that is, one or more condition can be dropped without changing the subset of observations that fall in the node. We end up with a simplified set of rules defining each terminal node; these no longer follow a tree structure, but their simplicity might make them more attractive to the user.</p>
</section>
<section id="linear-combination-splits" class="level4" data-number="12.0.0.10">
<h4 data-number="12.0.0.10" class="anchored" data-anchor-id="linear-combination-splits"><span class="header-section-number">12.0.0.10</span> Linear Combination Splits</h4>
<p>Rather than restricting splits to be of the form <span class="math inline">\(X_j \leq s\)</span> , one can allow splits along linear combinations of the form <span class="math inline">\(\sum a_j X_j \leq s\)</span> . The weights <span class="math inline">\(a_j\)</span> and split point s are optimized to minimize the relevant criterion (such as the Gini index). While this can improve the predictive power of the tree, it can hurt interpretability. Computationally, the discreteness of the split point search precludes the use of a smooth optimization for the weights. A better way to incorporate linear combination splits is in the hierarchical mixtures of experts (HME) model, the topic of Section 9.5.</p>
</section>
<section id="instability-of-trees" class="level4" data-number="12.0.0.11">
<h4 data-number="12.0.0.11" class="anchored" data-anchor-id="instability-of-trees"><span class="header-section-number">12.0.0.11</span> Instability of Trees</h4>
<p>One major problem with trees is their high variance. Often a small change in the data can result in a very different series of splits, making interpretation somewhat precarious. The major reason for this instability is the hierarchical nature of the process: the effect of an error in the top split is propagated down to all of the splits below it. One can alleviate this to some degree by trying to use a more stable split criterion, but the inherent instability is not removed. It is the price to be paid for estimating a simple, tree-based structure from the data. <em>Bagging</em> (Section 8.7) averages many trees to reduce this variance.</p>
</section>
<section id="lack-of-smoothness" class="level4" data-number="12.0.0.12">
<h4 data-number="12.0.0.12" class="anchored" data-anchor-id="lack-of-smoothness"><span class="header-section-number">12.0.0.12</span> Lack of Smoothness</h4>
<p>Another limitation of trees is the lack of smoothness of the prediction surface, as can be seen in the bottom right panel of Figure 9.2. In classification with 0/1 loss, this doesn’t hurt much, since bias in estimation of the class probabilities has a limited effect. However, this can degrade performance in the regression setting, where we would normally expect the underlying function to be smooth. The MARS procedure, described in Section 9.4,</p>
<p>TABLE 9.3. Spam data: confusion rates for the 17-node tree (chosen by cross– validation) on the test data. Overall error rate is 9.3%.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th>Predicted</th>
<th></th>
<th></th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>True</td>
<td>email</td>
<td>spam</td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>email</td>
<td>57.3%</td>
<td>4.0%</td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>spam</td>
<td>5.3%</td>
<td>33.4%</td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<p>can be viewed as a modification of CART designed to alleviate this lack of smoothness.</p>
</section>
<section id="difficulty-in-capturing-additive-structure" class="level4" data-number="12.0.0.13">
<h4 data-number="12.0.0.13" class="anchored" data-anchor-id="difficulty-in-capturing-additive-structure"><span class="header-section-number">12.0.0.13</span> Difficulty in Capturing Additive Structure</h4>
<p>Another problem with trees is their difficulty in modeling additive structure. In regression, suppose, for example, that Y = c1I(X<sup>1</sup> &lt; t1)+c2I(X<sup>2</sup> &lt; t2) + ε where ε is zero-mean noise. Then a binary tree might make its first split on X<sup>1</sup> near t1. At the next level down it would have to split both nodes on X<sup>2</sup> at t<sup>2</sup> in order to capture the additive structure. This might happen with sufficient data, but the model is given no special encouragement to find such structure. If there were ten rather than two additive effects, it would take many fortuitous splits to recreate the structure, and the data analyst would be hard pressed to recognize it in the estimated tree. The “blame” here can again be attributed to the binary tree structure, which has both advantages and drawbacks. Again the MARS method (Section 9.4) gives up this tree structure in order to capture additive structure.</p>
</section>
</section>
<section id="spam-example-continued" class="level1" data-number="13">
<h1 data-number="13"><span class="header-section-number">13</span> 9.2.5 Spam Example (Continued)</h1>
<p>We applied the classification tree methodology to the spam example introduced earlier. We used the deviance measure to grow the tree and misclassification rate to prune it. Figure 9.4 shows the 10-fold cross-validation error rate as a function of the size of the pruned tree, along with ±2 standard errors of the mean, from the ten replications. The test error curve is shown in orange. Note that the cross-validation error rates are indexed by a sequence of values of α and not tree size; for trees grown in different folds, a value of α might imply different sizes. The sizes shown at the base of the plot refer to |Tα|, the sizes of the pruned original tree.</p>
<p>The error flattens out at around 17 terminal nodes, giving the pruned tree in Figure 9.5. Of the 13 distinct features chosen by the tree, 11 overlap with the 16 significant features in the additive model (Table 9.2). The overall error rate shown in Table 9.3 is about 50% higher than for the additive model in Table 9.1.</p>
<p>Consider the rightmost branches of the tree. We branch to the right with a spam warning if more than 5.5% of the characters are the $ sign.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figures/_page_332_Figure_2.jpeg" class="img-fluid figure-img"></p>
<figcaption>Figure 9.4</figcaption>
</figure>
</div>
<p>FIGURE 9.4. Results for spam example. The blue curve is the 10-fold cross-validation estimate of misclassification rate as a function of tree size, with standard error bars. The minimum occurs at a tree size with about 17 terminal nodes (using the “one-standard-error” rule). The orange curve is the test error, which tracks the CV error quite closely. The cross-validation is indexed by values of α, shown above. The tree sizes shown below refer to |Tα|, the size of the original tree indexed by α.</p>
<p>However, if in addition the phrase hp occurs frequently, then this is likely to be company business and we classify as email. All of the 22 cases in the test set satisfying these criteria were correctly classified. If the second condition is not met, and in addition the average length of repeated capital letters CAPAVE is larger than 2.9, then we classify as spam. Of the 227 test cases, only seven were misclassified.</p>
<p>In medical classification problems, the terms sensitivity and specificity are used to characterize a rule. They are defined as follows:</p>
<p>Sensitivity: probability of predicting disease given true state is disease.</p>
<p>Specificity: probability of predicting non-disease given true state is nondisease.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figures/_page_333_Figure_2.jpeg" class="img-fluid figure-img"></p>
<figcaption>Figure 9.5</figcaption>
</figure>
</div>
<p>FIGURE 9.5. The pruned tree for the spam example. The split variables are shown in blue on the branches, and the classification is shown in every node.The numbers under the terminal nodes indicate misclassification rates on the test data.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figures/_page_334_Figure_2.jpeg" class="img-fluid figure-img"></p>
<figcaption>Figure 9.6</figcaption>
</figure>
</div>
<p>FIGURE 9.6. ROC curves for the classification rules fit to the spam data. Curves that are closer to the northeast corner represent better classifiers. In this case the GAM classifier dominates the trees. The weighted tree achieves better sensitivity for higher specificity than the unweighted tree. The numbers in the legend represent the area under the curve.</p>
<p>If we think of spam and email as the presence and absence of disease, respectively, then from Table 9.3 we have</p>
<p><span class="math display">\[\begin{array}{lcl} \textit{Sensitivity} &amp; = &amp; 100 \times \frac{33.4}{33.4 + 5.3} = 86.3\%, \\ \textit{Specificity} &amp; = &amp; 100 \times \frac{57.3}{57.3 + 4.0} = 93.4\%. \end{array}\]</span></p>
<p>In this analysis we have used equal losses. As before let <span class="math inline">\(L_{kk'}\)</span> be the loss associated with predicting a class k object as class k’. By varying the relative sizes of the losses <span class="math inline">\(L_{01}\)</span> and <span class="math inline">\(L_{10}\)</span> , we increase the sensitivity and decrease the specificity of the rule, or vice versa. In this example, we want to avoid marking good email as spam, and thus we want the specificity to be very high. We can achieve this by setting <span class="math inline">\(L_{01} &gt; 1\)</span> say, with <span class="math inline">\(L_{10} = 1\)</span> . The Bayes’ rule in each terminal node classifies to class 1 (spam) if the proportion of spam is <span class="math inline">\(\geq L_{01}/(L_{10} + L_{01})\)</span> , and class zero otherwise. The</p>
<p>receiver operating characteristic curve (ROC) is a commonly used summary for assessing the tradeoff between sensitivity and specificity. It is a plot of the sensitivity versus specificity as we vary the parameters of a classification rule. Varying the loss L<sup>01</sup> between 0.1 and 10, and applying Bayes’ rule to the 17-node tree selected in Figure 9.4, produced the ROC curve shown in Figure 9.6. The standard error of each curve near 0.9 is app p roximately 0.9(1 − 0.9)/1536 = 0.008, and hence the standard error of the difference is about 0.01. We see that in order to achieve a specificity of close to 100%, the sensitivity has to drop to about 50%. The area under the curve is a commonly used quantitative summary; extending the curve linearly in each direction so that it is defined over [0, 100], the area is approximately 0.95. For comparison, we have included the ROC curve for the GAM model fit to these data in Section 9.2; it gives a better classification rule for any loss, with an area of 0.98.</p>
<p>Rather than just modifying the Bayes rule in the nodes, it is better to take full account of the unequal losses in growing the tree, as was done in Section 9.2. With just two classes 0 and 1, losses may be incorporated into the tree-growing process by using weight Lk,1−<sup>k</sup> for an observation in class k. Here we chose L<sup>01</sup> = 5, L<sup>10</sup> = 1 and fit the same size tree as before (|Tα| = 17). This tree has higher sensitivity at high values of the specificity than the original tree, but does more poorly at the other extreme. Its top few splits are the same as the original tree, and then it departs from it. For this application the tree grown using L<sup>01</sup> = 5 is clearly better than the original tree.</p>
<p>The area under the ROC curve, used above, is sometimes called the cstatistic. Interestingly, it can be shown that the area under the ROC curve is equivalent to the Mann-Whitney U statistic (or Wilcoxon rank-sum test), for the median difference between the prediction scores in the two groups (Hanley and McNeil, 1982). For evaluating the contribution of an additional predictor when added to a standard model, the c-statistic may not be an informative measure. The new predictor can be very significant in terms of the change in model deviance, but show only a small increase in the cstatistic. For example, removal of the highly significant term george from the model of Table 9.2 results in a decrease in the c-statistic of less than 0.01. Instead, it is useful to examine how the additional predictor changes the classification on an individual sample basis. A good discussion of this point appears in Cook (2007).</p>
</section>
<section id="prim-bump-hunting" class="level1" data-number="14">
<h1 data-number="14"><span class="header-section-number">14</span> 9.3 PRIM: Bump Hunting</h1>
<p>Tree-based methods (for regression) partition the feature space into boxshaped regions, to try to make the response averages in each box as different as possible. The splitting rules defining the boxes are related to each through a binary tree, facilitating their interpretation.</p>
<p>The patient rule induction method (PRIM) also finds boxes in the feature space, but seeks boxes in which the response average is high. Hence it looks for maxima in the target function, an exercise known as bump hunting. (If minima rather than maxima are desired, one simply works with the negative response values.)</p>
<p>PRIM also differs from tree-based partitioning methods in that the box definitions are not described by a binary tree. This makes interpretation of the collection of rules more difficult; however, by removing the binary tree constraint, the individual rules are often simpler.</p>
<p>The main box construction method in PRIM works from the top down, starting with a box containing all of the data. The box is compressed along one face by a small amount, and the observations then falling outside the box are peeled off. The face chosen for compression is the one resulting in the largest box mean, after the compression is performed. Then the process is repeated, stopping when the current box contains some minimum number of data points.</p>
<p>This process is illustrated in Figure 9.7. There are 200 data points uniformly distributed over the unit square. The color-coded plot indicates the response Y taking the value 1 (red) when 0.5 &lt; X<sup>1</sup> &lt; 0.8 and 0.4 &lt; X<sup>2</sup> &lt; 0.6. and zero (blue) otherwise. The panels shows the successive boxes found by the top-down peeling procedure, peeling off a proportion α = 0.1 of the remaining data points at each stage.</p>
<p>Figure 9.8 shows the mean of the response values in the box, as the box is compressed.</p>
<p>After the top-down sequence is computed, PRIM reverses the process, expanding along any edge, if such an expansion increases the box mean. This is called pasting. Since the top-down procedure is greedy at each step, such an expansion is often possible.</p>
<p>The result of these steps is a sequence of boxes, with different numbers of observation in each box. Cross-validation, combined with the judgment of the data analyst, is used to choose the optimal box size.</p>
<p>Denote by B<sup>1</sup> the indices of the observations in the box found in step 1. The PRIM procedure then removes the observations in B<sup>1</sup> from the training set, and the two-step process—top down peeling, followed by bottom-up pasting—is repeated on the remaining dataset. This entire process is repeated several times, producing a sequence of boxes B1, B2, . . . , Bk. Each box is defined by a set of rules involving a subset of predictors like</p>
<p><span class="math display">\[(a_1 \le X_1 \le b_1)\]</span> and <span class="math inline">\((b_1 \le X_3 \le b_2)\)</span> .</p>
<p>A summary of the PRIM procedure is given Algorithm 9.3.</p>
<p>PRIM can handle a categorical predictor by considering all partitions of the predictor, as in CART. Missing values are also handled in a manner similar to CART. PRIM is designed for regression (quantitative response</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figures/_page_337_Figure_2.jpeg" class="img-fluid figure-img"></p>
<figcaption>Figure 9.7</figcaption>
</figure>
</div>
<p>FIGURE 9.7. Illustration of PRIM algorithm. There are two classes, indicated by the blue (class 0) and red (class 1) points. The procedure starts with a rectangle (broken black lines) surrounding all of the data, and then peels away points along one edge by a prespecified amount in order to maximize the mean of the points remaining in the box. Starting at the top left panel, the sequence of peelings is shown, until a pure red region is isolated in the bottom right panel. The iteration number is indicated at the top of each panel.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figures/_page_337_Figure_4.jpeg" class="img-fluid figure-img"></p>
<figcaption>Figure 9.8</figcaption>
</figure>
</div>
<p>FIGURE 9.8. Box mean as a function of number of observations in the box.</p>
<section id="algorithm-9.3-patient-rule-induction-method." class="level4" data-number="14.0.0.1">
<h4 data-number="14.0.0.1" class="anchored" data-anchor-id="algorithm-9.3-patient-rule-induction-method."><span class="header-section-number">14.0.0.1</span> Algorithm 9.3 Patient Rule Induction Method.</h4>
<ul>
<li><ol type="1">
<li>Start with all of the training data, and a maximal box containing all of the data.</li>
</ol></li>
<li><ol start="2" type="1">
<li>Consider shrinking the box by compressing one face, so as to peel off the proportion α of observations having either the highest values of a predictor X<sup>j</sup> , or the lowest. Choose the peeling that produces the highest response mean in the remaining box. (Typically α = 0.05 or 0.10.)</li>
</ol></li>
<li><ol start="3" type="1">
<li>Repeat step 2 until some minimal number of observations (say 10) remain in the box.</li>
</ol></li>
<li><ol start="4" type="1">
<li>Expand the box along any face, as long as the resulting box mean increases.</li>
</ol></li>
<li><ol start="5" type="1">
<li>Steps 1–4 give a sequence of boxes, with different numbers of observations in each box. Use cross-validation to choose a member of the sequence. Call the box B1.</li>
</ol></li>
<li><ol start="6" type="1">
<li>Remove the data in box B<sup>1</sup> from the dataset and repeat steps 2–5 to obtain a second box, and continue to get as many boxes as desired.</li>
</ol></li>
</ul>
<p>variable); a two-class outcome can be handled simply by coding it as 0 and 1. There is no simple way to deal with k &gt; 2 classes simultaneously: one approach is to run PRIM separately for each class versus a baseline class.</p>
<p>An advantage of PRIM over CART is its patience. Because of its binary splits, CART fragments the data quite quickly. Assuming splits of equal size, with N observations it can only make log<sup>2</sup> (N) − 1 splits before running out of data. If PRIM peels off a proportion α of training points at each stage, it can perform approximately − log(N)/ log(1 − α) peeling steps before running out of data. For example, if N = 128 and α = 0.10, then log<sup>2</sup> (N)−1 = 6 while − log(N)/ log(1−α) ≈ 46. Taking into account that there must be an integer number of observations at each stage, PRIM in fact can peel only 29 times. In any case, the ability of PRIM to be more patient should help the top-down greedy algorithm find a better solution.</p>
</section>
</section>
<section id="spam-example-continued-1" class="level1" data-number="15">
<h1 data-number="15"><span class="header-section-number">15</span> 9.3.1 Spam Example (Continued)</h1>
<p>We applied PRIM to the spam data, with the response coded as 1 for spam and 0 for email.</p>
<p>The first two boxes found by PRIM are summarized below:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Rule 1</th>
<th>Global Mean</th>
<th>Box Mean</th>
<th>Box Support</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Training</td>
<td>0.3931</td>
<td>0.9607</td>
<td>0.1413</td>
</tr>
<tr class="even">
<td>Test</td>
<td>0.3958</td>
<td>1.0000</td>
<td>0.1536</td>
</tr>
</tbody>
</table>
<p><span class="math display">\[\mathrm{Rule} \ 1 \left\{ \begin{array}{ll} \mathtt{ch!} &amp;&gt; 0.029 \\ \mathtt{CAPAVE} &amp;&gt; 2.331 \\ \mathtt{your} &amp;&gt; 0.705 \\ \mathtt{1999} &amp;&lt; 0.040 \\ \mathtt{CAPTOT} &amp;&gt; 79.50 \\ \mathtt{edu} &amp;&lt; 0.070 \\ \mathtt{re} &amp;&lt; 0.535 \\ \mathtt{ch;} &amp;&lt; 0.030 \end{array} \right.\]</span></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Rule 2</th>
<th>Remain Mean</th>
<th>Box Mean</th>
<th>Box Support</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Training</td>
<td>0.2998</td>
<td>0.9560</td>
<td>0.1043</td>
</tr>
<tr class="even">
<td>Test</td>
<td>0.2862</td>
<td>0.9264</td>
<td>0.1061</td>
</tr>
</tbody>
</table>
<p><span class="math display">\[Rule 2 \begin{cases} \text{remove} &gt; 0.010 \\ \text{george} &lt; 0.110 \end{cases}\]</span></p>
<p>The box support is the proportion of observations falling in the box. The first box is purely spam, and contains about 15% of the test data. The second box contains 10.6% of the test observations, 92.6% of which are spam. Together the two boxes contain 26% of the data and are about 97% spam. The next few boxes (not shown) are quite small, containing only about 3% of the data.</p>
<p>The predictors are listed in order of importance. Interestingly the top splitting variables in the CART tree (Figure 9.5) do not appear in PRIM’s first box.</p>
</section>
<section id="mars-multivariate-adaptive-regression-splines" class="level1" data-number="16">
<h1 data-number="16"><span class="header-section-number">16</span> 9.4 MARS: Multivariate Adaptive Regression Splines</h1>
<p>MARS is an adaptive procedure for regression, and is well suited for highdimensional problems (i.e., a large number of inputs). It can be viewed as a generalization of stepwise linear regression or a modification of the CART method to improve the latter’s performance in the regression setting. We introduce MARS from the first point of view, and later make the connection to CART.</p>
<p>MARS uses expansions in piecewise linear basis functions of the form (x − t)<sup>+</sup> and (t − x)+. The “+” means positive part, so</p>
<p><span class="math display">\[(x-t)_+ = \begin{cases} x-t, &amp; \text{if } x &gt; t, \\ 0, &amp; \text{otherwise,} \end{cases}\]</span> and <span class="math inline">\((t-x)_+ = \begin{cases} t-x, &amp; \text{if } x &lt; t, \\ 0, &amp; \text{otherwise.} \end{cases}\)</span></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figures/_page_340_Figure_2.jpeg" class="img-fluid figure-img"></p>
<figcaption>Figure 9.9</figcaption>
</figure>
</div>
<p><strong>FIGURE 9.9.</strong> The basis functions <span class="math inline">\((x-t)_+\)</span> (solid orange) and <span class="math inline">\((t-x)_+\)</span> (broken blue) used by MARS.</p>
<p>As an example, the functions <span class="math inline">\((x - 0.5)_+\)</span> and <span class="math inline">\((0.5 - x)_+\)</span> are shown in Figure 9.9.</p>
<p>Each function is piecewise linear, with a knot at the value t. In the terminology of Chapter 5, these are linear splines. We call the two functions a reflected pair in the discussion below. The idea is to form reflected pairs for each input <span class="math inline">\(X_j\)</span> with knots at each observed value <span class="math inline">\(x_{ij}\)</span> of that input. Therefore, the collection of basis functions is</p>
<p><span class="math display">\[C = \{ (X_j - t)_+, (t - X_j)_+ \} \underset{j = 1, 2, \dots, p}{t \in \{x_{1j}, x_{2j}, \dots, x_{Nj}\}}\]</span></p>
<p><span class="math display">\[(9.18)\]</span></p>
<p>If all of the input values are distinct, there are 2Np basis functions altogether. Note that although each basis function depends only on a single <span class="math inline">\(X_j\)</span> , for example, <span class="math inline">\(h(X) = (X_j - t)_+\)</span> , it is considered as a function over the entire input space <span class="math inline">\(\mathbb{R}^p\)</span> .</p>
<p>The model-building strategy is like a forward stepwise linear regression, but instead of using the original inputs, we are allowed to use functions from the set <span class="math inline">\(\mathcal{C}\)</span> and their products. Thus the model has the form</p>
<p><span class="math display">\[f(X) = \beta_0 + \sum_{m=1}^{M} \beta_m h_m(X), \tag{9.19}\]</span></p>
<p>where each <span class="math inline">\(h_m(X)\)</span> is a function in C, or a product of two or more such functions.</p>
<p>Given a choice for the <span class="math inline">\(h_m\)</span> , the coefficients <span class="math inline">\(\beta_m\)</span> are estimated by minimizing the residual sum-of-squares, that is, by standard linear regression. The real art, however, is in the construction of the functions <span class="math inline">\(h_m(x)\)</span> . We start with only the constant function <span class="math inline">\(h_0(X) = 1\)</span> in our model, and all functions in the set <span class="math inline">\(\mathcal{C}\)</span> are candidate functions. This is depicted in Figure 9.10.</p>
<p>At each stage we consider as a new basis function pair all products of a function <span class="math inline">\(h_m\)</span> in the model set <span class="math inline">\(\mathcal{M}\)</span> with one of the reflected pairs in <span class="math inline">\(\mathcal{C}\)</span> . We add to the model <span class="math inline">\(\mathcal{M}\)</span> the term of the form</p>
<p><span class="math display">\[\hat{\beta}_{M+1}h_{\ell}(X)\cdot(X_j-t)_+ + \hat{\beta}_{M+2}h_{\ell}(X)\cdot(t-X_j)_+, \ h_{\ell}\in\mathcal{M},\]</span></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figures/_page_341_Figure_2.jpeg" class="img-fluid figure-img"></p>
<figcaption>Figure 9.10</figcaption>
</figure>
</div>
<p>FIGURE 9.10. Schematic of the MARS forward model-building procedure. On the left are the basis functions currently in the model: initially, this is the constant function h(X) = 1. On the right are all candidate basis functions to be considered in building the model. These are pairs of piecewise linear basis functions as in Figure 9.9, with knots t at all unique observed values xij of each predictor X<sup>j</sup> . At each stage we consider all products of a candidate pair with a basis function in the model. The product that decreases the residual error the most is added into the current model. Above we illustrate the first three steps of the procedure, with the selected functions shown in red.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figures/_page_342_Figure_2.jpeg" class="img-fluid figure-img"></p>
<figcaption>Figure 9.11</figcaption>
</figure>
</div>
<p><strong>FIGURE 9.11.</strong> The function <span class="math inline">\(h(X_1, X_2) = (X_1 - x_{51})_+ \cdot (x_{72} - X_2)_+\)</span> , resulting from multiplication of two piecewise linear MARS basis functions.</p>
<p>that produces the largest decrease in training error. Here <span class="math inline">\(\hat{\beta}_{M+1}\)</span> and <span class="math inline">\(\hat{\beta}_{M+2}\)</span> are coefficients estimated by least squares, along with all the other M+1 coefficients in the model. Then the winning products are added to the model and the process is continued until the model set <span class="math inline">\(\mathcal{M}\)</span> contains some preset maximum number of terms.</p>
<p>For example, at the first stage we consider adding to the model a function of the form <span class="math inline">\(\beta_1(X_j-t)_++\beta_2(t-X_j)_+\)</span> ; <span class="math inline">\(t\in\{x_{ij}\}\)</span> , since multiplication by the constant function just produces the function itself. Suppose the best choice is <span class="math inline">\(\hat{\beta}_1(X_2-x_{72})_++\hat{\beta}_2(x_{72}-X_2)_+\)</span> . Then this pair of basis functions is added to the set <span class="math inline">\(\mathcal{M}\)</span> , and at the next stage we consider including a pair of products the form</p>
<p><span class="math display">\[h_m(X) \cdot (X_j - t)_+\]</span> and $h_m(X) (t - X_j)<em>+, t {x</em>{ij}},$</p>
<p>where for <span class="math inline">\(h_m\)</span> we have the choices</p>
<p><span class="math display">\[h_0(X) = 1,\]</span></p>
<p><span class="math inline">\(h_1(X) = (X_2 - x_{72})_+, \text{ or }\)</span><br>
<span class="math inline">\(h_2(X) = (x_{72} - X_2)_+.\)</span></p>
<p>The third choice produces functions such as <span class="math inline">\((X_1 - x_{51})_+ \cdot (x_{72} - X_2)_+\)</span> , depicted in Figure 9.11.</p>
<p>At the end of this process we have a large model of the form (9.19). This model typically overfits the data, and so a backward deletion procedure is applied. The term whose removal causes the smallest increase in residual squared error is deleted from the model at each stage, producing an estimated best model <span class="math inline">\(\hat{f}_{\lambda}\)</span> of each size (number of terms) <span class="math inline">\(\lambda\)</span> . One could use cross-validation to estimate the optimal value of <span class="math inline">\(\lambda\)</span> , but for computational</p>
<p>savings the MARS procedure instead uses generalized cross-validation. This criterion is defined as</p>
<p><span class="math display">\[GCV(\lambda) = \frac{\sum_{i=1}^{N} (y_i - \hat{f}_{\lambda}(x_i))^2}{(1 - M(\lambda)/N)^2}.\]</span> (9.20)</p>
<p>The value M(λ) is the effective number of parameters in the model: this accounts both for the number of terms in the models, plus the number of parameters used in selecting the optimal positions of the knots. Some mathematical and simulation results suggest that one should pay a price of three parameters for selecting a knot in a piecewise linear regression.</p>
<p>Thus if there are r linearly independent basis functions in the model, and K knots were selected in the forward process, the formula is M(λ) = r+cK, where c = 3. (When the model is restricted to be additive—details below a penalty of c = 2 is used). Using this, we choose the model along the backward sequence that minimizes GCV(λ).</p>
<p>Why these piecewise linear basis functions, and why this particular model strategy? A key property of the functions of Figure 9.9 is their ability to operate locally; they are zero over part of their range. When they are multiplied together, as in Figure 9.11, the result is nonzero only over the small part of the feature space where both component functions are nonzero. As a result, the regression surface is built up parsimoniously, using nonzero components locally—only where they are needed. This is important, since one should “spend” parameters carefully in high dimensions, as they can run out quickly. The use of other basis functions such as polynomials, would produce a nonzero product everywhere, and would not work as well.</p>
<p>The second important advantage of the piecewise linear basis function concerns computation. Consider the product of a function in M with each of the N reflected pairs for an input X<sup>j</sup> . This appears to require the fitting of N single-input linear regression models, each of which uses O(N) operations, making a total of O(N<sup>2</sup> ) operations. However, we can exploit the simple form of the piecewise linear function. We first fit the reflected pair with rightmost knot. As the knot is moved successively one position at a time to the left, the basis functions differ by zero over the left part of the domain, and by a constant over the right part. Hence after each such move we can update the fit in O(1) operations. This allows us to try every knot in only O(N) operations.</p>
<p>The forward modeling strategy in MARS is hierarchical, in the sense that multiway products are built up from products involving terms already in the model. For example, a four-way product can only be added to the model if one of its three-way components is already in the model. The philosophy here is that a high-order interaction will likely only exist if some of its lowerorder “footprints” exist as well. This need not be true, but is a reasonable working assumption and avoids the search over an exponentially growing space of alternatives.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figures/_page_344_Figure_2.jpeg" class="img-fluid figure-img"></p>
<figcaption>Figure 9.12</figcaption>
</figure>
</div>
<p><strong>FIGURE 9.12.</strong> Spam data: test error misclassification rate for the MARS procedure, as a function of the rank (number of independent basis functions) in the model.</p>
<p>There is one restriction put on the formation of model terms: each input can appear at most once in a product. This prevents the formation of higher-order powers of an input, which increase or decrease too sharply near the boundaries of the feature space. Such powers can be approximated in a more stable way with piecewise linear functions.</p>
<p>A useful option in the MARS procedure is to set an upper limit on the order of interaction. For example, one can set a limit of two, allowing pairwise products of piecewise linear functions, but not three- or higherway products. This can aid in the interpretation of the final model. An upper limit of one results in an additive model.</p>
<section id="spam-example-continued-2" class="level2" data-number="16.1">
<h2 data-number="16.1" class="anchored" data-anchor-id="spam-example-continued-2"><span class="header-section-number">16.1</span> 9.4.1 Spam Example (Continued)</h2>
<p>We applied MARS to the “spam” data analyzed earlier in this chapter. To enhance interpretability, we restricted MARS to second-degree interactions. Although the target is a two-class variable, we used the squared-error loss function nonetheless (see Section 9.4.3). Figure 9.12 shows the test error misclassification rate as a function of the rank (number of independent basis functions) in the model. The error rate levels off at about 5.5%, which is slightly higher than that of the generalized additive model (5.3%) discussed earlier. GCV chose a model size of 60, which is roughly the smallest model giving optimal performance. The leading interactions found by MARS involved inputs (ch$, remove), (ch$, free) and (hp, CAPTOT). However, these interactions give no improvement in performance over the generalized additive model.</p>
<section id="example-simulated-data" class="level4" data-number="16.1.0.1">
<h4 data-number="16.1.0.1" class="anchored" data-anchor-id="example-simulated-data"><span class="header-section-number">16.1.0.1</span> 9.4.2 Example (Simulated Data)</h4>
<p>Here we examine the performance of MARS in three contrasting scenarios. There are N=100 observations, and the predictors <span class="math inline">\(X_1, X_2, \ldots, X_p\)</span> and errors <span class="math inline">\(\varepsilon\)</span> have independent standard normal distributions.</p>
<p>Scenario 1: The data generation model is</p>
<p><span class="math display">\[Y = (X_1 - 1)_+ + (X_1 - 1)_+ \cdot (X_2 - .8)_+ + 0.12 \cdot \varepsilon. \tag{9.21}\]</span></p>
<p>The noise standard deviation 0.12 was chosen so that the signal-tonoise ratio was about 5. We call this the tensor-product scenario; the product term gives a surface that looks like that of Figure 9.11.</p>
<p>Scenario 2: This is the same as scenario 1, but with p = 20 total predictors; that is, there are 18 inputs that are independent of the response.</p>
<p>Scenario 3: This has the structure of a neural network:</p>
<p><span class="math display">\[\ell_1 = X_1 + X_2 + X_3 + X_4 + X_5,
\ell_2 = X_6 - X_7 + X_8 - X_9 + X_{10},
\sigma(t) = 1/(1 + e^{-t}),
Y = \sigma(\ell_1) + \sigma(\ell_2) + 0.12 \cdot \varepsilon.\]</span> (9.22)</p>
<p>Scenarios 1 and 2 are ideally suited for MARS, while scenario 3 contains high-order interactions and may be difficult for MARS to approximate. We ran five simulations from each model, and recorded the results.</p>
<p>In scenario 1, MARS typically uncovered the correct model almost perfectly. In scenario 2, it found the correct structure but also found a few extraneous terms involving other predictors.</p>
<p>Let <span class="math inline">\(\mu(x)\)</span> be the true mean of Y, and let</p>
<p><span class="math display">\[MSE_0 = ave_{x \in Test}(\bar{y} - \mu(x))^2,\]</span></p>
<p><span class="math display">\[MSE = ave_{x \in Test}(\hat{f}(x) - \mu(x))^2.\]</span> (9.23)</p>
<p>These represent the mean-square error of the constant model and the fitted MARS model, estimated by averaging at the 1000 test values of x. Table 9.4 shows the proportional decrease in model error or <span class="math inline">\(\mathbb{R}^2\)</span> for each scenario:</p>
<p><span class="math display">\[R^2 = \frac{\text{MSE}_0 - \text{MSE}}{\text{MSE}_0}.\]</span> (9.24)</p>
<p>The values shown are means and standard error over the five simulations. The performance of MARS is degraded only slightly by the inclusion of the useless inputs in scenario 2; it performs substantially worse in scenario 3.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Scenario</th>
<th>Mean (S.E.)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1: Tensor product<br>p<br>= 2</td>
<td>0.97 (0.01)</td>
</tr>
<tr class="even">
<td>2: Tensor product<br>p<br>= 20</td>
<td>0.96 (0.01)</td>
</tr>
<tr class="odd">
<td>3: Neural network</td>
<td>0.79 (0.01)</td>
</tr>
</tbody>
</table>
<p>TABLE 9.4. Proportional decrease in model error (R 2 ) when MARS is applied to three different scenarios.</p>
</section>
</section>
<section id="other-issues-1" class="level2" data-number="16.2">
<h2 data-number="16.2" class="anchored" data-anchor-id="other-issues-1"><span class="header-section-number">16.2</span> 9.4.3 Other Issues</h2>
<section id="mars-for-classification" class="level4" data-number="16.2.0.1">
<h4 data-number="16.2.0.1" class="anchored" data-anchor-id="mars-for-classification"><span class="header-section-number">16.2.0.1</span> MARS for Classification</h4>
<p>The MARS method and algorithm can be extended to handle classification problems. Several strategies have been suggested.</p>
<p>For two classes, one can code the output as 0/1 and treat the problem as a regression; we did this for the spam example. For more than two classes, one can use the indicator response approach described in Section 4.2. One codes the K response classes via 0/1 indicator variables, and then performs a multi-response MARS regression. For the latter we use a common set of basis functions for all response variables. Classification is made to the class with the largest predicted response value. There are, however, potential masking problems with this approach, as described in Section 4.2. A generally superior approach is the “optimal scoring” method discussed in Section 12.5.</p>
<p>Stone et al.&nbsp;(1997) developed a hybrid of MARS called PolyMARS specifically designed to handle classification problems. It uses the multiple logistic framework described in Section 4.4. It grows the model in a forward stagewise fashion like MARS, but at each stage uses a quadratic approximation to the multinomial log-likelihood to search for the next basis-function pair. Once found, the enlarged model is fit by maximum likelihood, and the process is repeated.</p>
</section>
<section id="relationship-of-mars-to-cart" class="level4" data-number="16.2.0.2">
<h4 data-number="16.2.0.2" class="anchored" data-anchor-id="relationship-of-mars-to-cart"><span class="header-section-number">16.2.0.2</span> Relationship of MARS to CART</h4>
<p>Although they might seem quite different, the MARS and CART strategies actually have strong similarities. Suppose we take the MARS procedure and make the following changes:</p>
<ul>
<li>Replace the piecewise linear basis functions by step functions I(x−t &gt; 0) and I(x − t ≤ 0).</li>
<li>When a model term is involved in a multiplication by a candidate term, it gets replaced by the interaction, and hence is not available for further interactions.</li>
</ul>
<p>With these changes, the MARS forward procedure is the same as the CART tree-growing algorithm. Multiplying a step function by a pair of reflected step functions is equivalent to splitting a node at the step. The second restriction implies that a node may not be split more than once, and leads to the attractive binary-tree representation of the CART model. On the other hand, it is this restriction that makes it difficult for CART to model additive structures. MARS forgoes the tree structure and gains the ability to capture additive effects.</p>
</section>
<section id="mixed-inputs" class="level4" data-number="16.2.0.3">
<h4 data-number="16.2.0.3" class="anchored" data-anchor-id="mixed-inputs"><span class="header-section-number">16.2.0.3</span> Mixed Inputs</h4>
<p>Mars can handle “mixed” predictors—quantitative and qualitative—in a natural way, much like CART does. MARS considers all possible binary partitions of the categories for a qualitative predictor into two groups. Each such partition generates a pair of piecewise constant basis functions indicator functions for the two sets of categories. This basis pair is now treated as any other, and is used in forming tensor products with other basis functions already in the model.</p>
</section>
</section>
</section>
<section id="hierarchical-mixtures-of-experts" class="level1" data-number="17">
<h1 data-number="17"><span class="header-section-number">17</span> 9.5 Hierarchical Mixtures of Experts</h1>
<p>The hierarchical mixtures of experts (HME) procedure can be viewed as a variant of tree-based methods. The main difference is that the tree splits are not hard decisions but rather soft probabilistic ones. At each node an observation goes left or right with probabilities depending on its input values. This has some computational advantages since the resulting parameter optimization problem is smooth, unlike the discrete split point search in the tree-based approach. The soft splits might also help in prediction accuracy and provide a useful alternative description of the data.</p>
<p>There are other differences between HMEs and the CART implementation of trees. In an HME, a linear (or logistic regression) model is fit in each terminal node, instead of a constant as in CART. The splits can be multiway, not just binary, and the splits are probabilistic functions of a linear combination of inputs, rather than a single input as in the standard use of CART. However, the relative merits of these choices are not clear, and most were discussed at the end of Section 9.2.</p>
<p>A simple two-level HME model in shown in Figure 9.13. It can be thought of as a tree with soft splits at each non-terminal node. However, the inventors of this methodology use a different terminology. The terminal nodes are called experts, and the non-terminal nodes are called gating networks. The idea is that each expert provides an opinion (prediction) about the response, and these are combined together by the gating networks. As we will see, the model is formally a mixture model, and the two-level model in the figure can be extend to multiple levels, hence the name hierarchical mixtures of experts.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figures/_page_348_Figure_2.jpeg" class="img-fluid figure-img"></p>
<figcaption>Figure 9.13</figcaption>
</figure>
</div>
<p>FIGURE 9.13. A two-level hierarchical mixture of experts (HME) model.</p>
<p>Consider the regression or classification problem, as described earlier in the chapter. The data is <span class="math inline">\((x_i, y_i)\)</span> , i = 1, 2, …, N, with <span class="math inline">\(y_i\)</span> either a continuous or binary-valued response, and <span class="math inline">\(x_i\)</span> a vector-valued input. For ease of notation we assume that the first element of <span class="math inline">\(x_i\)</span> is one, to account for intercepts.</p>
<p>Here is how an HME is defined. The top gating network has the output</p>
<p><span class="math display">\[g_j(x, \gamma_j) = \frac{e^{\gamma_j^T x}}{\sum_{k=1}^K e^{\gamma_k^T x}}, \ j = 1, 2, \dots, K,\]</span> (9.25)</p>
<p>where each <span class="math inline">\(\gamma_j\)</span> is a vector of unknown parameters. This represents a soft K-way split (K=2 in Figure 9.13.) Each <span class="math inline">\(g_j(x,\gamma_j)\)</span> is the probability of assigning an observation with feature vector x to the jth branch. Notice that with K=2 groups, if we take the coefficient of one of the elements of x to be <span class="math inline">\(+\infty\)</span> , then we get a logistic curve with infinite slope. In this case, the gating probabilities are either 0 or 1, corresponding to a hard split on that input.</p>
<p>At the second level, the gating networks have a similar form:</p>
<p><span class="math display">\[g_{\ell|j}(x,\gamma_{j\ell}) = \frac{e^{\gamma_{j\ell}^T x}}{\sum_{k=1}^K e^{\gamma_{jk}^T x}}, \ \ell = 1, 2, \dots, K.\]</span> (9.26)</p>
<p>This is the probability of assignment to the <span class="math inline">\(\ell\)</span> th branch, given assignment to the jth branch at the level above.</p>
<p>At each expert (terminal node), we have a model for the response variable of the form</p>
<p><span class="math display">\[Y \sim \Pr(y|x, \theta_{j\ell}).\]</span> (9.27)</p>
<p>This differs according to the problem.</p>
<p>Regression: The Gaussian linear regression model is used, with <span class="math inline">\(\theta_{j\ell} = (\beta_{j\ell}, \sigma_{j\ell}^2)\)</span> :</p>
<p><span class="math display">\[Y = \beta_{j\ell}^T x + \varepsilon \text{ and } \varepsilon \sim N(0, \sigma_{j\ell}^2).\]</span> (9.28)</p>
<p>Classification: The linear logistic regression model is used:</p>
<p><span class="math display">\[\Pr(Y = 1|x, \theta_{j\ell}) = \frac{1}{1 + e^{-\theta_{j\ell}^T x}}.\]</span> (9.29)</p>
<p>Denoting the collection of all parameters by <span class="math inline">\(\Psi = \{\gamma_j, \gamma_{j\ell}, \theta_{j\ell}\}\)</span> , the total probability that Y = y is</p>
<p><span class="math display">\[\Pr(y|x,\Psi) = \sum_{i=1}^{K} g_j(x,\gamma_j) \sum_{\ell=1}^{K} g_{\ell|j}(x,\gamma_{j\ell}) \Pr(y|x,\theta_{j\ell}). \tag{9.30}\]</span></p>
<p>This is a mixture model, with the mixture probabilities determined by the gating network models.</p>
<p>To estimate the parameters, we maximize the log-likelihood of the data, <span class="math inline">\(\sum_i \log \Pr(y_i|x_i, \Psi)\)</span> , over the parameters in <span class="math inline">\(\Psi\)</span> . The most convenient method for doing this is the EM algorithm, which we describe for mixtures in Section 8.5. We define latent variables <span class="math inline">\(\Delta_j\)</span> , all of which are zero except for a single one. We interpret these as the branching decisions made by the top level gating network. Similarly we define latent variables <span class="math inline">\(\Delta_{\ell|j}\)</span> to describe the gating decisions at the second level.</p>
<p>In the E-step, the EM algorithm computes the expectations of the <span class="math inline">\(\Delta_j\)</span> and <span class="math inline">\(\Delta_{\ell|j}\)</span> given the current values of the parameters. These expectations are then used as observation weights in the M-step of the procedure, to estimate the parameters in the expert networks. The parameters in the internal nodes are estimated by a version of multiple logistic regression. The expectations of the <span class="math inline">\(\Delta_j\)</span> or <span class="math inline">\(\Delta_{\ell|j}\)</span> are probability profiles, and these are used as the response vectors for these logistic regressions.</p>
<p>The hierarchical mixtures of experts approach is a promising competitor to CART trees. By using <em>soft splits</em> rather than hard decision rules it can capture situations where the transition from low to high response is gradual. The log-likelihood is a smooth function of the unknown weights and hence is amenable to numerical optimization. The model is similar to CART with linear combination splits, but the latter is more difficult to optimize. On</p>
<p>the other hand, to our knowledge there are no methods for finding a good tree topology for the HME model, as there are in CART. Typically one uses a fixed tree of some depth, possibly the output of the CART procedure. The emphasis in the research on HMEs has been on prediction rather than interpretation of the final model. A close cousin of the HME is the latent class model (Lin et al., 2000), which typically has only one layer; here the nodes or latent classes are interpreted as groups of subjects that show similar response behavior.</p>
</section>
<section id="missing-data" class="level1" data-number="18">
<h1 data-number="18"><span class="header-section-number">18</span> 9.6 Missing Data</h1>
<p>It is quite common to have observations with missing values for one or more input features. The usual approach is to impute (fill-in) the missing values in some way.</p>
<p>However, the first issue in dealing with the problem is determining whether the missing data mechanism has distorted the observed data. Roughly speaking, data are missing at random if the mechanism resulting in its omission is independent of its (unobserved) value. A more precise definition is given in Little and Rubin (2002). Suppose y is the response vector and X is the N × p matrix of inputs (some of which are missing). Denote by Xobs the observed entries in X and let Z = (y, X), Zobs = (y, Xobs). Finally, if R is an indicator matrix with ijth entry 1 if xij is missing and zero otherwise, then the data is said to be missing at random (MAR) if the distribution of R depends on the data Z only through Zobs:</p>
<p><span class="math display">\[Pr(\mathbf{R}|\mathbf{Z},\theta) = Pr(\mathbf{R}|\mathbf{Z}_{obs},\theta). \tag{9.31}\]</span></p>
<p>Here θ are any parameters in the distribution of R. Data are said to be missing completely at random (MCAR) if the distribution of R doesn’t depend on the observed or missing data:</p>
<p><span class="math display">\[\Pr(\mathbf{R}|\mathbf{Z},\theta) = \Pr(\mathbf{R}|\theta). \tag{9.32}\]</span></p>
<p>MCAR is a stronger assumption than MAR: most imputation methods rely on MCAR for their validity.</p>
<p>For example, if a patient’s measurement was not taken because the doctor felt he was too sick, that observation would not be MAR or MCAR. In this case the missing data mechanism causes our observed training data to give a distorted picture of the true population, and data imputation is dangerous in this instance. Often the determination of whether features are MCAR must be made from information about the data collection process. For categorical features, one way to diagnose this problem is to code “missing” as an additional class. Then we fit our model to the training data and see if class “missing” is predictive of the response.</p>
<p>Assuming the features are missing completely at random, there are a number of ways of proceeding:</p>
<ul>
<li><ol type="1">
<li>Discard observations with any missing values.</li>
</ol></li>
<li><ol start="2" type="1">
<li>Rely on the learning algorithm to deal with missing values in its training phase.</li>
</ol></li>
<li><ol start="3" type="1">
<li>Impute all missing values before training.</li>
</ol></li>
</ul>
<p>Approach (1) can be used if the relative amount of missing data is small, but otherwise should be avoided. Regarding (2), CART is one learning algorithm that deals effectively with missing values, through surrogate splits (Section 9.2.4). MARS and PRIM use similar approaches. In generalized additive modeling, all observations missing for a given input feature are omitted when the partial residuals are smoothed against that feature in the backfitting algorithm, and their fitted values are set to zero. Since the fitted curves have mean zero (when the model includes an intercept), this amounts to assigning the average fitted value to the missing observations.</p>
<p>For most learning methods, the imputation approach (3) is necessary. The simplest tactic is to impute the missing value with the mean or median of the nonmissing values for that feature. (Note that the above procedure for generalized additive models is analogous to this.)</p>
<p>If the features have at least some moderate degree of dependence, one can do better by estimating a predictive model for each feature given the other features and then imputing each missing value by its prediction from the model. In choosing the learning method for imputation of the features, one must remember that this choice is distinct from the method used for predicting y from X. Thus a flexible, adaptive method will often be preferred, even for the eventual purpose of carrying out a linear regression of y on X. In addition, if there are many missing feature values in the training set, the learning method must itself be able to deal with missing feature values. CART therefore is an ideal choice for this imputation “engine.”</p>
<p>After imputation, missing values are typically treated as if they were actually observed. This ignores the uncertainty due to the imputation, which will itself introduce additional uncertainty into estimates and predictions from the response model. One can measure this additional uncertainty by doing multiple imputations and hence creating many different training sets. The predictive model for y can be fit to each training set, and the variation across training sets can be assessed. If CART was used for the imputation engine, the multiple imputations could be done by sampling from the values in the corresponding terminal nodes.</p>
</section>
<section id="computational-considerations" class="level1" data-number="19">
<h1 data-number="19"><span class="header-section-number">19</span> 9.7 Computational Considerations</h1>
<p>With N observations and p predictors, additive model fitting requires some number mp of applications of a one-dimensional smoother or regression method. The required number of cycles m of the backfitting algorithm is usually less than 20 and often less than 10, and depends on the amount of correlation in the inputs. With cubic smoothing splines, for example, N log N operations are needed for an initial sort and N operations for the spline fit. Hence the total operations for an additive model fit is pN log N + mpN.</p>
<p>Trees require pN log N operations for an initial sort for each predictor, and typically another pN log N operations for the split computations. If the splits occurred near the edges of the predictor ranges, this number could increase to N2p.</p>
<p>MARS requires Nm<sup>2</sup> + pmN operations to add a basis function to a model with m terms already present, from a pool of p predictors. Hence to build an M-term model requires NM<sup>3</sup> + pM<sup>2</sup>N computations, which can be quite prohibitive if M is a reasonable fraction of N.</p>
<p>Each of the components of an HME are typically inexpensive to fit at each M-step: N p<sup>2</sup> for the regressions, and N p<sup>2</sup>K<sup>2</sup> for a K-class logistic regression. The EM algorithm, however, can take a long time to converge, and so sizable HME models are considered costly to fit.</p>
</section>
<section id="bibliographic-notes" class="level1" data-number="20">
<h1 data-number="20"><span class="header-section-number">20</span> Bibliographic Notes</h1>
<p>The most comprehensive source for generalized additive models is the text of that name by Hastie and Tibshirani (1990). Different applications of this work in medical problems are discussed in Hastie et al.&nbsp;(1989) and Hastie and Herman (1990), and the software implementation in Splus is described in Chambers and Hastie (1991). Green and Silverman (1994) discuss penalization and spline models in a variety of settings. Efron and Tibshirani (1991) give an exposition of modern developments in statistics (including generalized additive models), for a nonmathematical audience. Classification and regression trees date back at least as far as Morgan and Sonquist (1963). We have followed the modern approaches of Breiman et al.&nbsp;(1984) and Quinlan (1993). The PRIM method is due to Friedman and Fisher (1999), while MARS is introduced in Friedman (1991), with an additive precursor in Friedman and Silverman (1989). Hierarchical mixtures of experts were proposed in Jordan and Jacobs (1994); see also Jacobs et al.&nbsp;(1991).</p>
<section id="exercises" class="level4" data-number="20.0.0.1">
<h4 data-number="20.0.0.1" class="anchored" data-anchor-id="exercises"><span class="header-section-number">20.0.0.1</span> Exercises</h4>
<ul>
<li>Ex. 9.1 Show that a smoothing spline fit of <span class="math inline">\(y_i\)</span> to <span class="math inline">\(x_i\)</span> preserves the <em>linear</em> part of the fit. In other words, if <span class="math inline">\(y_i = \hat{y}_i + r_i\)</span> , where <span class="math inline">\(\hat{y}_i\)</span> represents the linear regression fits, and <strong>S</strong> is the smoothing matrix, then <span class="math inline">\(\mathbf{S}\mathbf{y} = \hat{\mathbf{y}} + \mathbf{S}\mathbf{r}\)</span> . Show that the same is true for local linear regression (Section 6.1.1). Hence argue that the adjustment step in the second line of (2) in Algorithm 9.1 is unnecessary.</li>
<li>Ex. 9.2 Let <strong>A</strong> be a known <span class="math inline">\(k \times k\)</span> matrix, <strong>b</strong> be a known k-vector, and <strong>z</strong> be an unknown k-vector. A Gauss–Seidel algorithm for solving the linear system of equations <span class="math inline">\(\mathbf{Az} = \mathbf{b}\)</span> works by successively solving for element <span class="math inline">\(z_j\)</span> in the jth equation, fixing all other <span class="math inline">\(z_j\)</span> ’s at their current guesses. This process is repeated for <span class="math inline">\(j = 1, 2, \ldots, k, 1, 2, \ldots, k, \ldots\)</span> , until convergence (Golub and Van Loan, 1983).
<ul>
<li><ol type="a">
<li>Consider an additive model with N observations and p terms, with the jth term to be fit by a linear smoother <span class="math inline">\(\mathbf{S}_{j}\)</span> . Consider the following system of equations:</li>
</ol></li>
</ul></li>
</ul>
<p><span class="math display">\[\begin{pmatrix}
\mathbf{I} &amp; \mathbf{S}_{1} &amp; \mathbf{S}_{1} &amp; \cdots &amp; \mathbf{S}_{1} \\
\mathbf{S}_{2} &amp; \mathbf{I} &amp; \mathbf{S}_{2} &amp; \cdots &amp; \mathbf{S}_{2} \\
\vdots &amp; \vdots &amp; \vdots &amp; \ddots &amp; \vdots \\
\mathbf{S}_{p} &amp; \mathbf{S}_{p} &amp; \mathbf{S}_{p} &amp; \cdots &amp; \mathbf{I}
\end{pmatrix}
\begin{pmatrix}
\mathbf{f}_{1} \\
\mathbf{f}_{2} \\
\vdots \\
\mathbf{f}_{p}
\end{pmatrix} =
\begin{pmatrix}
\mathbf{S}_{1}\mathbf{y} \\
\mathbf{S}_{2}\mathbf{y} \\
\vdots \\
\mathbf{S}_{p}\mathbf{y}
\end{pmatrix}.\]</span> (9.33)</p>
<p>Here each <span class="math inline">\(\mathbf{f}_j\)</span> is an N-vector of evaluations of the jth function at the data points, and <span class="math inline">\(\mathbf{y}\)</span> is an N-vector of the response values. Show that backfitting is a blockwise Gauss–Seidel algorithm for solving this system of equations.</p>
<ul>
<li><ol start="2" type="a">
<li>Let <span class="math inline">\(S_1\)</span> and <span class="math inline">\(S_2\)</span> be symmetric smoothing operators (matrices) with eigenvalues in [0,1). Consider a backfitting algorithm with response vector <span class="math inline">\(\mathbf{y}\)</span> and smoothers <span class="math inline">\(S_1, S_2\)</span> . Show that with any starting values, the algorithm converges and give a formula for the final iterates.</li>
</ol></li>
<li>Ex. 9.3 Backfitting equations. Consider a backfitting procedure with orthogonal projections, and let <span class="math inline">\(\mathbf{D}\)</span> be the overall regression matrix whose columns span <span class="math inline">\(V = \mathcal{L}_{\text{col}}(\mathbf{S}_1) \oplus \mathcal{L}_{\text{col}}(\mathbf{S}_2) \oplus \cdots \oplus \mathcal{L}_{\text{col}}(\mathbf{S}_p)\)</span> , where <span class="math inline">\(\mathcal{L}_{\text{col}}(\mathbf{S})\)</span> denotes the column space of a matrix S. Show that the estimating equations</li>
</ul>
<p><span class="math display">\[\begin{pmatrix} \mathbf{I} &amp; \mathbf{S}_1 &amp; \mathbf{S}_1 &amp; \cdots &amp; \mathbf{S}_1 \\ \mathbf{S}_2 &amp; \mathbf{I} &amp; \mathbf{S}_2 &amp; \cdots &amp; \mathbf{S}_2 \\ \vdots &amp; \vdots &amp; \vdots &amp; \ddots &amp; \vdots \\ \mathbf{S}_p &amp; \mathbf{S}_p &amp; \mathbf{S}_p &amp; \cdots &amp; \mathbf{I} \end{pmatrix} \begin{pmatrix} \mathbf{f}_1 \\ \mathbf{f}_2 \\ \vdots \\ \mathbf{f}_p \end{pmatrix} = \begin{pmatrix} \mathbf{S}_1 \mathbf{y} \\ \mathbf{S}_2 \mathbf{y} \\ \vdots \\ \mathbf{S}_p \mathbf{y} \end{pmatrix}\]</span></p>
<p>are equivalent to the least squares normal equations <span class="math inline">\(\mathbf{D}^T \mathbf{D} \beta = \mathbf{D}^T \mathbf{y}\)</span> where <span class="math inline">\(\beta\)</span> is the vector of coefficients.</p>
<p>Ex. 9.4 Suppose the same smoother S is used to estimate both terms in a two-term additive model (i.e., both variables are identical). Assume that S is symmetric with eigenvalues in [0,1). Show that the backfitting residual converges to <span class="math inline">\((I + S)^{-1}(I - S)y\)</span> , and that the residual sum of squares converges upward. Can the residual sum of squares converge upward in less structured situations? How does this fit compare to the fit with a single term fit by S? [Hint: Use the eigen-decomposition of S to help with this comparison.]</p>
<p>Ex. 9.5 Degrees of freedom of a tree. Given data <span class="math inline">\(y_i\)</span> with mean <span class="math inline">\(f(x_i)\)</span> and variance <span class="math inline">\(\sigma^2\)</span> , and a fitting operation <span class="math inline">\(\mathbf{y} \to \hat{\mathbf{y}}\)</span> , let’s define the degrees of freedom of a fit by <span class="math inline">\(\sum_i \text{cov}(y_i, \hat{y}_i)/\sigma^2\)</span> .</p>
<p>Consider a fit <span class="math inline">\(\hat{\mathbf{y}}\)</span> estimated by a regression tree, fit to a set of predictors <span class="math inline">\(X_1, X_2, \dots, X_p\)</span> .</p>
<ul>
<li><ol type="a">
<li>In terms of the number of terminal nodes m, give a rough formula for the degrees of freedom of the fit.</li>
</ol></li>
<li><ol start="2" type="a">
<li>Generate 100 observations with predictors <span class="math inline">\(X_1, X_2, ..., X_{10}\)</span> as independent standard Gaussian variates and fix these values.</li>
</ol></li>
<li><ol start="3" type="a">
<li>Generate response values also as standard Gaussian ( <span class="math inline">\(\sigma^2 = 1\)</span> ), independent of the predictors. Fit regression trees to the data of fixed size 1,5 and 10 terminal nodes and hence estimate the degrees of freedom of each fit. [Do ten simulations of the response and average the results, to get a good estimate of degrees of freedom.]</li>
</ol></li>
<li><ol start="4" type="a">
<li>Compare your estimates of degrees of freedom in (a) and (c) and discuss.</li>
</ol></li>
<li><ol start="5" type="a">
<li>If the regression tree fit were a linear operation, we could write <span class="math inline">\(\hat{\mathbf{y}} = \mathbf{S}\mathbf{y}\)</span> for some matrix <span class="math inline">\(\mathbf{S}\)</span> . Then the degrees of freedom would be <span class="math inline">\(\mathrm{tr}(\mathbf{S})\)</span> . Suggest a way to compute an approximate <span class="math inline">\(\mathbf{S}\)</span> matrix for a regression tree, compute it and compare the resulting degrees of freedom to those in (a) and (c).</li>
</ol></li>
</ul>
<p>Ex. 9.6 Consider the ozone data of Figure 6.9.</p>
<ul>
<li><ol type="a">
<li>Fit an additive model to the cube root of ozone concentration. as a function of temperature, wind speed, and radiation. Compare your results to those obtained via the trellis display in Figure 6.9.</li>
</ol></li>
<li><ol start="2" type="a">
<li>Fit trees, MARS, and PRIM to the same data, and compare the results to those found in (a) and in Figure 6.9.</li>
</ol></li>
</ul>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../chapters/08-model-inference-and-averaging.html" class="pagination-link" aria-label="Model Inference and Averaging">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Model Inference and Averaging</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../chapters/10-boosting-and-additive-trees.html" class="pagination-link" aria-label="Boosting and Additive Trees">
        <span class="nav-page-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Boosting and Additive Trees</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>