<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.35">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>11&nbsp; Neural Networks – esl</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../chapters/12-support-vector-machines-and-flexible-discriminants.html" rel="next">
<link href="../chapters/10-boosting-and-additive-trees.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-46f66b053e56abd73bb6e954d61a315b.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-5ccb035bea26c1e21f80f44cf7c27909.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/11-neural-networks.html"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Neural Networks</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">esl</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/01-introduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/02-overview-of-supervised-learning.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Overview of Supervised Learning</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/03-linear-methods-for-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Linear Methods for Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/04-linear-methods-for-classification.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Linear Methods for Classification</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/05-basis-expansions-and-regularization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Basis Expansions and Regularization</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/06-kernel-smoothing-methods.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Kernel Smoothing Methods</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/07-model-assessment-and-selection.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Model Assessment and Selection</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/08-model-inference-and-averaging.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Model Inference and Averaging</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/09-additive-models-trees-and-related-methods.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Additive Models, Trees, and Related Methods</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/10-boosting-and-additive-trees.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Boosting and Additive Trees</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/11-neural-networks.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Neural Networks</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/12-support-vector-machines-and-flexible-discriminants.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Support Vector Machines and Flexible Discriminants</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/13-prototype-methods-and-nearest-neighbors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Prototype Methods and Nearest-Neighbors</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/14-unsupervised-learning.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Unsupervised Learning</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/15-random-forests.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Random Forests</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/16-ensemble-learning.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Ensemble Learning</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/17-undirected-graphical-models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Undirected Graphical Models</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/18-high-dimensional-problems.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">High-Dimensional Problems: p ≫ N</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/19-references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">References</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/20-author-index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Author Index</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/21-index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Index</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"><span class="header-section-number">12</span> 11.1 Introduction</a></li>
  <li><a href="#projection-pursuit-regression" id="toc-projection-pursuit-regression" class="nav-link" data-scroll-target="#projection-pursuit-regression"><span class="header-section-number">13</span> 11.2 Projection Pursuit Regression</a></li>
  <li><a href="#neural-networks" id="toc-neural-networks" class="nav-link" data-scroll-target="#neural-networks"><span class="header-section-number">14</span> 11.3 Neural Networks</a></li>
  <li><a href="#fitting-neural-networks" id="toc-fitting-neural-networks" class="nav-link" data-scroll-target="#fitting-neural-networks"><span class="header-section-number">15</span> 11.4 Fitting Neural Networks</a></li>
  <li><a href="#some-issues-in-training-neural-networks" id="toc-some-issues-in-training-neural-networks" class="nav-link" data-scroll-target="#some-issues-in-training-neural-networks"><span class="header-section-number">16</span> 11.5 Some Issues in Training Neural Networks</a></li>
  <li><a href="#scaling-of-the-inputs" id="toc-scaling-of-the-inputs" class="nav-link" data-scroll-target="#scaling-of-the-inputs"><span class="header-section-number">17</span> 11.5.3 Scaling of the Inputs</a></li>
  <li><a href="#multiple-minima" id="toc-multiple-minima" class="nav-link" data-scroll-target="#multiple-minima"><span class="header-section-number">18</span> 11.5.5 Multiple Minima</a></li>
  <li><a href="#example-simulated-data" id="toc-example-simulated-data" class="nav-link" data-scroll-target="#example-simulated-data"><span class="header-section-number">19</span> 11.6 Example: Simulated Data</a></li>
  <li><a href="#example-zip-code-data" id="toc-example-zip-code-data" class="nav-link" data-scroll-target="#example-zip-code-data"><span class="header-section-number">20</span> 11.7 Example: ZIP Code Data</a></li>
  <li><a href="#discussion" id="toc-discussion" class="nav-link" data-scroll-target="#discussion"><span class="header-section-number">21</span> 11.8 Discussion</a></li>
  <li><a href="#bayesian-neural-nets-and-the-nips-2003-challenge" id="toc-bayesian-neural-nets-and-the-nips-2003-challenge" class="nav-link" data-scroll-target="#bayesian-neural-nets-and-the-nips-2003-challenge"><span class="header-section-number">22</span> 11.9 Bayesian Neural Nets and the NIPS 2003 Challenge</a></li>
  <li><a href="#computational-considerations" id="toc-computational-considerations" class="nav-link" data-scroll-target="#computational-considerations"><span class="header-section-number">23</span> 11.10 Computational Considerations</a></li>
  <li><a href="#bibliographic-notes" id="toc-bibliographic-notes" class="nav-link" data-scroll-target="#bibliographic-notes"><span class="header-section-number">24</span> Bibliographic Notes</a></li>
  <li><a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises"><span class="header-section-number">25</span> Exercises</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Neural Networks</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="introduction" class="level1" data-number="12">
<h1 data-number="12"><span class="header-section-number">12</span> 11.1 Introduction</h1>
<p>In this chapter we describe a class of learning methods that was developed separately in different fields—statistics and artificial intelligence—based on essentially identical models. The central idea is to extract linear combinations of the inputs as derived features, and then model the target as a nonlinear function of these features. The result is a powerful learning method, with widespread applications in many fields. We first discuss the projection pursuit model, which evolved in the domain of semiparametric statistics and smoothing. The rest of the chapter is devoted to neural network models.</p>
</section>
<section id="projection-pursuit-regression" class="level1" data-number="13">
<h1 data-number="13"><span class="header-section-number">13</span> 11.2 Projection Pursuit Regression</h1>
<p>As in our generic supervised learning problem, assume we have an input vector X with p components, and a target Y . Let ωm, m = 1, 2, . . . , M, be unit p-vectors of unknown parameters. The projection pursuit regression (PPR) model has the form</p>
<p><span class="math display">\[f(X) = \sum_{m=1}^{M} g_m(\omega_m^T X).\]</span> (11.1)</p>
<p>This is an additive model, but in the derived features V<sup>m</sup> = ω T <sup>m</sup>X rather than the inputs themselves. The functions g<sup>m</sup> are unspecified and are esti-</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figures/_page_408_Figure_2.jpeg" class="img-fluid figure-img"></p>
<figcaption>FIGURE 11.1. Perspective plots of two ridge functions.</figcaption>
</figure>
</div>
<p><strong>FIGURE 11.1.</strong> Perspective plots of two ridge functions. (Left:) <span class="math inline">\(g(V) = 1/[1 + \exp(-5(V - 0.5))]\)</span> , where <span class="math inline">\(V = (X_1 + X_2)/\sqrt{2}\)</span> . (Right:) <span class="math inline">\(g(V) = (V + 0.1)\sin(1/(V/3 + 0.1))\)</span> , where <span class="math inline">\(V = X_1\)</span> .</p>
<p>mated along with the directions <span class="math inline">\(\omega_m\)</span> using some flexible smoothing method (see below).</p>
<p>The function <span class="math inline">\(g_m(\omega_m^T X)\)</span> is called a ridge function in <span class="math inline">\(\mathbb{R}^p\)</span> . It varies only in the direction defined by the vector <span class="math inline">\(\omega_m\)</span> . The scalar variable <span class="math inline">\(V_m = \omega_m^T X\)</span> is the projection of X onto the unit vector <span class="math inline">\(\omega_m\)</span> , and we seek <span class="math inline">\(\omega_m\)</span> so that the model fits well, hence the name “projection pursuit.” Figure 11.1 shows some examples of ridge functions. In the example on the left <span class="math inline">\(\omega = (1/\sqrt{2})(1,1)^T\)</span> , so that the function only varies in the direction <span class="math inline">\(X_1 + X_2\)</span> . In the example on the right, <span class="math inline">\(\omega = (1,0)\)</span> .</p>
<p>The PPR model (11.1) is very general, since the operation of forming nonlinear functions of linear combinations generates a surprisingly large class of models. For example, the product <span class="math inline">\(X_1 \cdot X_2\)</span> can be written as <span class="math inline">\([(X_1 + X_2)^2 - (X_1 - X_2)^2]/4\)</span> , and higher-order products can be represented similarly.</p>
<p>In fact, if M is taken arbitrarily large, for appropriate choice of <span class="math inline">\(g_m\)</span> the PPR model can approximate any continuous function in <span class="math inline">\(\mathbb{R}^p\)</span> arbitrarily well. Such a class of models is called a universal approximator. However this generality comes at a price. Interpretation of the fitted model is usually difficult, because each input enters into the model in a complex and multifaceted way. As a result, the PPR model is most useful for prediction, and not very useful for producing an understandable model for the data. The M=1 model, known as the single index model in econometrics, is an exception. It is slightly more general than the linear regression model, and offers a similar interpretation.</p>
<p>How do we fit a PPR model, given training data <span class="math inline">\((x_i, y_i)\)</span> , i = 1, 2, …, N? We seek the approximate minimizers of the error function</p>
<p><span class="math display">\[\sum_{i=1}^{N} \left[ y_i - \sum_{m=1}^{M} g_m(\omega_m^T x_i) \right]^2\]</span> (11.2)</p>
<p>over functions <span class="math inline">\(g_m\)</span> and direction vectors <span class="math inline">\(\omega_m\)</span> , m = 1, 2, …, M. As in other smoothing problems, we need either explicitly or implicitly to impose complexity constraints on the <span class="math inline">\(g_m\)</span> , to avoid overfit solutions.</p>
<p>Consider just one term (M = 1, and drop the subscript). Given the direction vector <span class="math inline">\(\omega\)</span> , we form the derived variables <span class="math inline">\(v_i = \omega^T x_i\)</span> . Then we have a one-dimensional smoothing problem, and we can apply any scatterplot smoother, such as a smoothing spline, to obtain an estimate of g.</p>
<p>On the other hand, given g, we want to minimize (11.2) over <span class="math inline">\(\omega\)</span> . A Gauss–Newton search is convenient for this task. This is a quasi-Newton method, in which the part of the Hessian involving the second derivative of g is discarded. It can be simply derived as follows. Let <span class="math inline">\(\omega_{\rm old}\)</span> be the current estimate for <span class="math inline">\(\omega\)</span> . We write</p>
<p><span class="math display">\[g(\omega^T x_i) \approx g(\omega_{\text{old}}^T x_i) + g'(\omega_{\text{old}}^T x_i)(\omega - \omega_{\text{old}})^T x_i\]</span> (11.3)</p>
<p>to give</p>
<p><span class="math display">\[\sum_{i=1}^{N} \left[ y_i - g(\omega^T x_i) \right]^2 \approx \sum_{i=1}^{N} g'(\omega_{\text{old}}^T x_i)^2 \left[ \left( \omega_{\text{old}}^T x_i + \frac{y_i - g(\omega_{\text{old}}^T x_i)}{g'(\omega_{\text{old}}^T x_i)} \right) - \omega^T x_i \right]^2.\]</span> (11.4)</p>
<p>To minimize the right-hand side, we carry out a least squares regression with target <span class="math inline">\(\omega_{\rm old}^T x_i + (y_i - g(\omega_{\rm old}^T x_i))/g'(\omega_{\rm old}^T x_i)\)</span> on the input <span class="math inline">\(x_i\)</span> , with weights <span class="math inline">\(g'(\omega_{\rm old}^T x_i)^2\)</span> and no intercept (bias) term. This produces the updated coefficient vector <span class="math inline">\(\omega_{\rm new}\)</span> .</p>
<p>These two steps, estimation of g and <span class="math inline">\(\omega\)</span> , are iterated until convergence. With more than one term in the PPR model, the model is built in a forward stage-wise manner, adding a pair <span class="math inline">\((\omega_m, g_m)\)</span> at each stage.</p>
<p>There are a number of implementation details.</p>
<ul>
<li>Although any smoothing method can in principle be used, it is convenient if the method provides derivatives. Local regression and smoothing splines are convenient.</li>
<li>After each step the <span class="math inline">\(g_m\)</span> ’s from previous steps can be readjusted using the backfitting procedure described in Chapter 9. While this may lead ultimately to fewer terms, it is not clear whether it improves prediction performance.</li>
<li>Usually the <span class="math inline">\(\omega_m\)</span> are not readjusted (partly to avoid excessive computation), although in principle they could be as well.</li>
<li>The number of terms M is usually estimated as part of the forward stage-wise strategy. The model building stops when the next term does not appreciably improve the fit of the model. Cross-validation can also be used to determine M.</li>
</ul>
<p>There are many other applications, such as density estimation (Friedman et al., 1984; Friedman, 1987), where the projection pursuit idea can be used. In particular, see the discussion of ICA in Section 14.7 and its relationship with exploratory projection pursuit. However the projection pursuit regression model has not been widely used in the field of statistics, perhaps because at the time of its introduction (1981), its computational demands exceeded the capabilities of most readily available computers. But it does represent an important intellectual advance, one that has blossomed in its reincarnation in the field of neural networks, the topic of the rest of this chapter.</p>
</section>
<section id="neural-networks" class="level1" data-number="14">
<h1 data-number="14"><span class="header-section-number">14</span> 11.3 Neural Networks</h1>
<p>The term neural network has evolved to encompass a large class of models and learning methods. Here we describe the most widely used “vanilla” neural net, sometimes called the single hidden layer back-propagation network, or single layer perceptron. There has been a great deal of hype surrounding neural networks, making them seem magical and mysterious. As we make clear in this section, they are just nonlinear statistical models, much like the projection pursuit regression model discussed above.</p>
<p>A neural network is a two-stage regression or classification model, typically represented by a network diagram as in Figure 11.2. This network applies both to regression or classification. For regression, typically K = 1 and there is only one output unit Y<sup>1</sup> at the top. However, these networks can handle multiple quantitative responses in a seamless fashion, so we will deal with the general case.</p>
<p>For K-class classification, there are K units at the top, with the kth unit modeling the probability of class k. There are K target measurements Yk, k = 1, . . . , K, each being coded as a 0 − 1 variable for the kth class.</p>
<p>Derived features Z<sup>m</sup> are created from linear combinations of the inputs, and then the target Y<sup>k</sup> is modeled as a function of linear combinations of the Zm,</p>
<p><span class="math display">\[Z_{m} = \sigma(\alpha_{0m} + \alpha_{m}^{T}X), \ m = 1, \dots, M,\]</span></p>
<p><span class="math display">\[T_{k} = \beta_{0k} + \beta_{k}^{T}Z, \ k = 1, \dots, K,\]</span></p>
<p><span class="math display">\[f_{k}(X) = g_{k}(T), \ k = 1, \dots, K,\]</span> (11.5)</p>
<p>where Z = (Z1, Z2, . . . , ZM), and T = (T1, T2, . . . , TK).</p>
<p>The activation function σ(v) is usually chosen to be the sigmoid σ(v) = 1/(1 + e −v ); see Figure 11.3 for a plot of 1/(1 + e −v ). Sometimes Gaussian radial basis functions (Chapter 6) are used for the σ(v), producing what is known as a radial basis function network.</p>
<p>Neural network diagrams like Figure 11.2 are sometimes drawn with an additional bias unit feeding into every unit in the hidden and output layers.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figures/_page_411_Picture_2.jpeg" class="img-fluid figure-img"></p>
<figcaption>FIGURE 11.2. Schematic of a single hidden layer, feed-forward neural network.</figcaption>
</figure>
</div>
<p>FIGURE 11.2. Schematic of a single hidden layer, feed-forward neural network.</p>
<p>Thinking of the constant “1” as an additional input feature, this bias unit captures the intercepts <span class="math inline">\(\alpha_{0m}\)</span> and <span class="math inline">\(\beta_{0k}\)</span> in model (11.5).</p>
<p>The output function <span class="math inline">\(g_k(T)\)</span> allows a final transformation of the vector of outputs T. For regression we typically choose the identity function <span class="math inline">\(g_k(T) = T_k\)</span> . Early work in K-class classification also used the identity function, but this was later abandoned in favor of the <em>softmax</em> function</p>
<p><span class="math display">\[g_k(T) = \frac{e^{T_k}}{\sum_{\ell=1}^K e^{T_\ell}}.\]</span> (11.6)</p>
<p>This is of course exactly the transformation used in the multilogit model (Section 4.4), and produces positive estimates that sum to one. In Section 4.2 we discuss other problems with linear activation functions, in particular potentially severe masking effects.</p>
<p>The units in the middle of the network, computing the derived features <span class="math inline">\(Z_m\)</span> , are called <em>hidden units</em> because the values <span class="math inline">\(Z_m\)</span> are not directly observed. In general there can be more than one hidden layer, as illustrated in the example at the end of this chapter. We can think of the <span class="math inline">\(Z_m\)</span> as a basis expansion of the original inputs X; the neural network is then a standard linear model, or linear multilogit model, using these transformations as inputs. There is, however, an important enhancement over the basis-expansion techniques discussed in Chapter 5; here the parameters of the basis functions are learned from the data.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figures/_page_412_Figure_2.jpeg" class="img-fluid figure-img"></p>
<figcaption>FIGURE 11.3. Plot of the sigmoid function σ(v) = 1/(1+exp(−v)) (red curve).</figcaption>
</figure>
</div>
<p>FIGURE 11.3. Plot of the sigmoid function σ(v) = 1/(1+exp(−v)) (red curve), commonly used in the hidden layer of a neural network. Included are σ(sv) for s = 1 2 (blue curve) and s = 10 (purple curve). The scale parameter s controls the activation rate, and we can see that large s amounts to a hard activation at v = 0. Note that σ(s(v − v0)) shifts the activation threshold from 0 to v0.</p>
<p>Notice that if σ is the identity function, then the entire model collapses to a linear model in the inputs. Hence a neural network can be thought of as a nonlinear generalization of the linear model, both for regression and classification. By introducing the nonlinear transformation σ, it greatly enlarges the class of linear models. In Figure 11.3 we see that the rate of activation of the sigmoid depends on the norm of αm, and if kαmk is very small, the unit will indeed be operating in the linear part of its activation function.</p>
<p>Notice also that the neural network model with one hidden layer has exactly the same form as the projection pursuit model described above. The difference is that the PPR model uses nonparametric functions gm(v), while the neural network uses a far simpler function based on σ(v), with three free parameters in its argument. In detail, viewing the neural network model as a PPR model, we identify</p>
<p><span class="math display">\[g_m(\omega_m^T X) = \beta_m \sigma(\alpha_{0m} + \alpha_m^T X)\]</span></p>
<p>= <span class="math inline">\(\beta_m \sigma(\alpha_{0m} + ||\alpha_m||(\omega_m^T X)),\)</span> (11.7)</p>
<p>where ω<sup>m</sup> = αm/kαmk is the mth unit-vector. Since σβ,α0,s(v) = βσ(α<sup>0</sup> + sv) has lower complexity than a more general nonparametric g(v), it is not surprising that a neural network might use 20 or 100 such functions, while the PPR model typically uses fewer terms (M = 5 or 10, for example).</p>
<p>Finally, we note that the name “neural networks” derives from the fact that they were first developed as models for the human brain. Each unit represents a neuron, and the connections (links in Figure 11.2) represent synapses. In early models, the neurons fired when the total signal passed to that unit exceeded a certain threshold. In the model above, this corresponds to use of a step function for σ(Z) and gm(T). Later the neural network was recognized as a useful tool for nonlinear statistical modeling, and for this purpose the step function is not smooth enough for optimization. Hence the step function was replaced by a smoother threshold function, the sigmoid in Figure 11.3.</p>
</section>
<section id="fitting-neural-networks" class="level1" data-number="15">
<h1 data-number="15"><span class="header-section-number">15</span> 11.4 Fitting Neural Networks</h1>
<p>The neural network model has unknown parameters, often called weights, and we seek values for them that make the model fit the training data well. We denote the complete set of weights by θ, which consists of</p>
<p><span class="math display">\[\{\alpha_{0m}, \alpha_m; \ m = 1, 2, \dots, M\} \ M(p+1) \text{ weights},\]</span></p>
<p><span class="math inline">\(\{\beta_{0k}, \beta_k; \ k = 1, 2, \dots, K\} \ K(M+1) \text{ weights}.\)</span> (11.8)</p>
<p>For regression, we use sum-of-squared errors as our measure of fit (error function)</p>
<p><span class="math display">\[R(\theta) = \sum_{k=1}^{K} \sum_{i=1}^{N} (y_{ik} - f_k(x_i))^2.\]</span> (11.9)</p>
<p>For classification we use either squared error or cross-entropy (deviance):</p>
<p><span class="math display">\[R(\theta) = -\sum_{i=1}^{N} \sum_{k=1}^{K} y_{ik} \log f_k(x_i), \qquad (11.10)\]</span></p>
<p>and the corresponding classifier is G(x) = argmax<sup>k</sup> fk(x). With the softmax activation function and the cross-entropy error function, the neural network model is exactly a linear logistic regression model in the hidden units, and all the parameters are estimated by maximum likelihood.</p>
<p>Typically we don’t want the global minimizer of R(θ), as this is likely to be an overfit solution. Instead some regularization is needed: this is achieved directly through a penalty term, or indirectly by early stopping. Details are given in the next section.</p>
<p>The generic approach to minimizing R(θ) is by gradient descent, called back-propagation in this setting. Because of the compositional form of the model, the gradient can be easily derived using the chain rule for differentiation. This can be computed by a forward and backward sweep over the network, keeping track only of quantities local to each unit.</p>
<p>Here is back-propagation in detail for squared error loss. Let <span class="math inline">\(z_{mi} = \sigma(\alpha_{0m} + \alpha_m^T x_i)\)</span> , from (11.5) and let <span class="math inline">\(z_i = (z_{1i}, z_{2i}, \dots, z_{Mi})\)</span> . Then we have</p>
<p><span class="math display">\[R(\theta) \equiv \sum_{i=1}^{N} R_{i}\]</span></p>
<p><span class="math display">\[= \sum_{i=1}^{N} \sum_{k=1}^{K} (y_{ik} - f_{k}(x_{i}))^{2}, \qquad (11.11)\]</span></p>
<p>with derivatives</p>
<p><span class="math display">\[\frac{\partial R_i}{\partial \beta_{km}} = -2(y_{ik} - f_k(x_i))g_k'(\beta_k^T z_i)z_{mi},\]</span></p>
<p><span class="math display">\[\frac{\partial R_i}{\partial \alpha_{m\ell}} = -\sum_{k=1}^K 2(y_{ik} - f_k(x_i))g_k'(\beta_k^T z_i)\beta_{km}\sigma'(\alpha_m^T x_i)x_{i\ell}.\]</span> (11.12)</p>
<p>Given these derivatives, a gradient descent update at the (r+1)st iteration has the form</p>
<p><span class="math display">\[\beta_{km}^{(r+1)} = \beta_{km}^{(r)} - \gamma_r \sum_{i=1}^{N} \frac{\partial R_i}{\partial \beta_{km}^{(r)}},\]</span></p>
<p><span class="math display">\[\alpha_{m\ell}^{(r+1)} = \alpha_{m\ell}^{(r)} - \gamma_r \sum_{i=1}^{N} \frac{\partial R_i}{\partial \alpha_{m\ell}^{(r)}},\]</span> (11.13)</p>
<p>where <span class="math inline">\(\gamma_r\)</span> is the <em>learning rate</em>, discussed below.</p>
<p>Now write (11.12) as</p>
<p><span class="math display">\[\frac{\partial R_i}{\partial \beta_{km}} = \delta_{ki} z_{mi},
\frac{\partial R_i}{\partial \alpha_{m\ell}} = s_{mi} x_{i\ell}.\]</span> (11.14)</p>
<p>The quantities <span class="math inline">\(\delta_{ki}\)</span> and <span class="math inline">\(s_{mi}\)</span> are “errors” from the current model at the output and hidden layer units, respectively. From their definitions, these errors satisfy</p>
<p><span class="math display">\[s_{mi} = \sigma'(\alpha_m^T x_i) \sum_{k=1}^K \beta_{km} \delta_{ki}, \qquad (11.15)\]</span></p>
<p>known as the back-propagation equations. Using this, the updates in (11.13) can be implemented with a two-pass algorithm. In the forward pass, the current weights are fixed and the predicted values <span class="math inline">\(\hat{f}_k(x_i)\)</span> are computed from formula (11.5). In the backward pass, the errors <span class="math inline">\(\delta_{ki}\)</span> are computed, and then back-propagated via (11.15) to give the errors <span class="math inline">\(s_{mi}\)</span> . Both sets of errors are then used to compute the gradients for the updates in (11.13), via (11.14).</p>
<p>This two-pass procedure is what is known as back-propagation. It has also been called the <em>delta rule</em> (Widrow and Hoff, 1960). The computational components for cross-entropy have the same form as those for the sum of squares error function, and are derived in Exercise 11.3.</p>
<p>The advantages of back-propagation are its simple, local nature. In the back propagation algorithm, each hidden unit passes and receives information only to and from units that share a connection. Hence it can be implemented efficiently on a parallel architecture computer.</p>
<p>The updates in (11.13) are a kind of batch learning, with the parameter updates being a sum over all of the training cases. Learning can also be carried out online—processing each observation one at a time, updating the gradient after each training case, and cycling through the training cases many times. In this case, the sums in equations (11.13) are replaced by a single summand. A training epoch refers to one sweep through the entire training set. Online training allows the network to handle very large training sets, and also to update the weights as new observations come in.</p>
<p>The learning rate <span class="math inline">\(\gamma_r\)</span> for batch learning is usually taken to be a constant, and can also be optimized by a line search that minimizes the error function at each update. With online learning <span class="math inline">\(\gamma_r\)</span> should decrease to zero as the iteration <span class="math inline">\(r \to \infty\)</span> . This learning is a form of stochastic approximation (Robbins and Munro, 1951); results in this field ensure convergence if <span class="math inline">\(\gamma_r \to 0\)</span> , <span class="math inline">\(\sum_r \gamma_r = \infty\)</span> , and <span class="math inline">\(\sum_r \gamma_r^2 &lt; \infty\)</span> (satisfied, for example, by <span class="math inline">\(\gamma_r = 1/r\)</span> ). Back-propagation can be very slow, and for that reason is usually not</p>
<p>Back-propagation can be very slow, and for that reason is usually not the method of choice. Second-order techniques such as Newton’s method are not attractive here, because the second derivative matrix of R (the Hessian) can be very large. Better approaches to fitting include conjugate gradients and variable metric methods. These avoid explicit computation of the second derivative matrix while still providing faster convergence.</p>
</section>
<section id="some-issues-in-training-neural-networks" class="level1" data-number="16">
<h1 data-number="16"><span class="header-section-number">16</span> 11.5 Some Issues in Training Neural Networks</h1>
<p>There is quite an art in training neural networks. The model is generally overparametrized, and the optimization problem is nonconvex and unstable unless certain guidelines are followed. In this section we summarize some of the important issues.</p>
<section id="starting-values" class="level4" data-number="16.0.0.1">
<h4 data-number="16.0.0.1" class="anchored" data-anchor-id="starting-values"><span class="header-section-number">16.0.0.1</span> 11.5.1 Starting Values</h4>
<p>Note that if the weights are near zero, then the operative part of the sigmoid (Figure 11.3) is roughly linear, and hence the neural network collapses into an approximately linear model (Exercise 11.2). Usually starting values for weights are chosen to be random values near zero. Hence the model starts out nearly linear, and becomes nonlinear as the weights increase. Individual</p>
<p>units localize to directions and introduce nonlinearities where needed. Use of exact zero weights leads to zero derivatives and perfect symmetry, and the algorithm never moves. Starting instead with large weights often leads to poor solutions.</p>
</section>
<section id="overfitting" class="level4" data-number="16.0.0.2">
<h4 data-number="16.0.0.2" class="anchored" data-anchor-id="overfitting"><span class="header-section-number">16.0.0.2</span> 11.5.2 Overfitting</h4>
<p>Often neural networks have too many weights and will overfit the data at the global minimum of R. In early developments of neural networks, either by design or by accident, an early stopping rule was used to avoid overfitting. Here we train the model only for a while, and stop well before we approach the global minimum. Since the weights start at a highly regularized (linear) solution, this has the effect of shrinking the final model toward a linear model. A validation dataset is useful for determining when to stop, since we expect the validation error to start increasing.</p>
<p>A more explicit method for regularization is weight decay, which is analogous to ridge regression used for linear models (Section 3.4.1). We add a penalty to the error function R(θ) + λJ(θ), where</p>
<p><span class="math display">\[J(\theta) = \sum_{k,m} \beta_{km}^2 + \sum_{m,\ell} \alpha_{m\ell}^2\]</span> (11.16)</p>
<p>and λ ≥ 0 is a tuning parameter. Larger values of λ will tend to shrink the weights toward zero: typically cross-validation is used to estimate λ. The effect of the penalty is to simply add terms 2βkm and 2αmℓ to the respective gradient expressions (11.13). Other forms for the penalty have been proposed, for example,</p>
<p><span class="math display">\[J(\theta) = \sum_{k,m} \frac{\beta_{km}^2}{1 + \beta_{km}^2} + \sum_{m,\ell} \frac{\alpha_{m\ell}^2}{1 + \alpha_{m\ell}^2},\]</span> (11.17)</p>
<p>known as the weight elimination penalty. This has the effect of shrinking smaller weights more than (11.16) does.</p>
<p>Figure 11.4 shows the result of training a neural network with ten hidden units, without weight decay (upper panel) and with weight decay (lower panel), to the mixture example of Chapter 2. Weight decay has clearly improved the prediction. Figure 11.5 shows heat maps of the estimated weights from the training (grayscale versions of these are called Hinton diagrams.) We see that weight decay has dampened the weights in both layers: the resulting weights are spread fairly evenly over the ten hidden units.</p>
</section>
</section>
<section id="scaling-of-the-inputs" class="level1" data-number="17">
<h1 data-number="17"><span class="header-section-number">17</span> 11.5.3 Scaling of the Inputs</h1>
<p>Since the scaling of the inputs determines the effective scaling of the weights in the bottom layer, it can have a large effect on the quality of the final</p>
<section id="neural-network---10-units-no-weight-decay" class="level4" data-number="17.0.0.1">
<h4 data-number="17.0.0.1" class="anchored" data-anchor-id="neural-network---10-units-no-weight-decay"><span class="header-section-number">17.0.0.1</span> Neural Network - 10 Units, No Weight Decay</h4>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figures/_page_417_Figure_3.jpeg" class="img-fluid figure-img"></p>
<figcaption>Neural Network - 10 Units, No Weight Decay</figcaption>
</figure>
</div>
</section>
<section id="neural-network---10-units-weight-decay0.02" class="level4" data-number="17.0.0.2">
<h4 data-number="17.0.0.2" class="anchored" data-anchor-id="neural-network---10-units-weight-decay0.02"><span class="header-section-number">17.0.0.2</span> Neural Network - 10 Units, Weight Decay=0.02</h4>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figures/_page_417_Figure_5.jpeg" class="img-fluid figure-img"></p>
<figcaption>Neural Network - 10 Units, Weight Decay=0.02</figcaption>
</figure>
</div>
<p><strong>FIGURE 11.4.</strong> A neural network on the mixture example of Chapter 2. The upper panel uses no weight decay, and overfits the training data. The lower panel uses weight decay, and achieves close to the Bayes error rate (broken purple boundary). Both use the softmax activation function and cross-entropy error.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figures/_page_418_Figure_2.jpeg" class="img-fluid figure-img"></p>
<figcaption>FIGURE 11.5. Heat maps of the estimated weights from the training of neural networks from Figure 11.4.</figcaption>
</figure>
</div>
<p>FIGURE 11.5. Heat maps of the estimated weights from the training of neural networks from Figure 11.4. The display ranges from bright green (negative) to bright red (positive).</p>
<p>solution. At the outset it is best to standardize all inputs to have mean zero and standard deviation one. This ensures all inputs are treated equally in the regularization process, and allows one to choose a meaningful range for the random starting weights. With standardized inputs, it is typical to take random uniform weights over the range [−0.7, +0.7].</p>
</section>
<section id="number-of-hidden-units-and-layers" class="level4" data-number="17.0.0.3">
<h4 data-number="17.0.0.3" class="anchored" data-anchor-id="number-of-hidden-units-and-layers"><span class="header-section-number">17.0.0.3</span> 11.5.4 Number of Hidden Units and Layers</h4>
<p>Generally speaking it is better to have too many hidden units than too few. With too few hidden units, the model might not have enough flexibility to capture the nonlinearities in the data; with too many hidden units, the extra weights can be shrunk toward zero if appropriate regularization is used. Typically the number of hidden units is somewhere in the range of 5 to 100, with the number increasing with the number of inputs and number of training cases. It is most common to put down a reasonably large number of units and train them with regularization. Some researchers use cross-validation to estimate the optimal number, but this seems unnecessary if cross-validation is used to estimate the regularization parameter. Choice of the number of hidden layers is guided by background knowledge and experimentation. Each layer extracts features of the input for regression or classification. Use of multiple hidden layers allows construction of hierarchical features at different levels of resolution. An example of the effective use of multiple layers is given in Section 11.6.</p>
</section>
</section>
<section id="multiple-minima" class="level1" data-number="18">
<h1 data-number="18"><span class="header-section-number">18</span> 11.5.5 Multiple Minima</h1>
<p>The error function R(θ) is nonconvex, possessing many local minima. As a result, the final solution obtained is quite dependent on the choice of starting weights. One must at least try a number of random starting configurations, and choose the solution giving lowest (penalized) error. Probably a better approach is to use the average predictions over the collection of networks as the final prediction (Ripley, 1996). This is preferable to averaging the weights, since the nonlinearity of the model implies that this averaged solution could be quite poor. Another approach is via <em>bagging</em>, which averages the predictions of networks training from randomly perturbed versions of the training data. This is described in Section 8.7.</p>
</section>
<section id="example-simulated-data" class="level1" data-number="19">
<h1 data-number="19"><span class="header-section-number">19</span> 11.6 Example: Simulated Data</h1>
<p>We generated data from two additive error models <span class="math inline">\(Y = f(X) + \varepsilon\)</span> :</p>
<p>Sum of sigmoids: <span class="math display">\[Y = \sigma(a_1^T X) + \sigma(a_2^T X) + \varepsilon_1;\]</span></p>
<p>Radial: <span class="math inline">\(Y = \prod_{m=1}^{10} \phi(X_m) + \varepsilon_2.\)</span></p>
<p>Here <span class="math inline">\(X^T = (X_1, X_2, \dots, X_p)\)</span> , each <span class="math inline">\(X_j\)</span> being a standard Gaussian variate, with p = 2 in the first model, and p = 10 in the second.</p>
<p>For the sigmoid model, <span class="math inline">\(a_1=(3,3)\)</span> , <span class="math inline">\(a_2=(3,-3)\)</span> ; for the radial model, <span class="math inline">\(\phi(t)=(1/2\pi)^{1/2}\exp(-t^2/2)\)</span> . Both <span class="math inline">\(\varepsilon_1\)</span> and <span class="math inline">\(\varepsilon_2\)</span> are Gaussian errors, with variance chosen so that the signal-to-noise ratio</p>
<p><span class="math display">\[\frac{\operatorname{Var}(\operatorname{E}(Y|X))}{\operatorname{Var}(Y - \operatorname{E}(Y|X))} = \frac{\operatorname{Var}(f(X))}{\operatorname{Var}(\varepsilon)}\]</span> (11.18)</p>
<p>is 4 in both models. We took a training sample of size 100 and a test sample of size 10,000. We fit neural networks with weight decay and various numbers of hidden units, and recorded the average test error <span class="math inline">\(E_{\text{Test}}(Y - f(X))^2\)</span> for each of 10 random starting weights. Only one training set was generated, but the results are typical for an “average” training set. The test errors are shown in Figure 11.6. Note that the zero hidden unit model refers to linear least squares regression. The neural network is perfectly suited to the sum of sigmoids model, and the two-unit model does perform the best, achieving an error close to the Bayes rate. (Recall that the Bayes rate for regression with squared error is the error variance; in the figures, we report test error relative to the Bayes error). Notice, however, that with more hidden units, overfitting quickly creeps in, and with some starting weights the model does worse than the linear model (zero hidden unit) model. Even with two hidden units, two of the ten starting weight configurations produced results no better than the linear model, confirming the importance of multiple starting values.</p>
<p>A radial function is in a sense the most difficult for the neural net, as it is spherically symmetric and with no preferred directions. We see in the right</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figures/_page_420_Figure_2.jpeg" class="img-fluid figure-img"></p>
<figcaption>FIGURE 11.6. Boxplots of test error, for simulated data example.</figcaption>
</figure>
</div>
<p>FIGURE 11.6. Boxplots of test error, for simulated data example, relative to the Bayes error (broken horizontal line). True function is a sum of two sigmoids on the left, and a radial function is on the right. The test error is displayed for 10 different starting weights, for a single hidden layer neural network with the number of units as indicated.</p>
<p>panel of Figure 11.6 that it does poorly in this case, with the test error staying well above the Bayes error (note the different vertical scale from the left panel). In fact, since a constant fit (such as the sample average) achieves a relative error of 5 (when the SNR is 4), we see that the neural networks perform increasingly worse than the mean.</p>
<p>In this example we used a fixed weight decay parameter of 0.0005, representing a mild amount of regularization. The results in the left panel of Figure 11.6 suggest that more regularization is needed with greater numbers of hidden units.</p>
<p>In Figure 11.7 we repeated the experiment for the sum of sigmoids model, with no weight decay in the left panel, and stronger weight decay (λ = 0.1) in the right panel. With no weight decay, overfitting becomes even more severe for larger numbers of hidden units. The weight decay value λ = 0.1 produces good results for all numbers of hidden units, and there does not appear to be overfitting as the number of units increase. Finally, Figure 11.8 shows the test error for a ten hidden unit network, varying the weight decay parameter over a wide range. The value 0.1 is approximately optimal.</p>
<p>In summary, there are two free parameters to select: the weight decay λ and number of hidden units M. As a learning strategy, one could fix either parameter at the value corresponding to the least constrained model, to ensure that the model is rich enough, and use cross-validation to choose the other parameter. Here the least constrained values are zero weight decay and ten hidden units. Comparing the left panel of Figure 11.7 to Figure 11.8, we see that the test error is less sensitive to the value of the weight</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figures/_page_421_Figure_2.jpeg" class="img-fluid figure-img"></p>
<figcaption>FIGURE 11.7. Boxplots of test error, for simulated data example.</figcaption>
</figure>
</div>
<p>FIGURE 11.7. Boxplots of test error, for simulated data example, relative to the Bayes error. True function is a sum of two sigmoids. The test error is displayed for ten different starting weights, for a single hidden layer neural network with the number units as indicated. The two panels represent no weight decay (left) and strong weight decay λ = 0.1 (right).</p>
<section id="sum-of-sigmoids-10-hidden-unit-model" class="level4" data-number="19.0.0.1">
<h4 data-number="19.0.0.1" class="anchored" data-anchor-id="sum-of-sigmoids-10-hidden-unit-model"><span class="header-section-number">19.0.0.1</span> Sum of Sigmoids, 10 Hidden Unit Model</h4>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figures/_page_421_Figure_5.jpeg" class="img-fluid figure-img"></p>
<figcaption>FIGURE 11.8. Boxplots of test error, for simulated data example.</figcaption>
</figure>
</div>
<p>FIGURE 11.8. Boxplots of test error, for simulated data example. True function is a sum of two sigmoids. The test error is displayed for ten different starting weights, for a single hidden layer neural network with ten hidden units and weight decay parameter value as indicated.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figures/_page_422_Figure_2.jpeg" class="img-fluid figure-img"></p>
<figcaption>FIGURE 11.9. Examples of training cases from ZIP code data.</figcaption>
</figure>
</div>
<p>FIGURE 11.9. Examples of training cases from ZIP code data. Each image is a 16 × 16 8-bit grayscale representation of a handwritten digit.</p>
<p>decay parameter, and hence cross-validation of this parameter would be preferred.</p>
</section>
</section>
<section id="example-zip-code-data" class="level1" data-number="20">
<h1 data-number="20"><span class="header-section-number">20</span> 11.7 Example: ZIP Code Data</h1>
<p>This example is a character recognition task: classification of handwritten numerals. This problem captured the attention of the machine learning and neural network community for many years, and has remained a benchmark problem in the field. Figure 11.9 shows some examples of normalized handwritten digits, automatically scanned from envelopes by the U.S. Postal Service. The original scanned digits are binary and of different sizes and orientations; the images shown here have been deslanted and size normalized, resulting in 16 × 16 grayscale images (Le Cun et al., 1990). These 256 pixel values are used as inputs to the neural network classifier.</p>
<p>A black box neural network is not ideally suited to this pattern recognition task, partly because the pixel representation of the images lack certain invariances (such as small rotations of the image). Consequently early attempts with neural networks yielded misclassification rates around 4.5% on various examples of the problem. In this section we show some of the pioneering efforts to handcraft the neural network to overcome some these deficiencies (Le Cun, 1989), which ultimately led to the state of the art in neural network performance(Le Cun et al., 1998)<sup>1</sup> .</p>
<p>Although current digit datasets have tens of thousands of training and test examples, the sample size here is deliberately modest in order to em-</p>
<p><sup>1</sup>The figures and tables in this example were recreated from Le Cun (1989).</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figures/_page_423_Picture_2.jpeg" class="img-fluid figure-img"></p>
<figcaption>FIGURE 11.10. Architecture of the five networks used in the ZIP code example.</figcaption>
</figure>
</div>
<p>FIGURE 11.10. Architecture of the five networks used in the ZIP code example.</p>
<p>phasize the effects. The examples were obtained by scanning some actual hand-drawn digits, and then generating additional images by random horizontal shifts. Details may be found in Le Cun (1989). There are 320 digits in the training set, and 160 in the test set.</p>
<p>Five different networks were fit to the data:</p>
<p>Net-1: No hidden layer, equivalent to multinomial logistic regression.</p>
<p>Net-2: One hidden layer, 12 hidden units fully connected.</p>
<p>Net-3: Two hidden layers locally connected.</p>
<p>Net-4: Two hidden layers, locally connected with weight sharing.</p>
<p>Net-5: Two hidden layers, locally connected, two levels of weight sharing.</p>
<p>These are depicted in Figure 11.10. Net-1 for example has 256 inputs, one each for the 16×16 input pixels, and ten output units for each of the digits 0–9. The predicted value ˆfk(x) represents the estimated probability that an image x has digit class k, for k = 0, 1, 2, . . . , 9.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figures/_page_424_Figure_2.jpeg" class="img-fluid figure-img"></p>
<figcaption>FIGURE 11.11. Test performance curves, as a function of the number of training epochs.</figcaption>
</figure>
</div>
<p>FIGURE 11.11. Test performance curves, as a function of the number of training epochs, for the five networks of Table 11.1 applied to the ZIP code data. (Le Cun, 1989)</p>
<p>The networks all have sigmoidal output units, and were all fit with the sum-of-squares error function. The first network has no hidden layer, and hence is nearly equivalent to a linear multinomial regression model (Exercise 11.4). Net-2 is a single hidden layer network with 12 hidden units, of the kind described above.</p>
<p>The training set error for all of the networks was 0%, since in all cases there are more parameters than training observations. The evolution of the test error during the training epochs is shown in Figure 11.11. The linear network (Net-1) starts to overfit fairly quickly, while test performance of the others level off at successively superior values.</p>
<p>The other three networks have additional features which demonstrate the power and flexibility of the neural network paradigm. They introduce constraints on the network, natural for the problem at hand, which allow for more complex connectivity but fewer parameters.</p>
<p>Net-3 uses local connectivity: this means that each hidden unit is connected to only a small patch of units in the layer below. In the first hidden layer (an 8×8 array), each unit takes inputs from a 3×3 patch of the input layer; for units in the first hidden layer that are one unit apart, their receptive fields overlap by one row or column, and hence are two pixels apart. In the second hidden layer, inputs are from a 5 × 5 patch, and again units that are one unit apart have receptive fields that are two units apart. The weights for all other connections are set to zero. Local connectivity makes each unit responsible for extracting local features from the layer below, and</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th>Network Architecture</th>
<th>Links</th>
<th>Weights</th>
<th>% Correct</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Net-1:</td>
<td>Single layer network</td>
<td>2570</td>
<td>2570</td>
<td>80.0%</td>
</tr>
<tr class="even">
<td>Net-2:</td>
<td>Two layer network</td>
<td>3214</td>
<td>3214</td>
<td>87.0%</td>
</tr>
<tr class="odd">
<td>Net-3:</td>
<td>Locally connected</td>
<td>1226</td>
<td>1226</td>
<td>88.5%</td>
</tr>
<tr class="even">
<td>Net-4:</td>
<td>Constrained network 1</td>
<td>2266</td>
<td>1132</td>
<td>94.0%</td>
</tr>
<tr class="odd">
<td>Net-5:</td>
<td>Constrained network 2</td>
<td>5194</td>
<td>1060</td>
<td>98.4%</td>
</tr>
</tbody>
</table>
<p><strong>TABLE 11.1.</strong> Test set performance of five different neural networks on a handwritten digit classification example (Le Cun, 1989).</p>
<p>reduces considerably the total number of weights. With many more hidden units than Net-2, Net-3 has fewer links and hence weights (1226 vs.&nbsp;3214), and achieves similar performance.</p>
<p>Net-4 and Net-5 have local connectivity with shared weights. All units in a local feature map perform the same operation on different parts of the image, achieved by sharing the same weights. The first hidden layer of Net-4 has two <span class="math inline">\(8\times 8\)</span> arrays, and each unit takes input from a <span class="math inline">\(3\times 3\)</span> patch just like in Net-3. However, each of the units in a single <span class="math inline">\(8\times 8\)</span> feature map share the same set of nine weights (but have their own bias parameter). This forces the extracted features in different parts of the image to be computed by the same linear functional, and consequently these networks are sometimes known as convolutional networks. The second hidden layer of Net-4 has no weight sharing, and is the same as in Net-3. The gradient of the error function R with respect to a shared weight is the sum of the gradients of R with respect to each connection controlled by the weights in question.</p>
<p>Table 11.1 gives the number of links, the number of weights and the optimal test performance for each of the networks. We see that Net-4 has more links but fewer weights than Net-3, and superior test performance. Net-5 has four <span class="math inline">\(4\times 4\)</span> feature maps in the second hidden layer, each unit connected to a <span class="math inline">\(5\times 5\)</span> local patch in the layer below. Weights are shared in each of these feature maps. We see that Net-5 does the best, having errors of only 1.6%, compared to 13% for the “vanilla” network Net-2. The clever design of network Net-5, motivated by the fact that features of handwriting style should appear in more than one part of a digit, was the result of many person years of experimentation. This and similar networks gave better performance on ZIP code problems than any other learning method at that time (early 1990s). This example also shows that neural networks are not a fully automatic tool, as they are sometimes advertised. As with all statistical models, subject matter knowledge can and should be used to improve their performance.</p>
<p>This network was later outperformed by the tangent distance approach (Simard et al., 1993) described in Section 13.3.3, which explicitly incorporates natural affine invariances. At this point the digit recognition datasets become test beds for every new learning procedure, and researchers worked</p>
<p>hard to drive down the error rates. As of this writing, the best error rates on a large database (60, 000 training, 10, 000 test observations), derived from standard NIST<sup>2</sup> databases, were reported to be the following: (Le Cun et al., 1998):</p>
<ul>
<li>1.1% for tangent distance with a 1-nearest neighbor classifier (Section 13.3.3);</li>
<li>0.8% for a degree-9 polynomial SVM (Section 12.3);</li>
<li>0.8% for LeNet-5, a more complex version of the convolutional network described here;</li>
<li>0.7% for boosted LeNet-4. Boosting is described in Chapter 8. LeNet-4 is a predecessor of LeNet-5.</li>
</ul>
<p>Le Cun et al.&nbsp;(1998) report a much larger table of performance results, and it is evident that many groups have been working very hard to bring these test error rates down. They report a standard error of 0.1% on the error estimates, which is based on a binomial average with N = 10, 000 and p ≈ 0.01. This implies that error rates within 0.1—0.2% of one another are statistically equivalent. Realistically the standard error is even higher, since the test data has been implicitly used in the tuning of the various procedures.</p>
</section>
<section id="discussion" class="level1" data-number="21">
<h1 data-number="21"><span class="header-section-number">21</span> 11.8 Discussion</h1>
<p>Both projection pursuit regression and neural networks take nonlinear functions of linear combinations (“derived features”) of the inputs. This is a powerful and very general approach for regression and classification, and has been shown to compete well with the best learning methods on many problems.</p>
<p>These tools are especially effective in problems with a high signal-to-noise ratio and settings where prediction without interpretation is the goal. They are less effective for problems where the goal is to describe the physical process that generated the data and the roles of individual inputs. Each input enters into the model in many places, in a nonlinear fashion. Some authors (Hinton, 1989) plot a diagram of the estimated weights into each hidden unit, to try to understand the feature that each unit is extracting. This is limited however by the lack of identifiability of the parameter vectors αm, m = 1, . . . , M. Often there are solutions with α<sup>m</sup> spanning the same linear space as the ones found during training, giving predicted values that</p>
<p><sup>2</sup>The National Institute of Standards and Technology maintain large databases, including handwritten character databases; http://www.nist.gov/srd/.</p>
<p>are roughly the same. Some authors suggest carrying out a principal component analysis of these weights, to try to find an interpretable solution. In general, the difficulty of interpreting these models has limited their use in fields like medicine, where interpretation of the model is very important.</p>
<p>There has been a great deal of research on the training of neural networks. Unlike methods like CART and MARS, neural networks are smooth functions of real-valued parameters. This facilitates the development of Bayesian inference for these models. The next sections discusses a successful Bayesian implementation of neural networks.</p>
</section>
<section id="bayesian-neural-nets-and-the-nips-2003-challenge" class="level1" data-number="22">
<h1 data-number="22"><span class="header-section-number">22</span> 11.9 Bayesian Neural Nets and the NIPS 2003 Challenge</h1>
<p>A classification competition was held in 2003, in which five labeled training datasets were provided to participants. It was organized for a Neural Information Processing Systems (NIPS) workshop. Each of the data sets constituted a two-class classification problems, with different sizes and from a variety of domains (see Table 11.2). Feature measurements for a validation dataset were also available.</p>
<p>Participants developed and applied statistical learning procedures to make predictions on the datasets, and could submit predictions to a website on the validation set for a period of 12 weeks. With this feedback, participants were then asked to submit predictions for a separate test set and they received their results. Finally, the class labels for the validation set were released and participants had one week to train their algorithms on the combined training and validation sets, and submit their final predictions to the competition website. A total of 75 groups participated, with 20 and 16 eventually making submissions on the validation and test sets, respectively.</p>
<p>There was an emphasis on feature extraction in the competition. Artificial “probes” were added to the data: these are noise features with distributions resembling the real features but independent of the class labels. The percentage of probes that were added to each dataset, relative to the total set of features, is shown on Table 11.2. Thus each learning algorithm had to figure out a way of identifying the probes and downweighting or eliminating them.</p>
<p>A number of metrics were used to evaluate the entries, including the percentage correct on the test set, the area under the ROC curve, and a combined score that compared each pair of classifiers head-to-head. The results of the competition are very interesting and are detailed in Guyon et al.&nbsp;(2006). The most notable result: the entries of Neal and Zhang (2006) were the clear overall winners. In the final competition they finished first</p>
<p>Artificial</p>
<p>Madelon</p>
<p>Dataset Domain Feature <span class="math inline">\(N_{tr}\)</span> <span class="math inline">\(N_{val}\)</span> Percent <span class="math inline">\(N_{te}\)</span> р Туре Probes Arcene Mass spectrometry Dense 10,000 30 100 100 700 2000 Text classification Sparse 20,000 50 300 300 Dexter Sparse 100,000 800 350 800 Dorothea Drug discovery 50 Gisette Digit recognition Dense 5000 30 6000 1000 6500</p>
<p>Dense</p>
<p><strong>TABLE 11.2.</strong> NIPS 2003 challenge data sets. The column labeled p is the number of features. For the Dorothea dataset the features are binary. <span class="math inline">\(N_{tr}\)</span> , <span class="math inline">\(N_{val}\)</span> and <span class="math inline">\(N_{te}\)</span> are the number of training, validation and test cases, respectively</p>
<p>in three of the five datasets, and were 5th and 7th on the remaining two datasets.</p>
<p>500</p>
<p>96</p>
<p>2000</p>
<p>600</p>
<p>1800</p>
<p>In their winning entries, Neal and Zhang (2006) used a series of preprocessing feature-selection steps, followed by Bayesian neural networks, Dirichlet diffusion trees, and combinations of these methods. Here we focus only on the Bayesian neural network approach, and try to discern which aspects of their approach were important for its success. We rerun their programs and compare the results to boosted neural networks and boosted trees, and other related methods.</p>
<section id="bayes-boosting-and-bagging" class="level4" data-number="22.0.0.1">
<h4 data-number="22.0.0.1" class="anchored" data-anchor-id="bayes-boosting-and-bagging"><span class="header-section-number">22.0.0.1</span> 11.9.1 Bayes, Boosting and Bagging</h4>
<p>Let us first review briefly the Bayesian approach to inference and its application to neural networks. Given training data <span class="math inline">\(\mathbf{X}_{\mathrm{tr}}, \mathbf{y}_{\mathrm{tr}}\)</span> , we assume a sampling model with parameters <span class="math inline">\(\theta\)</span> ; Neal and Zhang (2006) use a two-hidden-layer neural network, with output nodes the class probabilities <span class="math inline">\(\Pr(Y|X,\theta)\)</span> for the binary outcomes. Given a prior distribution <span class="math inline">\(\Pr(\theta)\)</span> , the posterior distribution for the parameters is</p>
<p><span class="math display">\[Pr(\theta|\mathbf{X}_{tr}, \mathbf{y}_{tr}) = \frac{Pr(\theta)Pr(\mathbf{y}_{tr}|\mathbf{X}_{tr}, \theta)}{\int Pr(\theta)Pr(\mathbf{y}_{tr}|\mathbf{X}_{tr}, \theta)d\theta}\]</span> (11.19)</p>
<p>For a test case with features <span class="math inline">\(X_{\text{new}}\)</span> , the predictive distribution for the label <span class="math inline">\(Y_{\text{new}}\)</span> is</p>
<p><span class="math display">\[\Pr(Y_{\text{new}}|X_{\text{new}}, \mathbf{X}_{\text{tr}}, \mathbf{y}_{\text{tr}}) = \int \Pr(Y_{\text{new}}|X_{\text{new}}, \theta) \Pr(\theta|\mathbf{X}_{\text{tr}}, \mathbf{y}_{\text{tr}}) d\theta \quad (11.20)\]</span></p>
<p>(c.f. equation 8.24). Since the integral in (11.20) is intractable, sophisticated Markov Chain Monte Carlo (MCMC) methods are used to sample from the posterior distribution <span class="math inline">\(\Pr(Y_{\text{new}}|X_{\text{new}},\mathbf{X}_{\text{tr}},\mathbf{y}_{\text{tr}})\)</span> . A few hundred values <span class="math inline">\(\theta\)</span> are generated and then a simple average of these values estimates the integral. Neal and Zhang (2006) use diffuse Gaussian priors for all of the parameters. The particular MCMC approach that was used is called <em>hybrid Monte Carlo</em>, and may be important for the success of the method. It includes an auxiliary momentum vector and implements Hamiltonian dynamics in which the potential function is the target density. This is done to avoid</p>
<p>random walk behavior; the successive candidates move across the sample space in larger steps. They tend to be less correlated and hence converge to the target distribution more rapidly.</p>
<p>Neal and Zhang (2006) also tried different forms of pre-processing of the features:</p>
<ul>
<li><ol type="1">
<li>univariate screening using t-tests, and</li>
</ol></li>
<li><ol start="2" type="1">
<li>automatic relevance determination.</li>
</ol></li>
</ul>
<p>In the latter method (ARD), the weights (coefficients) for the jth feature to each of the first hidden layer units all share a common prior variance σ 2 j , and prior mean zero. The posterior distributions for each variance σ 2 j are computed, and the features whose posterior variance concentrates on small values are discarded.</p>
<p>There are thus three main features of this approach that could be important for its success:</p>
<ul>
<li><ol type="a">
<li>the feature selection and pre-processing,</li>
</ol></li>
<li><ol start="2" type="a">
<li>the neural network model, and</li>
</ol></li>
<li><ol start="3" type="a">
<li>the Bayesian inference for the model using MCMC.</li>
</ol></li>
</ul>
<p>According to Neal and Zhang (2006), feature screening in (a) is carried out purely for computational efficiency; the MCMC procedure is slow with a large number of features. There is no need to use feature selection to avoid overfitting. The posterior average (11.20) takes care of this automatically.</p>
<p>We would like to understand the reasons for the success of the Bayesian method. In our view, power of modern Bayesian methods does not lie in their use as a formal inference procedure; most people would not believe that the priors in a high-dimensional, complex neural network model are actually correct. Rather the Bayesian/MCMC approach gives an efficient way of sampling the relevant parts of model space, and then averaging the predictions for the high-probability models.</p>
<p>Bagging and boosting are non-Bayesian procedures that have some similarity to MCMC in a Bayesian model. The Bayesian approach fixes the data and perturbs the parameters, according to current estimate of the posterior distribution. Bagging perturbs the data in an i.i.d fashion and then re-estimates the model to give a new set of model parameters. At the end, a simple average of the model predictions from different bagged samples is computed. Boosting is similar to bagging, but fits a model that is additive in the models of each individual base learner, which are learned using non i.i.d. samples. We can write all of these models in the form</p>
<p><span class="math display">\[\hat{f}(\mathbf{x}_{\text{new}}) = \sum_{\ell=1}^{L} w_{\ell} E(Y_{\text{new}} | \mathbf{x}_{\text{new}}, \hat{\theta}_{\ell})\]</span> (11.21)</p>
<p>In all cases the ˆθ<sup>ℓ</sup> are a large collection of model parameters. For the Bayesian model the w<sup>ℓ</sup> = 1/L, and the average estimates the posterior mean (11.21) by sampling θ<sup>ℓ</sup> from the posterior distribution. For bagging, w<sup>ℓ</sup> = 1/L as well, and the ˆθ<sup>ℓ</sup> are the parameters refit to bootstrap resamples of the training data. For boosting, the weights are all equal to 1, but the ˆθ<sup>ℓ</sup> are typically chosen in a nonrandom sequential fashion to constantly improve the fit.</p>
</section>
<section id="performance-comparisons" class="level4" data-number="22.0.0.2">
<h4 data-number="22.0.0.2" class="anchored" data-anchor-id="performance-comparisons"><span class="header-section-number">22.0.0.2</span> 11.9.2 Performance Comparisons</h4>
<p>Based on the similarities above, we decided to compare Bayesian neural networks to boosted trees, boosted neural networks, random forests and bagged neural networks on the five datasets in Table 11.2. Bagging and boosting of neural networks are not methods that we have previously used in our work. We decided to try them here, because of the success of Bayesian neural networks in this competition, and the good performance of bagging and boosting with trees. We also felt that by bagging and boosting neural nets, we could assess both the choice of model as well as the model search strategy.</p>
<p>Here are the details of the learning methods that were compared:</p>
<ul>
<li>Bayesian neural nets. The results here are taken from Neal and Zhang (2006), using their Bayesian approach to fitting neural networks. The models had two hidden layers of 20 and 8 units. We re-ran some networks for timing purposes only.</li>
<li>Boosted trees. We used the gbm package (version 1.5-7) in the R language. Tree depth and shrinkage factors varied from dataset to dataset. We consistently bagged 80% of the data at each boosting iteration (the default is 50%). Shrinkage was between 0.001 and 0.1. Tree depth was between 2 and 9.</li>
<li>Boosted neural networks. Since boosting is typically most effective with “weak” learners, we boosted a single hidden layer neural network with two or four units, fit with the nnet package (version 7.2-36) in R.</li>
<li>Random forests. We used the R package randomForest (version 4.5-16) with default settings for the parameters.</li>
<li>Bagged neural networks. We used the same architecture as in the Bayesian neural network above (two hidden layers of 20 and 8 units), fit using both Neal’s C language package “Flexible Bayesian Modeling” (2004- 11-10 release), and Matlab neural-net toolbox (version 5.1).</li>
</ul>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figures/_page_431_Figure_2.jpeg" class="img-fluid figure-img"></p>
<figcaption>FIGURE 11.12. Performance of different learning methods on five problems.</figcaption>
</figure>
</div>
<p>FIGURE 11.12. Performance of different learning methods on five problems, using both univariate screening of features (top panel) and a reduced feature set from automatic relevance determination. The error bars at the top of each plot have width equal to one standard error of the difference between two error rates. On most of the problems several competitors are within this error bound.</p>
<p>This analysis was carried out by Nicholas Johnson, and full details may be found in Johnson (2008)<sup>3</sup> . The results are shown in Figure 11.12 and Table 11.3.</p>
<p>The figure and table show Bayesian, boosted and bagged neural networks, boosted trees, and random forests, using both the screened and reduced features sets. The error bars at the top of each plot indicate one standard error of the difference between two error rates. Bayesian neural networks again emerge as the winner, although for some datasets the differences between the test error rates is not statistically significant. Random forests performs the best among the competitors using the selected feature set, while the boosted neural networks perform best with the reduced feature set, and nearly match the Bayesian neural net.</p>
<p>The superiority of boosted neural networks over boosted trees suggest that the neural network model is better suited to these particular problems. Specifically, individual features might not be good predictors here</p>
<p><sup>3</sup>We also thank Isabelle Guyon for help in preparing the results of this section.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 27%">
<col style="width: 9%">
<col style="width: 20%">
<col style="width: 23%">
<col style="width: 12%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 2%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th></th>
<th>Screened Features</th>
<th>ARD Reduced Features</th>
<th></th>
<th></th>
<th></th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Method</td>
<td>Average</td>
<td>Average</td>
<td>Average</td>
<td>Average</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td>Rank</td>
<td>Time</td>
<td>Rank</td>
<td>Time</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>Bayesian neural networks</td>
<td>1.5</td>
<td>384(138)</td>
<td>1.6</td>
<td>600(186)</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>Boosted trees</td>
<td>3.4</td>
<td>3.03(2.5)</td>
<td>4.0</td>
<td>34.1(32.4)</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>Boosted neural networks</td>
<td>3.8</td>
<td>9.4(8.6)</td>
<td>2.2</td>
<td>35.6(33.5)</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>Random forests</td>
<td>2.7</td>
<td>1.9(1.7)</td>
<td>3.2</td>
<td>11.2(9.3)</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>Bagged neural networks</td>
<td>3.6</td>
<td>3.5(1.1)</td>
<td>4.0</td>
<td>6.4(4.4)</td>
<td></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<p>TABLE 11.3. Performance of different methods. Values are average rank of test error across the five problems (low is good), and mean computation time and standard error of the mean, in minutes.</p>
<p>and linear combinations of features work better. However the impressive performance of random forests is at odds with this explanation, and came as a surprise to us.</p>
<p>Since the reduced feature sets come from the Bayesian neural network approach, only the methods that use the screened features are legitimate, self-contained procedures. However, this does suggest that better methods for internal feature selection might help the overall performance of boosted neural networks.</p>
<p>The table also shows the approximate training time required for each method. Here the non-Bayesian methods show a clear advantage.</p>
<p>Overall, the superior performance of Bayesian neural networks here may be due to the fact that</p>
<ul>
<li><ol type="a">
<li>the neural network model is well suited to these five problems, and</li>
</ol></li>
<li><ol start="2" type="a">
<li>the MCMC approach provides an efficient way of exploring the important part of the parameter space, and then averaging the resulting models according to their quality.</li>
</ol></li>
</ul>
<p>The Bayesian approach works well for smoothly parametrized models like neural nets; it is not yet clear that it works as well for non-smooth models like trees.</p>
</section>
</section>
<section id="computational-considerations" class="level1" data-number="23">
<h1 data-number="23"><span class="header-section-number">23</span> 11.10 Computational Considerations</h1>
<p>With N observations, p predictors, M hidden units and L training epochs, a neural network fit typically requires O(N pML) operations. There are many packages available for fitting neural networks, probably many more than exist for mainstream statistical methods. Because the available software varies widely in quality, and the learning problem for neural networks is sensitive to issues such as input scaling, such software should be carefully chosen and tested.</p>
</section>
<section id="bibliographic-notes" class="level1" data-number="24">
<h1 data-number="24"><span class="header-section-number">24</span> Bibliographic Notes</h1>
<p>Projection pursuit was proposed by Friedman and Tukey (1974), and specialized to regression by Friedman and Stuetzle (1981). Huber (1985) gives a scholarly overview, and Roosen and Hastie (1994) present a formulation using smoothing splines. The motivation for neural networks dates back to McCulloch and Pitts (1943), Widrow and Hoff (1960) (reprinted in Anderson and Rosenfeld (1988)) and Rosenblatt (1962). Hebb (1949) heavily influenced the development of learning algorithms. The resurgence of neural networks in the mid 1980s was due to Werbos (1974), Parker (1985) and Rumelhart et al.&nbsp;(1986), who proposed the back-propagation algorithm. Today there are many books written on the topic, for a broad range of audiences. For readers of this book, Hertz et al.&nbsp;(1991), Bishop (1995) and Ripley (1996) may be the most informative. Bayesian learning for neural networks is described in Neal (1996). The ZIP code example was taken from Le Cun (1989); see also Le Cun et al.&nbsp;(1990) and Le Cun et al.&nbsp;(1998).</p>
<p>We do not discuss theoretical topics such as approximation properties of neural networks, such as the work of Barron (1993), Girosi et al.&nbsp;(1995) and Jones (1992). Some of these results are summarized by Ripley (1996).</p>
</section>
<section id="exercises" class="level1" data-number="25">
<h1 data-number="25"><span class="header-section-number">25</span> Exercises</h1>
<p>Ex. 11.1 Establish the exact correspondence between the projection pursuit regression model (11.1) and the neural network (11.5). In particular, show that the single-layer regression network is equivalent to a PPR model with gm(ω T <sup>m</sup>x) = βmσ(α0<sup>m</sup> + sm(ω T <sup>m</sup>x)), where ω<sup>m</sup> is the mth unit vector. Establish a similar equivalence for a classification network.</p>
<p>Ex. 11.2 Consider a neural network for a quantitative outcome as in (11.5), using squared-error loss and identity output function gk(t) = t. Suppose that the weights α<sup>m</sup> from the input to hidden layer are nearly zero. Show that the resulting model is nearly linear in the inputs.</p>
<p>Ex. 11.3 Derive the forward and backward propagation equations for the cross-entropy loss function.</p>
<p>Ex. 11.4 Consider a neural network for a K class outcome that uses crossentropy loss. If the network has no hidden layer, show that the model is equivalent to the multinomial logistic model described in Chapter 4.</p>
<section id="ex.-11.5" class="level4" data-number="25.0.0.1">
<h4 data-number="25.0.0.1" class="anchored" data-anchor-id="ex.-11.5"><span class="header-section-number">25.0.0.1</span> Ex. 11.5</h4>
<ol type="a">
<li><p>Write a program to fit a single hidden layer neural network (ten hidden units) via back-propagation and weight decay.</p></li>
<li><p>Apply it to 100 observations from the model</p></li>
</ol>
<p><span class="math display">\[Y = \sigma(a_1^T X) + (a_2^T X)^2 + 0.30 \cdot Z,\]</span></p>
<p>where σ is the sigmoid function, Z is standard normal, X<sup>T</sup> = (X1, X2), each X<sup>j</sup> being independent standard normal, and a<sup>1</sup> = (3, 3), a<sup>2</sup> = (3, −3). Generate a test sample of size 1000, and plot the training and test error curves as a function of the number of training epochs, for different values of the weight decay parameter. Discuss the overfitting behavior in each case.</p>
<ol start="3" type="a">
<li>Vary the number of hidden units in the network, from 1 up to 10, and determine the minimum number needed to perform well for this task.</li>
</ol>
<p>Ex. 11.6 Write a program to carry out projection pursuit regression, using cubic smoothing splines with fixed degrees of freedom. Fit it to the data from the previous exercise, for various values of the smoothing parameter and number of model terms. Find the minimum number of model terms necessary for the model to perform well and compare this to the number of hidden units from the previous exercise.</p>
<p>Ex. 11.7 Fit a neural network to the spam data of Section 9.1.2, and compare the results to those for the additive model given in that chapter. Compare both the classification performance and interpretability of the final model.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../chapters/10-boosting-and-additive-trees.html" class="pagination-link" aria-label="Boosting and Additive Trees">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Boosting and Additive Trees</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../chapters/12-support-vector-machines-and-flexible-discriminants.html" class="pagination-link" aria-label="Support Vector Machines and Flexible Discriminants">
        <span class="nav-page-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Support Vector Machines and Flexible Discriminants</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>