<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.35">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>21&nbsp; Index – esl</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../references.html" rel="next">
<link href="../chapters/20-author-index.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-46f66b053e56abd73bb6e954d61a315b.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-5ccb035bea26c1e21f80f44cf7c27909.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/21-index.html"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Index</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">esl</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/01-introduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/02-overview-of-supervised-learning.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Overview of Supervised Learning</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/03-linear-methods-for-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Linear Methods for Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/04-linear-methods-for-classification.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Linear Methods for Classification</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/05-basis-expansions-and-regularization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Basis Expansions and Regularization</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/06-kernel-smoothing-methods.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Kernel Smoothing Methods</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/07-model-assessment-and-selection.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Model Assessment and Selection</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/08-model-inference-and-averaging.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Model Inference and Averaging</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/09-additive-models-trees-and-related-methods.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Additive Models, Trees, and Related Methods</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/10-boosting-and-additive-trees.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Boosting and Additive Trees</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/11-neural-networks.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Neural Networks</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/12-support-vector-machines-and-flexible-discriminants.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Support Vector Machines and Flexible Discriminants</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/13-prototype-methods-and-nearest-neighbors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Prototype Methods and Nearest-Neighbors</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/14-unsupervised-learning.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Unsupervised Learning</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/15-random-forests.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Random Forests</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/16-ensemble-learning.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Ensemble Learning</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/17-undirected-graphical-models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Undirected Graphical Models</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/18-high-dimensional-problems.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">High-Dimensional Problems: p ≫ N</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/19-references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">References</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/20-author-index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Author Index</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/21-index.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Index</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
        
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Index</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<table class="caption-top table">
<colgroup>
<col style="width: 49%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>L1<br>regularization,<br>see<br>Lasso</th>
<th>demographics, 379–380<br>document, 532</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Activation function, 392–395</td>
<td>flow cytometry, 637</td>
</tr>
<tr class="even">
<td>AdaBoost, 337–346</td>
<td>galaxy, 201</td>
</tr>
<tr class="odd">
<td>Adaptive lasso, 92</td>
<td>heart attack, 122, 146, 207</td>
</tr>
<tr class="even">
<td>Adaptive methods, 429</td>
<td>lymphoma, 674</td>
</tr>
<tr class="odd">
<td>Adaptive nearest neighbor meth</td>
<td>marketing, 488</td>
</tr>
<tr class="even">
<td>ods, 475–478</td>
<td>microarray, 5, 505, 532</td>
</tr>
<tr class="odd">
<td>Adaptive wavelet filtering, 181</td>
<td>nested spheres, 590</td>
</tr>
<tr class="even">
<td>Additive model, 295–304</td>
<td>New Zealand fish, 375–379</td>
</tr>
<tr class="odd">
<td>Adjusted response, 297</td>
<td>nuclear magnetic resonance,</td>
</tr>
<tr class="even">
<td>Affine set, 130</td>
<td>176</td>
</tr>
<tr class="odd">
<td>Affine-invariant average, 482, 540</td>
<td>ozone, 201</td>
</tr>
<tr class="even">
<td>AIC,<br>see<br>Akaike information cri</td>
<td>prostate cancer, 3, 49, 61, 608</td>
</tr>
<tr class="odd">
<td>terion</td>
<td>protein mass spectrometry, 664</td>
</tr>
<tr class="even">
<td>Akaike information criterion (AIC),</td>
<td>satellite image, 470</td>
</tr>
<tr class="odd">
<td>230</td>
<td>skin of the orange, 429–432</td>
</tr>
<tr class="even">
<td>Analysis of deviance, 124</td>
<td>spam, 2, 300–304, 313, 320,</td>
</tr>
<tr class="odd">
<td>Applications</td>
<td>328, 352, 593</td>
</tr>
<tr class="even">
<td>abstracts, 672</td>
<td>vowel, 440, 464</td>
</tr>
<tr class="odd">
<td>aorta, 204</td>
<td>waveform, 451</td>
</tr>
<tr class="even">
<td>bone, 152</td>
<td>ZIP code, 4, 404, 536–539</td>
</tr>
<tr class="odd">
<td>California housing, 371–372,</td>
<td>Archetypal analysis, 554–557</td>
</tr>
<tr class="even">
<td>591</td>
<td>Association rules, 492–495, 499–</td>
</tr>
<tr class="odd">
<td>countries, 517</td>
<td>501</td>
</tr>
</tbody>
</table>
<table class="caption-top table">
<colgroup>
<col style="width: 48%">
<col style="width: 51%">
</colgroup>
<thead>
<tr class="header">
<th>Automatic relevance determination,</th>
<th>implementations, 360</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>411</td>
<td>margin maximization, 613</td>
</tr>
<tr class="even">
<td>Automatic selection of smoothing</td>
<td>numerical optimization, 358</td>
</tr>
<tr class="odd">
<td>parameters , 156</td>
<td>partial-dependence plots, 369</td>
</tr>
<tr class="even">
<td>B-Spline, 186</td>
<td>regularization path, 607<br>shrinkage, 364</td>
</tr>
<tr class="odd">
<td>Back-propagation, 392–397, 408–</td>
<td>stochastic gradient boosting,</td>
</tr>
<tr class="even">
<td>409</td>
<td>365</td>
</tr>
<tr class="odd">
<td>Backfitting, 297, 391</td>
<td>tree size, 361</td>
</tr>
<tr class="even">
<td>Backward</td>
<td>variable importance, 367</td>
</tr>
<tr class="odd">
<td>selection, 58</td>
<td>Bootstrap, 249, 261–264, 267, 271–</td>
</tr>
<tr class="even">
<td>stepwise selection, 59</td>
<td>282, 587</td>
</tr>
<tr class="odd">
<td>Backward pass, 396</td>
<td>relationship to Bayesian method,</td>
</tr>
<tr class="even">
<td>Bagging, 282–288, 409, 587</td>
<td>271</td>
</tr>
<tr class="odd">
<td>Basis expansions and regulariza</td>
<td>relationship to maximum like</td>
</tr>
<tr class="even">
<td>tion, 139–189</td>
<td>lihood method, 267</td>
</tr>
<tr class="odd">
<td>Basis functions, 141, 186, 189, 321,</td>
<td>Bottom-up clustering, 520–528</td>
</tr>
<tr class="even">
<td>328</td>
<td>Bump<br>hunting,<br>see<br>Patient<br>rule</td>
</tr>
<tr class="odd">
<td>Batch learning, 397</td>
<td>induction method</td>
</tr>
<tr class="even">
<td>Baum–Welch algorithm, 272</td>
<td>Bumping, 290–292</td>
</tr>
<tr class="odd">
<td>Bayes</td>
<td></td>
</tr>
<tr class="even">
<td>classifier, 21</td>
<td>C5.0, 624</td>
</tr>
<tr class="odd">
<td>factor, 234</td>
<td>Canonical variates, 441</td>
</tr>
<tr class="even">
<td>methods, 233–235, 267–272</td>
<td>CART,<br>see<br>Classification and re</td>
</tr>
<tr class="odd">
<td>rate, 21</td>
<td>gression trees</td>
</tr>
<tr class="even">
<td>Bayesian, 409</td>
<td>Categorical predictors, 10, 310</td>
</tr>
<tr class="odd">
<td>Bayesian information criterion (BIC),</td>
<td>Censored data, 674</td>
</tr>
<tr class="even">
<td>233</td>
<td>Classical multidimensional scaling,</td>
</tr>
<tr class="odd">
<td>Benjamini–Hochberg method, 688</td>
<td>570</td>
</tr>
<tr class="even">
<td>Best-subset selection, 57, 610</td>
<td>Classification, 22, 101–137, 305–</td>
</tr>
<tr class="odd">
<td>Between class covariance matrix,</td>
<td>317, 417–429</td>
</tr>
<tr class="even">
<td>114</td>
<td>Classification and regression trees</td>
</tr>
<tr class="odd">
<td>Bias, 16, 24, 37, 160, 219</td>
<td>(CART), 305–317</td>
</tr>
<tr class="even">
<td>Bias-variance decomposition, 24,</td>
<td>Clique, 628</td>
</tr>
<tr class="odd">
<td>37, 219</td>
<td>Clustering, 501–528</td>
</tr>
<tr class="even">
<td>Bias-variance tradeoff, 37, 219</td>
<td>k-means, 509–510</td>
</tr>
<tr class="odd">
<td>BIC,<br>see<br>Bayesian Information Cri</td>
<td>agglomerative, 523–528</td>
</tr>
<tr class="even">
<td>terion</td>
<td>hierarchical, 520–528</td>
</tr>
<tr class="odd">
<td>Boltzmann machines, 638–648</td>
<td>Codebook, 515</td>
</tr>
<tr class="even">
<td>Bonferroni method, 686</td>
<td>Combinatorial algorithms, 507</td>
</tr>
<tr class="odd">
<td>Boosting, 337–386, 409</td>
<td>Combining models, 288–290</td>
</tr>
<tr class="even">
<td>as lasso regression, 607–609</td>
<td>Committee, 289, 587, 605</td>
</tr>
<tr class="odd">
<td>exponential loss and AdaBoost,</td>
<td>Comparison of learning methods,</td>
</tr>
<tr class="even">
<td>343</td>
<td>350–352</td>
</tr>
<tr class="odd">
<td>gradient boosting, 358</td>
<td>Complete data, 276</td>
</tr>
</tbody>
</table>
<table class="caption-top table">
<colgroup>
<col style="width: 47%">
<col style="width: 52%">
</colgroup>
<thead>
<tr class="header">
<th>Complexity parameter, 37</th>
<th>Discriminant</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Computational shortcuts</td>
<td>adaptive nearest neighbor clas</td>
</tr>
<tr class="even">
<td>quadratic penalty, 659</td>
<td>sifier, 475–480</td>
</tr>
<tr class="odd">
<td>Condensing procedure, 480</td>
<td>analysis, 106–119</td>
</tr>
<tr class="even">
<td>Conditional likelihood, 31</td>
<td>coordinates, 108</td>
</tr>
<tr class="odd">
<td>Confusion matrix, 301</td>
<td>functions, 109–110</td>
</tr>
<tr class="even">
<td>Conjugate gradients, 396</td>
<td>Dissimilarity measure, 503–504</td>
</tr>
<tr class="odd">
<td>Consensus, 285–286</td>
<td>Dummy variables, 10</td>
</tr>
<tr class="even">
<td>Convolutional networks, 407</td>
<td></td>
</tr>
<tr class="odd">
<td>Coordinate descent, 92, 636, 668</td>
<td></td>
</tr>
<tr class="even">
<td>COSSO, 304</td>
<td>Early stopping, 398</td>
</tr>
<tr class="odd">
<td>Cost complexity pruning, 308</td>
<td>Effective degrees of freedom, 17,</td>
</tr>
<tr class="even">
<td>Covariance graph, 631</td>
<td>68, 153–154, 158, 232, 302,</td>
</tr>
<tr class="odd">
<td>Cp<br>statistic, 230</td>
<td>336</td>
</tr>
<tr class="even">
<td>Cross-entropy, 308–310</td>
<td>Effective<br>number<br>of<br>parameters,</td>
</tr>
<tr class="odd">
<td>Cross-validation, 241–245</td>
<td>15, 68, 153–154, 158, 232,</td>
</tr>
<tr class="even">
<td>Cubic smoothing spline, 151–153</td>
<td>302, 336</td>
</tr>
<tr class="odd">
<td>Cubic spline, 151–153</td>
<td>Eigenvalues of a smoother matrix,</td>
</tr>
<tr class="even">
<td>Curse of dimensionality, 22–26</td>
<td>154</td>
</tr>
<tr class="odd">
<td></td>
<td>Elastic net, 662</td>
</tr>
<tr class="even">
<td>Dantzig selector, 89</td>
<td>EM algorithm, 272–279</td>
</tr>
<tr class="odd">
<td>Data augmentation, 276</td>
<td>as a maximization-maximization</td>
</tr>
<tr class="even">
<td>Daubechies<br>symmlet-8<br>wavelets,</td>
<td>procedure, 277</td>
</tr>
<tr class="odd">
<td>176</td>
<td>for two component Gaussian</td>
</tr>
<tr class="even">
<td>De-correlation, 597</td>
<td>mixture, 272</td>
</tr>
<tr class="odd">
<td>Decision boundary, 13–15, 21</td>
<td>Encoder, 514–515</td>
</tr>
<tr class="even">
<td>Decision trees, 305–317</td>
<td>Ensemble, 616–623</td>
</tr>
<tr class="odd">
<td>Decoder, 515,<br>see<br>encoder</td>
<td>Ensemble learning, 605–624</td>
</tr>
<tr class="even">
<td>Decomposable models, 641</td>
<td>Entropy, 309</td>
</tr>
<tr class="odd">
<td>Degrees of freedom</td>
<td>Equivalent kernel, 156</td>
</tr>
<tr class="even">
<td>in an additive model, 302</td>
<td>Error rate, 219–230</td>
</tr>
<tr class="odd">
<td>in ridge regression, 68</td>
<td>Error-correcting codes, 606</td>
</tr>
<tr class="even">
<td>of a tree, 336</td>
<td>Estimates of in-sample prediction</td>
</tr>
<tr class="odd">
<td>of smoother matrices, 153–154,</td>
<td>error, 230</td>
</tr>
<tr class="even">
<td>158</td>
<td>Expectation-maximization algorithm,</td>
</tr>
<tr class="odd">
<td>Delta rule, 397</td>
<td>see<br>EM algorithm</td>
</tr>
<tr class="even">
<td>Demmler-Reinsch basis for splines,</td>
<td>Extra-sample error, 228</td>
</tr>
<tr class="odd">
<td>156</td>
<td></td>
</tr>
<tr class="even">
<td>Density estimation, 208–215</td>
<td>False discovery rate, 687–690, 692,</td>
</tr>
<tr class="odd">
<td>Deviance, 124, 309</td>
<td>693</td>
</tr>
<tr class="even">
<td>Diagonal linear discriminant anal</td>
<td>Feature, 1</td>
</tr>
<tr class="odd">
<td>ysis, 651–654</td>
<td>extraction, 150</td>
</tr>
<tr class="even">
<td>Dimension reduction, 658</td>
<td>selection, 409, 658, 681–683</td>
</tr>
<tr class="odd">
<td>for nearest neighbors, 479</td>
<td>Feed-forward neural networks, 392–</td>
</tr>
<tr class="even">
<td>Discrete variables, 10, 310–311</td>
<td>408</td>
</tr>
<tr class="odd">
<td></td>
<td></td>
</tr>
</tbody>
</table>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Global Markov property, 628</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Gradient Boosting, 359–361</td>
</tr>
<tr class="even">
<td>Gradient descent, 358, 395–397</td>
</tr>
<tr class="odd">
<td>Graph Laplacian, 545</td>
</tr>
<tr class="even">
<td>Graphical lasso, 636</td>
</tr>
<tr class="odd">
<td>Grouped lasso, 90</td>
</tr>
<tr class="even">
<td></td>
</tr>
<tr class="odd">
<td>Haar basis function, 176</td>
</tr>
<tr class="even">
<td>Hammersley-Clifford theorem, 629</td>
</tr>
<tr class="odd">
<td>Hard-thresholding, 653</td>
</tr>
<tr class="even">
<td>Hat matrix, 46</td>
</tr>
<tr class="odd">
<td>Helix, 582</td>
</tr>
<tr class="even">
<td>Hessian matrix, 121</td>
</tr>
<tr class="odd">
<td>Hidden nodes, 641–642</td>
</tr>
<tr class="even">
<td>Hidden units, 393–394</td>
</tr>
<tr class="odd">
<td></td>
</tr>
<tr class="even">
<td>Hierarchical clustering, 520–528</td>
</tr>
<tr class="odd">
<td>Hierarchical mixtures of experts,</td>
</tr>
<tr class="even">
<td>329–332</td>
</tr>
<tr class="odd">
<td>High-dimensional problems, 649</td>
</tr>
<tr class="even">
<td>Hints, 96</td>
</tr>
<tr class="odd">
<td>Hyperplane,<br>see<br>Separating<br>Hy</td>
</tr>
<tr class="even">
<td>perplane</td>
</tr>
<tr class="odd">
<td></td>
</tr>
<tr class="even">
<td>ICA,<br>see<br>Independent components</td>
</tr>
<tr class="odd">
<td>analysis</td>
</tr>
<tr class="even">
<td>Importance sampling, 617</td>
</tr>
<tr class="odd">
<td>In-sample prediction error, 230</td>
</tr>
<tr class="even">
<td>Incomplete data, 332</td>
</tr>
<tr class="odd">
<td>Independent components analysis,</td>
</tr>
<tr class="even">
<td>557–570</td>
</tr>
<tr class="odd">
<td>Independent variables, 9</td>
</tr>
<tr class="even">
<td>Indicator response matrix, 103</td>
</tr>
<tr class="odd">
<td>Inference, 261–294</td>
</tr>
<tr class="even">
<td>Information</td>
</tr>
<tr class="odd">
<td>Fisher, 266</td>
</tr>
<tr class="even">
<td>observed, 274</td>
</tr>
<tr class="odd">
<td>Information theory, 236, 561</td>
</tr>
<tr class="even">
<td>Inner product, 53, 668, 670</td>
</tr>
<tr class="odd">
<td>Inputs, 10</td>
</tr>
<tr class="even">
<td>Instability of trees, 312</td>
</tr>
<tr class="odd">
<td>Intercept, 11</td>
</tr>
<tr class="even">
<td>Invariance manifold, 471</td>
</tr>
<tr class="odd">
<td>Invariant metric, 471</td>
</tr>
<tr class="even">
<td>Inverse wavelet transform, 179</td>
</tr>
<tr class="odd">
<td></td>
</tr>
</tbody>
</table>
<table class="caption-top table">
<colgroup>
<col style="width: 52%">
<col style="width: 47%">
</colgroup>
<thead>
<tr class="header">
<th>IRLS,<br>see<br>Iteratively<br>reweighted</th>
<th>fused, 666</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>least squares</td>
<td>Latent</td>
</tr>
<tr class="even">
<td>Irreducible error, 224</td>
<td>factor, 674</td>
</tr>
<tr class="odd">
<td>Ising model, 638</td>
<td>variable, 678</td>
</tr>
<tr class="even">
<td>ISOMAP, 572</td>
<td>Learning, 1</td>
</tr>
<tr class="odd">
<td>Isometric feature mapping, 572</td>
<td>Learning rate, 396</td>
</tr>
<tr class="even">
<td>Iterative proportional scaling, 585</td>
<td>Learning vector quantization, 462</td>
</tr>
<tr class="odd">
<td>Iteratively reweighted least squares</td>
<td>Least angle regression, 73–79, 86,</td>
</tr>
<tr class="even">
<td>(IRLS), 121</td>
<td>610</td>
</tr>
<tr class="odd">
<td></td>
<td>Least squares, 11, 32</td>
</tr>
<tr class="even">
<td>Jensen’s inequality, 293</td>
<td>Leave-one-out cross-validation, 243</td>
</tr>
<tr class="odd">
<td>Join tree, 629</td>
<td>LeNet, 406</td>
</tr>
<tr class="even">
<td>Junction tree, 629</td>
<td>Likelihood function, 265, 273</td>
</tr>
<tr class="odd">
<td></td>
<td>Linear basis expansion, 139–148</td>
</tr>
<tr class="even">
<td>K-means clustering, 460, 509–514</td>
<td>Linear combination splits, 312</td>
</tr>
<tr class="odd">
<td>K-medoid clustering, 515–520</td>
<td>Linear discriminant function, 106–</td>
</tr>
<tr class="even">
<td>K-nearest neighbor classifiers, 463</td>
<td>119</td>
</tr>
<tr class="odd">
<td>Karhunen-Loeve transformation (prin</td>
<td>Linear methods</td>
</tr>
<tr class="even">
<td>cipal<br>components),<br>66–</td>
<td>for classification, 101–137</td>
</tr>
<tr class="odd">
<td>67, 79, 534–539</td>
<td>for regression, 43–99</td>
</tr>
<tr class="even">
<td>Karush-Kuhn-Tucker<br>conditions,</td>
<td>Linear models and least squares,</td>
</tr>
<tr class="odd">
<td>133, 420</td>
<td>11</td>
</tr>
<tr class="even">
<td>Kernel</td>
<td>Linear regression of an indicator</td>
</tr>
<tr class="odd">
<td>classification, 670</td>
<td>matrix, 103</td>
</tr>
<tr class="even">
<td>density classification, 210</td>
<td>Linear separability, 129</td>
</tr>
<tr class="odd">
<td>density estimation, 208–215</td>
<td>Linear smoother, 153</td>
</tr>
<tr class="even">
<td>function, 209</td>
<td>Link function, 296</td>
</tr>
<tr class="odd">
<td>logistic regression, 654</td>
<td>LLE,<br>see<br>Local linear embedding</td>
</tr>
<tr class="even">
<td>principal component, 547–550</td>
<td>Local false discovery rate, 693</td>
</tr>
<tr class="odd">
<td>string, 668–669</td>
<td>Local likelihood, 205</td>
</tr>
<tr class="even">
<td>trick, 660</td>
<td>Local linear embedding, 572</td>
</tr>
<tr class="odd">
<td>Kernel methods, 167–176, 208–215,</td>
<td>Local methods in high dimensions,</td>
</tr>
<tr class="even">
<td>423–438, 659</td>
<td>22–27</td>
</tr>
<tr class="odd">
<td>Knot, 141, 322</td>
<td>Local minima, 400</td>
</tr>
<tr class="even">
<td>Kriging, 171</td>
<td>Local polynomial regression, 197</td>
</tr>
<tr class="odd">
<td>Kruskal-Shephard scaling, 570</td>
<td>Local regression, 194, 200</td>
</tr>
<tr class="even">
<td>Kullback-Leibler distance, 561</td>
<td>Localization in time/frequency, 175</td>
</tr>
<tr class="odd">
<td></td>
<td>Loess (local regression), 194, 200</td>
</tr>
<tr class="even">
<td>Lagrange multipliers, 293</td>
<td>Log-linear model, 639</td>
</tr>
<tr class="odd">
<td>Landmark, 539</td>
<td>Log-odds ratio (logit), 119</td>
</tr>
<tr class="even">
<td>Laplacian, 545</td>
<td>Logistic (sigmoid) function, 393</td>
</tr>
<tr class="odd">
<td>Laplacian distribution, 72</td>
<td>Logistic regression, 119–128, 299</td>
</tr>
<tr class="even">
<td>LAR,<br>see<br>Least angle regression</td>
<td>Logit (log-odds ratio), 119</td>
</tr>
<tr class="odd">
<td>Lasso, 68–69, 86–90, 609, 635, 636,</td>
<td>Loss function, 18, 21, 219–223, 346</td>
</tr>
<tr class="even">
<td>661</td>
<td>Loss matrix, 310</td>
</tr>
<tr class="odd">
<td></td>
<td></td>
</tr>
</tbody>
</table>
<table class="caption-top table">
<colgroup>
<col style="width: 51%">
<col style="width: 48%">
</colgroup>
<thead>
<tr class="header">
<th>Lossless compression, 515</th>
<th>Mixture of experts, 329–332</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Lossy compression, 515</td>
<td>Mixtures and the EM algorithm,</td>
</tr>
<tr class="even">
<td>LVQ,<br>see<br>Learning Vector Quan</td>
<td>272–275</td>
</tr>
<tr class="odd">
<td>tization</td>
<td>MM algorithm, 294, 584</td>
</tr>
<tr class="even">
<td></td>
<td>Mode seekers, 507</td>
</tr>
<tr class="odd">
<td>Mahalanobis distance, 441</td>
<td>Model averaging and stacking, 288</td>
</tr>
<tr class="even">
<td>Majority vote, 337</td>
<td>Model combination, 289</td>
</tr>
<tr class="odd">
<td>Majorization, 294, 553</td>
<td>Model complexity, 221–222</td>
</tr>
<tr class="even">
<td>Majorize-Minimize algorithm, 294,</td>
<td></td>
</tr>
<tr class="odd">
<td>584</td>
<td>Model selection, 57, 222–223, 230–</td>
</tr>
<tr class="even">
<td>MAP (maximum aposteriori) es</td>
<td>231</td>
</tr>
<tr class="odd">
<td>timate, 270</td>
<td>Modified regression, 634</td>
</tr>
<tr class="even">
<td>Margin, 134, 418</td>
<td>Monte Carlo method, 250, 495</td>
</tr>
<tr class="odd">
<td>Market basket analysis, 488, 499</td>
<td>Mother wavelet, 178</td>
</tr>
<tr class="even">
<td>Markov chain Monte Carlo (MCMC)</td>
<td>Multidimensional scaling, 570–572</td>
</tr>
<tr class="odd">
<td>methods, 279</td>
<td>Multidimensional splines, 162</td>
</tr>
<tr class="even">
<td>Markov graph, 627</td>
<td>Multiedit algorithm, 480</td>
</tr>
<tr class="odd">
<td>Markov networks, 638–648</td>
<td>Multilayer perceptron, 400, 401</td>
</tr>
<tr class="even">
<td>MARS,<br>see<br>Multivariate adaptive</td>
<td>Multinomial distribution, 120</td>
</tr>
<tr class="odd">
<td>regression splines</td>
<td>Multiple additive regression trees</td>
</tr>
<tr class="even">
<td>MART,<br>see<br>Multiple additive re</td>
<td>(MART), 361</td>
</tr>
<tr class="odd">
<td>gression trees</td>
<td>Multiple hypothesis testing, 683–</td>
</tr>
<tr class="even">
<td>Maximum<br>likelihood<br>estimation,</td>
<td>693</td>
</tr>
<tr class="odd">
<td>31, 261, 265</td>
<td>Multiple minima, 291, 400</td>
</tr>
<tr class="even">
<td>MCMC,<br>see<br>Markov Chain Monte</td>
<td>Multiple<br>outcome<br>shrinkage<br>and</td>
</tr>
<tr class="odd">
<td>Carlo Methods</td>
<td>selection, 84</td>
</tr>
<tr class="even">
<td>MDL,<br>see<br>Minimum<br>description</td>
<td>Multiple outputs, 56, 84, 103–106</td>
</tr>
<tr class="odd">
<td>length</td>
<td>Multiple regression from simple uni</td>
</tr>
<tr class="even">
<td>Mean field approximation, 641</td>
<td>variate regression, 52</td>
</tr>
<tr class="odd">
<td>Mean squared error, 24, 285</td>
<td>Multiresolution analysis, 178</td>
</tr>
<tr class="even">
<td>Memory-based method, 463</td>
<td>Multivariate<br>adaptive<br>regression</td>
</tr>
<tr class="odd">
<td>Metropolis-Hastings algorithm, 282</td>
<td>splines (MARS), 321–327</td>
</tr>
<tr class="even">
<td></td>
<td>Multivariate nonparametric regres</td>
</tr>
<tr class="odd">
<td>Minimum description length (MDL),</td>
<td>sion, 445</td>
</tr>
<tr class="even">
<td>235<br>Minorization, 294, 553</td>
<td>Nadaraya–Watson estimate, 193</td>
</tr>
<tr class="odd">
<td>Minorize-Maximize algorithm, 294,</td>
<td>Naive Bayes classifier, 108, 210–</td>
</tr>
<tr class="even">
<td>584</td>
<td>211, 694</td>
</tr>
<tr class="odd">
<td></td>
<td></td>
</tr>
<tr class="even">
<td>Misclassification error, 17, 309</td>
<td>Natural cubic splines, 144–146</td>
</tr>
<tr class="odd">
<td>Missing data, 276, 332–333</td>
<td>Nearest centroids, 670</td>
</tr>
<tr class="even">
<td>Missing predictor values, 332–333</td>
<td>Nearest<br>neighbor<br>methods,<br>463–</td>
</tr>
<tr class="odd">
<td>Mixing proportions, 214</td>
<td>483</td>
</tr>
<tr class="even">
<td>Mixture discriminant analysis, 449–</td>
<td>Nearest shrunken centroids, 651–</td>
</tr>
<tr class="odd">
<td>455</td>
<td>654, 694</td>
</tr>
<tr class="even">
<td>Mixture modeling, 214–215, 272–<br>275, 449–455, 692</td>
<td>Network diagram, 392<br>Neural networks, 389–416</td>
</tr>
<tr class="odd">
<td></td>
<td></td>
</tr>
</tbody>
</table>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 49%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Index<br>743</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Newton’s method (Newton-Raphson</td>
<td>Perceptron, 392–416</td>
</tr>
<tr class="even">
<td>procedure), 120–122</td>
<td>Piecewise polynomials and splines,</td>
</tr>
<tr class="odd">
<td>Non-negative matrix factorization,</td>
<td>36, 143</td>
</tr>
<tr class="even">
<td>553–554</td>
<td>Posterior</td>
</tr>
<tr class="odd">
<td>Nonparametric logistic regression,</td>
<td>distribution, 268</td>
</tr>
<tr class="even">
<td>299–304</td>
<td>probability, 233–235, 268</td>
</tr>
<tr class="odd">
<td>Normal<br>(Gaussian)<br>distribution,</td>
<td>Power method, 577</td>
</tr>
<tr class="even">
<td>16, 31</td>
<td>Pre-conditioning, 681–683</td>
</tr>
<tr class="odd">
<td>Normal equations, 12</td>
<td>Prediction accuracy, 329</td>
</tr>
<tr class="even">
<td>Numerical optimization, 395–396</td>
<td>Prediction error, 18</td>
</tr>
<tr class="odd">
<td></td>
<td>Predictive distribution, 268</td>
</tr>
<tr class="even">
<td>Object dissimilarity, 505–507</td>
<td>PRIM,<br>see<br>Patient rule induction</td>
</tr>
<tr class="odd">
<td>Online algorithm, 397</td>
<td>method</td>
</tr>
<tr class="even">
<td>Optimal scoring, 445, 450–451</td>
<td>Principal components, 66–67, 79–</td>
</tr>
<tr class="odd">
<td>Optimal separating hyperplane, 132–</td>
<td>80, 534–539, 547</td>
</tr>
<tr class="even">
<td>135</td>
<td>regression, 79–80</td>
</tr>
<tr class="odd">
<td>Optimism of the training error rate,</td>
<td>sparse, 550</td>
</tr>
<tr class="even">
<td>228–230</td>
<td>supervised, 674</td>
</tr>
<tr class="odd">
<td>Ordered categorical (ordinal) pre</td>
<td>Principal curves and surfaces, 541–</td>
</tr>
<tr class="even">
<td>dictor, 10, 504</td>
<td>544</td>
</tr>
<tr class="odd">
<td>Ordered features, 666</td>
<td>Principal points, 541</td>
</tr>
<tr class="even">
<td>Orthogonal predictors, 53</td>
<td>Prior distribution, 268–272</td>
</tr>
<tr class="odd">
<td>Overfitting, 220, 228–230, 364</td>
<td>Procrustes</td>
</tr>
<tr class="even">
<td></td>
<td>average, 540</td>
</tr>
<tr class="odd">
<td>PageRank, 576</td>
<td>distance, 539</td>
</tr>
<tr class="even">
<td>Pairwise distance, 668</td>
<td>Projection pursuit, 389–392, 565</td>
</tr>
<tr class="odd">
<td>Pairwise Markov property, 628</td>
<td>regression, 389–392</td>
</tr>
<tr class="even">
<td>Parametric bootstrap, 264</td>
<td>Prototype classifier, 459–463</td>
</tr>
<tr class="odd">
<td>Partial dependence plots, 369–370</td>
<td>Prototype methods, 459–463</td>
</tr>
<tr class="even">
<td>Partial least squares, 80–82, 680</td>
<td>Proximity matrices, 503</td>
</tr>
<tr class="odd">
<td>Partition function, 638</td>
<td>Pruning, 308</td>
</tr>
<tr class="even">
<td>Parzen window, 208</td>
<td></td>
</tr>
<tr class="odd">
<td>Pasting, 318</td>
<td>QR decomposition, 55</td>
</tr>
<tr class="even">
<td>Path algorithm, 73–79, 86–89, 432</td>
<td>Quadratic approximations and in</td>
</tr>
<tr class="odd">
<td>Patient rule induction method(PRIM),</td>
<td>ference, 124</td>
</tr>
<tr class="even">
<td>317–321, 499–501</td>
<td>Quadratic discriminant function,</td>
</tr>
<tr class="odd">
<td>Peeling, 318</td>
<td>108, 110</td>
</tr>
<tr class="even">
<td>Penalization, 607,<br>see<br>regulariza</td>
<td></td>
</tr>
<tr class="odd">
<td>tion</td>
<td>Radial basis function (RBF) net</td>
</tr>
<tr class="even">
<td>Penalized discriminant analysis, 446–</td>
<td>work, 392</td>
</tr>
</tbody>
</table>
<p>449</p>
<p>171</p>
<p>Penalty matrix, 152, 189</p>
<p>Penalized polynomial regression,</p>
<p>Penalized regression, 34, 61–69, 171</p>
<p>work, 392 Radial basis functions, 212–214, 275, 393 Radial kernel, 548 Random forest, 409, 587–604 algorithm, 588</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 49%">
</colgroup>
<thead>
<tr class="header">
<th>bias, 596–601</th>
<th>Separating hyperplanes, 136, 417–</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>comparison to boosting, 589</td>
<td>419</td>
</tr>
<tr class="even">
<td>example, 589</td>
<td>Separator, 628</td>
</tr>
<tr class="odd">
<td>out-of-bag (oob), 592</td>
<td>Shape average, 482, 540</td>
</tr>
<tr class="even">
<td>overfit, 596</td>
<td>Shrinkage methods, 61–69, 652</td>
</tr>
<tr class="odd">
<td>proximity plot, 595</td>
<td>Sigmoid, 393</td>
</tr>
<tr class="even">
<td>variable importance, 593</td>
<td>Significance Analysis of Microar</td>
</tr>
<tr class="odd">
<td>variance, 597–601</td>
<td>rays, 690–693</td>
</tr>
<tr class="even">
<td>Rao score test, 125</td>
<td>Similarity<br>measure,<br>see<br>Dissimi</td>
</tr>
<tr class="odd">
<td>Rayleigh quotient, 116</td>
<td>larity measure</td>
</tr>
<tr class="even">
<td>Receiver operating characteristic</td>
<td>Single index model, 390</td>
</tr>
<tr class="odd">
<td>(ROC) curve, 317</td>
<td>Singular value decomposition, 64,</td>
</tr>
<tr class="even">
<td>Reduced-rank linear discriminant</td>
<td>535–536, 659</td>
</tr>
<tr class="odd">
<td>analysis, 113</td>
<td>singular values, 535</td>
</tr>
<tr class="even">
<td>Regression, 11–14, 43–99, 200–204</td>
<td>singular vectors, 535</td>
</tr>
<tr class="odd">
<td>Regression spline, 144</td>
<td>Sliced inverse regression, 480</td>
</tr>
<tr class="even">
<td>Regularization, 34, 167–176</td>
<td>Smoother, 139–156, 192–199</td>
</tr>
<tr class="odd">
<td>Regularized discriminant analysis,</td>
<td>matrix, 153</td>
</tr>
<tr class="even">
<td>112–113, 654</td>
<td>Smoothing parameter, 37, 156–161,</td>
</tr>
<tr class="odd">
<td>Relevance network, 631</td>
<td>198–199</td>
</tr>
<tr class="even">
<td>Representer of evaluation, 169</td>
<td>Smoothing spline, 151–156</td>
</tr>
<tr class="odd">
<td>Reproducing kernel Hilbert space,</td>
<td>Soft clustering, 512</td>
</tr>
<tr class="even">
<td>167–176, 428–429</td>
<td>Soft-thresholding, 653</td>
</tr>
<tr class="odd">
<td>Reproducing property, 169</td>
<td>Softmax function, 393</td>
</tr>
<tr class="even">
<td>Responsibilities, 274–275</td>
<td>SOM,<br>see<br>Self-organizing map</td>
</tr>
<tr class="odd">
<td>Ridge regression, 61–68, 650, 659</td>
<td>Sparse, 175, 304, 610–613, 636</td>
</tr>
<tr class="even">
<td>Risk factor, 122</td>
<td>additive model, 91</td>
</tr>
<tr class="odd">
<td>Robust fitting, 346–350</td>
<td>graph, 625, 635</td>
</tr>
<tr class="even">
<td>Rosenblatt’s perceptron learning</td>
<td>Specificity of a test, 314–317</td>
</tr>
<tr class="odd">
<td>algorithm, 130</td>
<td>Spectral clustering, 544–547</td>
</tr>
<tr class="even">
<td>Rug plot, 303</td>
<td>Spline, 186</td>
</tr>
<tr class="odd">
<td>Rulefit, 623</td>
<td>additive, 297–299</td>
</tr>
<tr class="even">
<td></td>
<td>cubic, 151–153</td>
</tr>
<tr class="odd">
<td>SAM, 690–693,<br>see<br>Significance Anal</td>
<td>cubic smoothing, 151–153</td>
</tr>
<tr class="even">
<td>ysis of Microarrays</td>
<td>interaction, 428</td>
</tr>
<tr class="odd">
<td>Sammon mapping, 571</td>
<td>regression, 144</td>
</tr>
<tr class="even">
<td>SCAD, 92</td>
<td>smoothing, 151–156</td>
</tr>
<tr class="odd">
<td>Scaling of the inputs, 398</td>
<td>thin plate, 165</td>
</tr>
<tr class="even">
<td>Schwarz’s criterion, 230–235</td>
<td>Squared error loss, 18, 24, 37, 219</td>
</tr>
<tr class="odd">
<td>Score equations, 120, 265</td>
<td>SRM,<br>see<br>Structural risk minimiza</td>
</tr>
<tr class="even">
<td>Self-consistency property, 541–543</td>
<td>tion</td>
</tr>
<tr class="odd">
<td>Self-organizing map (SOM), 528–</td>
<td>Stacking (stacked generalization),</td>
</tr>
<tr class="even">
<td>534</td>
<td>290</td>
</tr>
<tr class="odd">
<td>Sensitivity of a test, 314–317</td>
<td>Starting values, 397</td>
</tr>
<tr class="even">
<td>Separating hyperplane, 132–135</td>
<td>Statistical decision theory, 18–22</td>
</tr>
</tbody>
</table>
<p>Weights in a neural network, 395 Within class covariance matrix, 114,</p>
<p>446</p>
<p>Statistical model, 28–29 Steepest descent, 358, 395–397 Stepwise selection, 60 Stochastic approximation, 397 Stochastic search (bumping), 290– 292 Stress function, 570–572 Structural risk minimization (SRM), 239–241 Subset selection, 57–60 Supervised learning, 2 Supervised principal components, 674–681 Support vector classifier, 417–421, 654 multiclass, 657 Support vector machine, 423–437 SURE shrinkage method, 179 Survival analysis, 674 Survival curve, 674 SVD, see Singular value decomposition Symmlet basis, 176 Tangent distance, 471–475 Tanh activation function, 424 Target variables, 10 Tensor product basis, 162 Test error, 220–223 Test set, 220 Thin plate spline, 165 Thinning strategy, 189 Undirected graph, 625–648 Universal approximator, 390 Unsupervised learning, 2, 485–585 Unsupervised learning as supervised learning, 495–497 Validation set, 222 Vapnik-Chervonenkis (VC) dimension, 237–239 Variable importance plot, 594 Variable types and terminology, 9 Variance, 16, 25, 37, 158–161, 219 between, 114 within, 114, 446 Variance reduction, 588 Varying coefficient models, 203– 204 VC dimension, see Vapnik–Chervonenkis dimension Vector quantization, 514–515 Voronoi regions, 510 Wald test, 125 Wavelet basis functions, 176–179 smoothing, 174 transform, 176–179 Weak learner, 383, 605 Weakest link pruning, 308 Webpages, 576 Website for book, 8 Weight decay, 398 Weight elimination, 398</p>
<p>Trace of a matrix, 153 Training epoch, 397 Training error, 220–223 Training set, 219–223 Tree for regression, 307–308 Tree-based methods, 305–317 Trees for classification, 308–310 Trellis display, 202</p>



</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../chapters/20-author-index.html" class="pagination-link" aria-label="Author Index">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Author Index</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../references.html" class="pagination-link" aria-label="References">
        <span class="nav-page-text">References</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>